// Cẩm nang ngữ pháp tiếng Trung (/chinese/handbook): gom ngữ pháp HSK 1+2, 3, 4 theo NGHĨA/CHỨC NĂNG thay vì theo bài,
// để tra nhanh những mẫu cùng nghĩa nhưng cách dùng khác nhau (vd "nhưng" có 但是, 可是, 却, 然而, 而…). Hiển thị bằng
// component dùng chung components/shared/GrammarHandbook.tsx (cùng kiểu với cẩm nang Korean).
//
// Key của HANDBOOK_ITEMS = `${lesson}|${hanzi}` khớp CHÍNH XÁC với thẻ ngữ pháp trong DB (chinese_cards.hanzi).
// Thẻ ngữ pháp mới chưa có ở đây sẽ rơi vào nhóm "Chưa phân loại" ở cuối trang (không bị ẩn mất).

import type { HandbookCategory, HandbookGroup, HandbookItem } from '@/lib/handbook/types'

export const HANDBOOK_GROUPS: HandbookGroup[] = [
  { key: 'clause', title: 'Nối câu – Quan hệ từ' },
  { key: 'adverb', title: 'Phó từ' },
  { key: 'modal', title: 'Năng nguyện – Quan điểm' },
  { key: 'sentence', title: 'Kiểu câu' },
  { key: 'complement', title: 'Bổ ngữ' },
  { key: 'word', title: 'Giới từ – Từ loại' },
]

export const HANDBOOK_CATEGORIES: HandbookCategory[] = [
  { key: 'cause', group: 'clause', icon: '🔗', title: 'Nguyên nhân – Kết quả', intro: 'Các cặp "vì… nên…", "do… vì vậy…". Khác nhau ở khẩu ngữ hay văn viết.' },
  { key: 'condition', group: 'clause', icon: '🧩', title: 'Điều kiện – Giả định', intro: '"Nếu… thì…", "chỉ cần…", "chỉ có…": khác ở loại điều kiện.' },
  { key: 'concession', group: 'clause', icon: '🛡️', title: 'Nhượng bộ – Bất kể', intro: '"Dù… cũng…", "bất kể…": sự thật đã xảy ra hay chỉ là giả định.' },
  { key: 'contrast', group: 'clause', icon: '⚖️', title: 'Chuyển ngoặt (nhưng…)', intro: 'Các cách nói "nhưng": mạnh hay nhẹ, khẩu ngữ hay văn viết, đứng ở đâu trong câu.' },
  { key: 'progressive', group: 'clause', icon: '➕', title: 'Tăng tiến – Bổ sung', intro: '"Không những… mà còn…", "ngoài ra", "thậm chí", "ngay cả…".' },
  { key: 'choice', group: 'clause', icon: '🔀', title: 'Song song – Lựa chọn', intro: '"Vừa… vừa…", "hay là / hoặc", "không phải… mà là…".' },
  { key: 'sequence', group: 'clause', icon: '⛓️', title: 'Trình tự – Thời điểm', intro: '"Trước / sau / khi…", "trước tiên… sau đó…", "vừa… là…".' },
  { key: 'purpose', group: 'clause', icon: '🎯', title: 'Mục đích – Cách thức', intro: '"Để…", "vì…", "thông qua…".' },

  { key: 'degree', group: 'adverb', icon: '🌡️', title: 'Mức độ', intro: 'Rất, quá, nhất, hơi, cực kỳ…: khác ở vị trí và sắc thái.' },
  { key: 'trend', group: 'adverb', icon: '📈', title: 'Ngày càng…', intro: 'Mức độ thay đổi theo thời gian hoặc theo một yếu tố khác.' },
  { key: 'aspect', group: 'adverb', icon: '⏳', title: 'Đang – Đã – Từng (在, 了, 着, 过)', intro: 'Hành động đang diễn ra, đã xong, đang duy trì hay đã từng trải qua.' },
  { key: 'timing', group: 'adverb', icon: '⏰', title: 'Đã, vừa, sắp, cuối cùng', intro: 'Phó từ chỉ thời điểm xảy ra của sự việc.' },
  { key: 'jiucai', group: 'adverb', icon: '⚡', title: '就 và 才', intro: '就 = sớm / dễ hơn mong đợi, 才 = muộn / khó hơn mong đợi.' },
  { key: 'repeat', group: 'adverb', icon: '🔁', title: 'Lặp lại – Vẫn (再, 又, 还)', intro: '"Lại, nữa, vẫn": việc đã xảy ra hay sẽ xảy ra, nói hay viết.' },
  { key: 'scope', group: 'adverb', icon: '🎚️', title: 'Phạm vi – Tần suất', intro: '"Đều, mỗi, chỉ, thường, thỉnh thoảng, từ trước tới nay…".' },
  { key: 'guess', group: 'adverb', icon: '🔮', title: 'Phỏng đoán – Chắc chắn', intro: 'Từ "có lẽ" đến "chắc chắn": mức độ tin tưởng khác nhau.' },
  { key: 'tone', group: 'adverb', icon: '❗', title: 'Ngữ khí – Bất ngờ – Phản vấn', intro: 'Thái độ người nói: bất ngờ, hoá ra, rốt cuộc, chẳng lẽ…' },

  { key: 'modal', group: 'modal', icon: '💪', title: 'Động từ năng nguyện', intro: '"Biết, có thể, muốn, nên, phải": khác ở nguồn gốc của khả năng / nghĩa vụ.' },
  { key: 'opinion', group: 'modal', icon: '💬', title: 'Nhận định – Quan điểm', intro: '"Cho rằng, tưởng rằng, đối với… mà nói, theo… thấy, ví dụ như".' },

  { key: 'question', group: 'sentence', icon: '❓', title: 'Câu hỏi', intro: 'Từ để hỏi và các kiểu câu hỏi.' },
  { key: 'request', group: 'sentence', icon: '🙋', title: 'Cầu khiến – Đề nghị', intro: 'Rủ, khuyên, cấm và dặn dò.' },
  { key: 'ba', group: 'sentence', icon: '🫳', title: 'Câu chữ 把', intro: '把 đưa tân ngữ lên trước động từ để nói hành động tác động lên nó ra sao.' },
  { key: 'passive', group: 'sentence', icon: '🔄', title: 'Bị động – Kiêm ngữ', intro: '"Bị / được" và "bảo / khiến ai làm gì".' },
  { key: 'compare', group: 'sentence', icon: '📏', title: 'So sánh', intro: 'So sánh hơn, ngang bằng và không bằng.' },
  { key: 'special', group: 'sentence', icon: '🧱', title: 'Câu đặc biệt', intro: 'Câu liên động, câu 是…的, câu vị ngữ chủ vị.' },

  { key: 'resultComp', group: 'complement', icon: '✅', title: 'Bổ ngữ kết quả – khả năng', intro: 'Hành động đạt kết quả gì, có làm được hay không.' },
  { key: 'direction', group: 'complement', icon: '↗️', title: 'Bổ ngữ xu hướng', intro: 'Hướng của hành động và các nghĩa mở rộng (起来, 下去, 上, 过来…).' },
  { key: 'quantity', group: 'complement', icon: '🔢', title: 'Thời lượng – Động lượng – Trạng thái', intro: 'Làm bao lâu, bao nhiêu lần, làm như thế nào.' },

  { key: 'prep', group: 'word', icon: '🧭', title: 'Giới từ – Từ nối danh từ', intro: 'Giới từ chỉ nơi chốn, đối tượng, căn cứ, phương hướng.' },
  { key: 'particle', group: 'word', icon: '🪢', title: '的 / 地 / 之', intro: 'Trợ từ kết cấu nối định ngữ và trạng ngữ.' },
  { key: 'measure', group: 'word', icon: '🏷️', title: 'Phương vị – Lượng từ', intro: 'Vị trí (trên, dưới, trước…), lượng từ và số nhiều.' },
  { key: 'numbers', group: 'word', icon: '🧮', title: 'Số – Thời gian – Ước lượng', intro: 'Số đếm, giờ, ngày tháng, tiền, ước lượng, phần trăm.' },
  { key: 'verbs', group: 'word', icon: '🛠️', title: 'Động từ đặc biệt', intro: 'Lặp động từ, động từ ly hợp và cách dùng một số động từ hay nhầm.' },
  { key: 'misc', group: 'word', icon: '🔹', title: 'Mẫu riêng lẻ', intro: 'Không có mẫu cùng nghĩa để so sánh.' },
]

// `${lesson}|${hanzi}` → nhóm + điểm phân biệt. Một mẫu chỉ thuộc đúng 1 nhóm.
export const HANDBOOK_ITEMS: Record<string, HandbookItem> = {
  // ── HSK 1+2 (bài 1-25) ──
  '1|什么': { cat: 'question', tip: 'Hỏi "cái gì": đặt vào đúng chỗ của thứ muốn hỏi, không thêm 吗.' },
  '1|的': { cat: 'particle', tip: 'Sở hữu "của": 我的书. Người thân / tổ chức thân thiết thì lược: 我妈妈.' },
  '1|呢': { cat: 'question', tip: 'Hỏi lại "còn… thì sao?": 我很好，你呢？' },
  '1|多少': { cat: 'question', tip: 'Hỏi số lượng (thường trên 10), không cần lượng từ.' },
  '1|数字': { cat: 'numbers', tip: 'Số đếm 0–99, trăm 百, nghìn 千, vạn 万.' },
  '2|吗': { cat: 'question', tip: 'Thêm cuối câu trần thuật → câu hỏi có / không.' },
  '2|了': { cat: 'aspect', tip: '了 cuối câu: tình huống đã THAY ĐỔI ("…rồi").' },
  '2|多大 / 几岁 / 年纪': { cat: 'question', tip: 'Hỏi tuổi: 几岁 (trẻ em), 多大 (ngang hàng), 多大年纪 (người lớn tuổi).' },
  '2|有': { cat: 'verbs', tip: '"Có" (sở hữu, tồn tại). Phủ định là 没有, không dùng 不有.' },
  '2|和': { cat: 'prep', tip: '"Và" nối danh từ / đại từ. ✗ nối hai câu.' },
  '2|都': { cat: 'scope', tip: '"Đều": đứng sau chủ ngữ, trước động từ; chủ ngữ là số nhiều.' },
  '3|谁': { cat: 'question', tip: 'Hỏi "ai".' },
  '3|上 / 下 / 里': { cat: 'measure', tip: 'Đặt SAU danh từ để chỉ vị trí: 桌子上, 房间里.' },
  '3|个 / 本 (lượng từ)': { cat: 'measure', tip: '这 / 那 + lượng từ + danh từ: 这本书. 个 dùng chung, 本 cho sách vở.' },
  '3|在': { cat: 'prep', tip: '在 + nơi chốn làm vị ngữ: "ở" (他在家).' },
  '3|哪儿': { cat: 'question', tip: 'Hỏi "ở đâu".' },
  '4|会': { cat: 'modal', tip: '"Biết": kỹ năng có được nhờ HỌC (会说汉语). Còn nghĩa "sẽ" (khả năng xảy ra).' },
  '4|还': { cat: 'repeat', tip: '"Còn": bổ sung thêm (我还要一杯).' },
  '4|很 + Tính từ': { cat: 'degree', tip: 'Tính từ làm vị ngữ phải có phó từ mức độ; 很 ở đây không mang nghĩa "rất" mạnh.' },
  '4|怎么': { cat: 'question', tip: '怎么 + động từ: hỏi CÁCH làm ("làm thế nào").' },
  '4|在': { cat: 'prep', tip: '在 + nơi + động từ: nơi diễn ra hành động (我在学校学习).' },
  '4|吧': { cat: 'request', tip: 'Cuối câu: đề nghị, rủ ("…nhé", "…đi").' },
  '5|年 / 月 / 日(号) / 星期': { cat: 'numbers', tip: 'Năm → tháng → ngày → thứ (từ lớn đến nhỏ). Văn nói dùng 号.' },
  '5|那': { cat: 'cause', tip: '"Thế thì / vậy…": rút ra kết luận từ lời người kia.' },
  '5|们': { cat: 'measure', tip: '们 sau danh từ chỉ người → số nhiều. ✗ khi đã có số đếm (三个学生).' },
  '5|连动句': { cat: 'special', tip: 'Hai động từ chung chủ ngữ, theo thứ tự xảy ra / mục đích (去商店买东西).' },
  '5|真': { cat: 'degree', tip: '"Thật là…": cảm thán, chỉ đứng làm vị ngữ (✗ 真 + tính từ + danh từ).' },
  '6|点 / 分 / 秒': { cat: 'numbers', tip: 'Giờ 点 – phút 分 – giây 秒.' },
  '6|差 / 刻': { cat: 'numbers', tip: '差 = kém (差五分八点), 刻 = 15 phút (一刻, 三刻).' },
  '6|时间词 (trạng ngữ)': { cat: 'numbers', tip: 'Từ chỉ thời gian đứng TRƯỚC động từ (trước hoặc sau chủ ngữ).' },
  '6|从…到': { cat: 'prep', tip: '"Từ… đến…" cho thời gian hoặc nơi chốn.' },
  '7|元(块) / 角(毛) / 分': { cat: 'numbers', tip: 'Tiền: 元 / 角 / 分 khi viết, 块 / 毛 / 分 khi nói.' },
  '7|二 / 两': { cat: 'numbers', tip: '两 đứng trước lượng từ (两个); 二 khi đếm số, số thứ tự, hàng chục (十二).' },
  '7|再': { cat: 'repeat', tip: '再: lặp lại / tiếp tục ở TƯƠNG LAI ("nữa", "lại").' },
  '7|太': { cat: 'degree', tip: '"…quá": 太 + tính từ + 了, thường mang ý quá mức.' },
  '7|几 / 多少': { cat: 'question', tip: '几: số nhỏ (dưới 10), cần lượng từ. 多少: số bất kỳ, không cần lượng từ.' },
  '8|怎么样': { cat: 'question', tip: 'Hỏi tình trạng / ý kiến: "thế nào?". Cuối câu đề nghị: "…được không?".' },
  '8|主谓谓语句': { cat: 'special', tip: 'Vị ngữ là một cụm chủ – vị: 他身体很好.' },
  '8|最': { cat: 'degree', tip: '"Nhất": so sánh cao nhất.' },
  '8|不A不B': { cat: 'degree', tip: '"Không A cũng không B": vừa đủ (不大不小).' },
  '9|就': { cat: 'jiucai', tip: '就: "chính là" / "liền, ngay": nhấn mạnh, khẳng định.' },
  '9|往': { cat: 'prep', tip: '"Về phía": 往 + phương hướng + động từ (往前走).' },
  '9|边 / 面': { cat: 'measure', tip: 'Phương vị từ: 前边, 后面, 左边… chỉ vị trí.' },
  '9|离': { cat: 'prep', tip: '"Cách": A 离 B + 远 / 近 (khoảng cách).' },
  '9|多 + Tính từ': { cat: 'question', tip: '"Bao + tính từ?": 多远, 多高, 多长.' },
  '9|……以后': { cat: 'sequence', tip: '"Sau…": thời điểm / sự việc + 以后.' },
  '10|在 (đang)': { cat: 'aspect', tip: '在 + động từ (+ 呢): hành động ĐANG diễn ra.' },
  '10|先…然后…': { cat: 'sequence', tip: '"Trước tiên… sau đó…": trình tự hai hành động.' },
  '10|想': { cat: 'modal', tip: '"Muốn": mong muốn, ý định (nhẹ hơn 要).' },
  '10|骑 / 坐 / 开': { cat: 'verbs', tip: '骑: cưỡi (xe đạp, ngựa); 坐: ngồi trên phương tiện; 开: lái.' },
  '11|给': { cat: 'prep', tip: '"Cho": 给 + người + động từ (đối tượng nhận).' },
  '11|了 (động thái)': { cat: 'aspect', tip: '了 sau động từ: hành động đã HOÀN THÀNH.' },
  '11|极了': { cat: 'degree', tip: 'Tính từ + 极了: "…cực kỳ" (khẩu ngữ).' },
  '11|的 (cụm từ)': { cat: 'particle', tip: 'Cụm "…的" thay cho danh từ: 红的 (cái màu đỏ).' },
  '11|Danh từ + 呢？': { cat: 'question', tip: 'N + 呢？: hỏi "N đâu rồi?".' },
  '11|多了': { cat: 'degree', tip: 'Tính từ + 多了: "…hơn nhiều" (so với trước / người khác).' },
  '11|是……的': { cat: 'special', tip: 'Nhấn mạnh thời gian / nơi / cách thức của việc ĐÃ xảy ra.' },
  '12|一下': { cat: 'verbs', tip: 'Động từ + 一下: làm thử, làm một chút (nhẹ nhàng).' },
  '12|就是': { cat: 'contrast', tip: '"Chỉ có điều là…": nêu điểm chưa ổn sau lời khen.' },
  '12|一点儿 / 有点儿': { cat: 'degree', tip: '有点儿 + tính từ: "hơi…" (không hài lòng). Tính từ + 一点儿: "…hơn một chút".' },
  '12|已经': { cat: 'timing', tip: '"Đã": thường đi với 了 cuối câu.' },
  '13|动词重叠': { cat: 'verbs', tip: 'Lặp động từ (看看, 休息休息): làm thử, làm chút, nhẹ nhàng.' },
  '13|还是 / 或者': { cat: 'choice', tip: '还是: "hay là" trong câu HỎI. 或者: "hoặc" trong câu trần thuật.' },
  '13|时量补语': { cat: 'quantity', tip: 'Động từ + khoảng thời gian: làm KÉO DÀI bao lâu (学了两年).' },
  '13|A不A': { cat: 'question', tip: 'Câu hỏi chính phản: 去不去？ (không thêm 吗).' },
  '14|别 / 不要': { cat: 'request', tip: '"Đừng": khuyên / cấm người nghe làm gì.' },
  '14|还 (vẫn)': { cat: 'repeat', tip: '还: "vẫn": trạng thái tiếp tục, chưa thay đổi.' },
  '14|对': { cat: 'prep', tip: '"Đối với": đối tượng của thái độ (对我很好).' },
  '14|结果补语': { cat: 'resultComp', tip: 'Động từ + 完 / 好 / 到 / 懂…: kết quả của hành động.' },
  '14|这么 / 那么': { cat: 'degree', tip: '"Như thế này / thế kia": nhấn mạnh mức độ.' },
  '15|的 (định ngữ động từ)': { cat: 'particle', tip: 'Cụm động từ + 的 + danh từ: 我买的书.' },
  '15|是不是': { cat: 'question', tip: '"…phải không?": hỏi xác nhận điều mình đoán.' },
  '15|第': { cat: 'numbers', tip: '第 + số: số thứ tự (第一).' },
  '15|可能': { cat: 'guess', tip: '"Có lẽ": khả năng có thể xảy ra.' },
  '15|能': { cat: 'modal', tip: '"Có thể": năng lực, điều kiện cho phép (khác 会: kỹ năng học được).' },
  '15|比': { cat: 'compare', tip: 'A 比 B + tính từ: so sánh hơn. ✗ dùng 很 trước tính từ.' },
  '16|得 (bổ ngữ trạng thái)': { cat: 'quantity', tip: 'Động từ + 得 + đánh giá: 说得很好 (mức độ, trạng thái của hành động).' },
  '16|死了': { cat: 'degree', tip: 'Tính từ + 死了: "…chết mất" (khẩu ngữ, cảm xúc mạnh).' },
  '16|每': { cat: 'scope', tip: '"Mỗi": 每 + lượng từ + danh từ, thường đi với 都.' },
  '16|因为…所以…': { cat: 'cause', tip: '"Bởi vì… cho nên…": cặp nhân quả cơ bản, dùng mọi lúc.' },
  '16|得 (děi)': { cat: 'modal', tip: '"Phải" (khẩu ngữ). Phủ định là 不用, không nói 不得.' },
  '16|就 / 才': { cat: 'jiucai', tip: '就: sớm / nhanh / dễ hơn mong đợi. 才: muộn / chậm / khó hơn mong đợi.' },
  '17|以前': { cat: 'sequence', tip: '"Trước / trước khi": thời điểm + 以前; đứng đầu câu = "trước đây".' },
  '17|离合词': { cat: 'verbs', tip: 'Động từ ly hợp (见面, 睡觉): thành phần khác chen vào giữa (见了面).' },
  '17|哪': { cat: 'question', tip: '哪 + lượng từ + danh từ: "…nào?".' },
  '17|好 / 完': { cat: 'resultComp', tip: '完: làm XONG. 好: làm xong và đạt yêu cầu, sẵn sàng.' },
  '17|一会儿 / 一下': { cat: 'verbs', tip: '一会儿: một lúc (khoảng thời gian). 一下: một chút, làm thử.' },
  '18|看起来': { cat: 'guess', tip: '"Xem ra, trông có vẻ": nhận định dựa trên bề ngoài.' },
  '18|着': { cat: 'aspect', tip: '着: trạng thái đang DUY TRÌ (门开着, 坐着).' },
  '18|地': { cat: 'particle', tip: 'Tính từ + 地 + động từ: "một cách…" (认真地学习).' },
  '18|……的时候': { cat: 'sequence', tip: '"Khi, lúc…".' },
  '19|不是……吗？': { cat: 'tone', tip: 'Phản vấn "chẳng phải… sao?": khẳng định mạnh.' },
  '19|过': { cat: 'aspect', tip: '过: đã TỪNG trải qua (kinh nghiệm).' },
  '19|才 (chỉ mới)': { cat: 'jiucai', tip: '才 + số lượng: "chỉ mới" (ít hơn mong đợi).' },
  '19|动量补语': { cat: 'quantity', tip: 'Động từ + số lần (次, 遍): làm bao nhiêu LẦN.' },
  '19|概数 (hai số liền nhau)': { cat: 'numbers', tip: 'Hai số liền nhau = ước lượng (三四个).' },
  '20|都……了': { cat: 'timing', tip: '"Đã… rồi": nhấn mạnh đã muộn / đã nhiều.' },
  '20|怎么 (hỏi nguyên nhân)': { cat: 'question', tip: '怎么 (+ 不 / 没) + động từ: hỏi "sao lại…" kèm ngạc nhiên.' },
  '20|一……就……': { cat: 'sequence', tip: '"Vừa… là…": hai việc nối tiếp ngay.' },
  '21|虽然……但是……': { cat: 'contrast', tip: '"Tuy… nhưng…": cặp chuyển ngoặt cơ bản.' },
  '21|……以内': { cat: 'numbers', tip: '"Trong vòng": phạm vi thời gian / số lượng.' },
  '21|多 (ước lượng)': { cat: 'numbers', tip: 'Số + 多: "hơn" (十多个).' },
  '21|应该': { cat: 'modal', tip: '"Nên": lời khuyên, lẽ phải.' },
  '22|从……起': { cat: 'sequence', tip: '"Từ… trở đi": mốc bắt đầu.' },
  '22|吧 (2)': { cat: 'question', tip: '吧 cuối câu hỏi: đoán và cần xác nhận ("…nhỉ?").' },
  '22|一……也 / 都 + 不': { cat: 'tone', tip: '"Một… cũng không": phủ định tuyệt đối (一个人也没有).' },
  '22|趋向补语 (单)': { cat: 'direction', tip: 'Động từ + 来 / 去: hướng hành động so với người nói.' },
  '23|哪有时间': { cat: 'tone', tip: '"Làm gì có thời gian": phản vấn để phủ định.' },
  '23|不是A就是B': { cat: 'choice', tip: '"Không phải A thì là B": chỉ có 2 khả năng.' },
  '23|再 (thời gian + 再 + động từ)': { cat: 'timing', tip: 'Thời điểm + 再 + động từ: "rồi hãy…" (để sau mới làm).' },
  '23|叫 (câu kiêm ngữ)': { cat: 'passive', tip: 'A 叫 B + động từ: bảo / khiến B làm gì.' },
  '24|刚 / 刚才': { cat: 'timing', tip: '刚: phó từ "vừa mới" (trước động từ). 刚才: danh từ "lúc nãy" (đứng đầu câu được).' },
  '24|又……又……': { cat: 'choice', tip: '"Vừa… vừa…": hai tính chất cùng có.' },
  '25|快要 / 要 / 快 / 就要……了': { cat: 'timing', tip: '"Sắp… rồi". Có mốc thời gian cụ thể thì dùng 就要, không dùng 快要.' },
  '25|更 + Tính': { cat: 'degree', tip: '"Càng / hơn": mức độ tăng thêm khi so sánh.' },
  '25|动 + 来 + 动 + 去': { cat: 'verbs', tip: 'Động + 来 + Động + 去: làm đi làm lại (想来想去).' },

  // ── HSK 3 (bài 26-50) ──
  '26|越来越': { cat: 'trend', tip: '"Ngày càng…": thay đổi dần theo thời gian.' },
  '26|多(么)……啊！': { cat: 'degree', tip: '"…biết bao!": câu cảm thán.' },
  '26|一定': { cat: 'guess', tip: '"Nhất định": chắc chắn / quyết tâm.' },
  '26|好不容易才 / 好容易才': { cat: 'jiucai', tip: '"Khó khăn lắm mới…" (cả hai cùng nghĩa khẳng định).' },
  '27|谁 / 什么 / 哪儿 + 都': { cat: 'scope', tip: 'Từ để hỏi + 都 / 也: "ai / gì / đâu cũng…" (phiếm chỉ).' },
  '27|不但……，而且……': { cat: 'progressive', tip: '"Không những… mà còn…": cặp tăng tiến cơ bản.' },
  '27|如果……(的话)，就……': { cat: 'condition', tip: '"Nếu… thì…": giả định phổ biến nhất.' },
  '27|Động từ + bổ ngữ xu hướng kép': { cat: 'direction', tip: 'Động + 上 / 下 / 进 / 出 / 回 / 过 / 起 + 来 / 去: hướng kép.' },
  '28|一边……一边……': { cat: 'choice', tip: '"Vừa… vừa…": hai HÀNH ĐỘNG diễn ra cùng lúc.' },
  '28|Động + 得 / 不 + Bổ': { cat: 'resultComp', tip: 'Bổ ngữ khả năng: 听得懂 / 听不懂 (có / không thể đạt kết quả).' },
  '28|挺': { cat: 'degree', tip: '"Khá" (khẩu ngữ), thường dùng 挺…的.' },
  '28|还是': { cat: 'repeat', tip: '还是: "vẫn": giữ nguyên dù hoàn cảnh thay đổi.' },
  '29|Tính 是 Tính，但是……': { cat: 'contrast', tip: '"…thì có…, nhưng…": chê khéo sau khi công nhận.' },
  '29|A 像 B 一样': { cat: 'compare', tip: '"A giống như B": so sánh ngang bằng.' },
  '29|又 + Động': { cat: 'repeat', tip: '又: lặp lại việc ĐÃ xảy ra ("lại").' },
  '30|能……吗？': { cat: 'tone', tip: '"Sao có thể… chứ?": phản vấn.' },
  '30|越A越B': { cat: 'trend', tip: '"Càng A càng B": B thay đổi theo A.' },
  '30|把 (1)': { cat: 'ba', tip: '把 + tân ngữ + động từ + nơi đến / kết quả: làm di chuyển, thay đổi.' },
  '30|除了……(以外)，……': { cat: 'progressive', tip: '除了…还 / 也: "ngoài… còn" (bổ sung). 除了…都: "trừ… ra" (loại trừ).' },
  '31|好像': { cat: 'guess', tip: '"Hình như": phán đoán không chắc chắn.' },
  '31|把 (2)': { cat: 'ba', tip: '把 + tân ngữ + động từ + bổ ngữ kết quả / xu hướng.' },
  '31|下去 / 下来 (mở rộng)': { cat: 'direction', tip: '下去: tiếp tục làm. 下来: từ quá khứ kéo đến nay / cố định lại.' },
  '32|被': { cat: 'passive', tip: '"Bị / được": chủ ngữ chịu tác động (thường không mong muốn).' },
  '32|只有……，才……': { cat: 'condition', tip: '"Chỉ có… mới…": điều kiện DUY NHẤT.' },
  '32|A 对 B 感兴趣': { cat: 'misc', tip: '"A có hứng thú với B".' },
  '33|为 / 为了': { cat: 'purpose', tip: '为了: mục đích. 为: đối tượng được hưởng ("vì ai").' },
  '33|对……来说': { cat: 'opinion', tip: '"Đối với… mà nói": đứng ở góc độ của ai.' },
  '33|AA / AABB': { cat: 'degree', tip: 'Lặp tính từ: nhấn mạnh, miêu tả sinh động (高高的, 干干净净).' },
  '34|不是……，而是……': { cat: 'choice', tip: '"Không phải… mà là…": phủ định A, khẳng định B.' },
  '34|Động + 上': { cat: 'direction', tip: '上: đạt được mục đích / bắt đầu và tiếp tục (考上, 爱上).' },
  '34|Động + 起来': { cat: 'direction', tip: '起来: bắt đầu và tiếp tục / nhận xét (看起来, 笑起来).' },
  '34|突然': { cat: 'tone', tip: '"Đột nhiên": vừa là tính từ (很突然) vừa là phó từ.' },
  '35|认为': { cat: 'opinion', tip: '"Cho rằng": nhận định có cân nhắc.' },
  '35|根据': { cat: 'prep', tip: '"Dựa vào": căn cứ (根据调查).' },
  '35|把 (3)': { cat: 'ba', tip: '把 + tân ngữ + động từ + 给 / 成 / 在…: trao, biến đổi, đặt ở đâu.' },
  '36|终于': { cat: 'timing', tip: '"Cuối cùng cũng…": sau thời gian dài chờ đợi.' },
  '36|必须': { cat: 'modal', tip: '"Phải": bắt buộc. Phủ định là 不必 / 不用.' },
  '36|千万': { cat: 'request', tip: '"Nhất định / tuyệt đối": dặn dò khẩn thiết, hay đi với 别 / 不要.' },
  '36|在……下': { cat: 'condition', tip: '"Dưới…" (sự giúp đỡ / điều kiện): 在老师的帮助下.' },
  '37|大约 / 左右': { cat: 'numbers', tip: '大约 đứng TRƯỚC số, 左右 đứng SAU số: "khoảng".' },
  '37|比如': { cat: 'opinion', tip: '"Ví dụ như": nêu ví dụ minh hoạ.' },
  '37|从来': { cat: 'scope', tip: '"Từ trước tới nay", thường đi với 不 / 没.' },
  '38|几乎': { cat: 'scope', tip: '"Hầu như, gần như": gần đạt mức tuyệt đối.' },
  '38|后来': { cat: 'sequence', tip: '"Sau đó, về sau": chỉ dùng cho việc đã qua.' },
  '38|最后': { cat: 'sequence', tip: '"Cuối cùng": vị trí sau cùng trong một chuỗi.' },
  '38|肯定': { cat: 'guess', tip: '"Chắc chắn": khẳng định không nghi ngờ.' },
  '39|估计': { cat: 'guess', tip: '"Ước đoán": đoán dựa trên tình hình.' },
  '39|不仅': { cat: 'progressive', tip: '"Không chỉ": = 不但 nhưng trang trọng hơn, đi với 而且 / 也 / 还.' },
  '39|尤其': { cat: 'progressive', tip: '"Nhất là": làm nổi bật một phần trong cái chung.' },
  '39|再说': { cat: 'progressive', tip: '"Vả lại": thêm lý do. Còn nghĩa "để sau hãy tính".' },
  '40|在……上': { cat: 'prep', tip: '"Về mặt…": phương diện, phạm vi (在学习上).' },
  '40|本来': { cat: 'tone', tip: '"Vốn dĩ / lẽ ra": tình trạng ban đầu hoặc điều đáng lẽ.' },
  '40|要是……，就……': { cat: 'condition', tip: '"Nếu…": giống 如果 nhưng khẩu ngữ hơn.' },
  '40|关于': { cat: 'prep', tip: '"Về": giới thiệu chủ đề được nói đến, đứng đầu câu được.' },
  '41|原来': { cat: 'tone', tip: '"Hoá ra": phát hiện sự thật. Còn nghĩa "vốn, ban đầu".' },
  '41|以为': { cat: 'opinion', tip: '"Tưởng rằng": nhận định đã bị sai.' },
  '41|并': { cat: 'tone', tip: '并 + 不 / 没: "hoàn toàn không": bác bỏ suy nghĩ của người khác.' },
  '41|首先……，其次……': { cat: 'sequence', tip: '"Đầu tiên…, tiếp theo…": liệt kê theo thứ tự.' },
  '41|不管……，还是 / 都……': { cat: 'concession', tip: '"Bất kể…": khẩu ngữ, đi với 都 / 也. Vế sau kết quả không đổi.' },
  '42|竟然': { cat: 'tone', tip: '"Vậy mà": ngoài dự đoán, bất ngờ.' },
  '42|尽管……，但是 / 还是……': { cat: 'concession', tip: '"Mặc dù…": sự thật ĐÃ xảy ra (khác 即使 = giả định).' },
  '42|只要……，就……': { cat: 'condition', tip: '"Chỉ cần… là…": điều kiện ĐỦ (khác 只有…才: điều kiện duy nhất).' },
  '42|来不及': { cat: 'resultComp', tip: '"Không kịp" (bổ ngữ khả năng). Ngược lại là 来得及.' },
  '43|Động + 过来': { cat: 'direction', tip: '过来: đủ sức làm hết / tỉnh lại, trở về trạng thái bình thường.' },
  '43|与': { cat: 'prep', tip: '"Và" như 和 nhưng dùng trong văn viết.' },
  '43|可是': { cat: 'contrast', tip: '"Nhưng": khẩu ngữ, nhẹ hơn 但是.' },
  '43|反正': { cat: 'concession', tip: '"Dù sao thì": kết quả không đổi trong mọi tình huống.' },
  '44|从……来看': { cat: 'opinion', tip: '"Từ… mà xét": căn cứ để đưa ra nhận định.' },
  '44|另外': { cat: 'progressive', tip: '"Ngoài ra": bổ sung ý / sự vật khác.' },
  '44|是否': { cat: 'question', tip: '"Có… hay không" (văn viết, = 是不是).' },
  '44|却': { cat: 'contrast', tip: '"Lại": chuyển ý nhẹ, đứng SAU chủ ngữ (khác 但是 đứng đầu vế).' },
  '45|无论': { cat: 'concession', tip: '"Bất kể": như 不管 nhưng trang trọng hơn.' },
  '45|除此以外': { cat: 'progressive', tip: '"Ngoài điều này ra": bổ sung thêm thông tin.' },
  '45|连……都 / 也……': { cat: 'progressive', tip: '"Ngay cả… cũng…": nhấn mạnh trường hợp cực đoan.' },
  '46|不得不': { cat: 'modal', tip: '"Không thể không": buộc phải làm dù không muốn.' },
  '46|为……而……': { cat: 'purpose', tip: '"Vì… mà…": mục đích / nguyên nhân của hành động (văn viết).' },
  '46|百分之 + Con số': { cat: 'numbers', tip: '"Phần trăm": 百分之五十 = 50%.' },
  '46|确实': { cat: 'guess', tip: '"Thật sự": xác nhận là đúng.' },
  '47|不如': { cat: 'compare', tip: 'A 不如 B: "A không bằng B". Còn nghĩa "chẳng thà".' },
  '47|什么的': { cat: 'misc', tip: '"…vân vân": đặt sau chuỗi liệt kê (khẩu ngữ).' },
  '47|按照': { cat: 'prep', tip: '"Theo": làm theo quy định, kế hoạch.' },
  '48|甚至': { cat: 'progressive', tip: '"Thậm chí": đẩy lên mức cao hơn.' },
  '48|叫 / 让 / 使 (câu kiêm ngữ)': { cat: 'passive', tip: '叫 / 让: bảo, để ai làm (khẩu ngữ). 使: khiến (văn viết, kết quả tâm lý).' },
  '48|既……又 / 也 / 还……': { cat: 'choice', tip: '"Vừa… vừa…": hai tính chất cùng tồn tại (trang trọng hơn 又…又).' },
  '49|随着': { cat: 'cause', tip: '"Cùng với…": thay đổi xảy ra theo một xu hướng.' },
  '49|拿……来说': { cat: 'opinion', tip: '"Lấy… mà nói": dẫn ra ví dụ.' },
  '49|之一': { cat: 'numbers', tip: '"Một trong số…": …之一.' },
  '49|由': { cat: 'prep', tip: '"Do": ai thực hiện / phụ trách.' },
  '49|所有': { cat: 'scope', tip: '"Tất cả", đứng trước danh từ, thường đi với 都.' },
  '50|既然……，(就)……': { cat: 'cause', tip: '"Đã… thì…": suy ra từ sự thật đã biết.' },
  '50|一天比一天': { cat: 'trend', tip: '"Mỗi ngày một…": thay đổi theo từng ngày.' },
  '50|其中': { cat: 'numbers', tip: '"Trong đó": chỉ phần trong tổng thể vừa nói.' },
  '50|仍然': { cat: 'repeat', tip: '"Vẫn": văn viết, giống 还是.' },

  // ── HSK 4 (bài 51-70) ──
  '51|Động + 起来': { cat: 'direction', tip: '起来: từ phân tán đến tập trung (收起来, 加起来).' },
  '51|而': { cat: 'contrast', tip: '而: nối 2 vế đối lập ("còn, mà") hoặc tăng tiến (văn viết).' },
  '51|由于': { cat: 'cause', tip: '"Do, vì": văn viết, đi với 所以 / 因此.' },
  '51|A，于是 B': { cat: 'sequence', tip: '"Thế là": B xảy ra tiếp theo do A.' },
  '52|否则': { cat: 'condition', tip: '"Nếu không thì": hậu quả khi không làm theo vế trước.' },
  '52|即使……也……': { cat: 'concession', tip: '"Dù cho… cũng…": GIẢ ĐỊNH (chưa xảy ra).' },
  '52|往往': { cat: 'scope', tip: '"Thường thường": quy luật rút ra từ kinh nghiệm (khác 常常: thói quen).' },
  '52|以': { cat: 'purpose', tip: '"Để": nối mục đích ở vế sau (văn viết).' },
  '53|因此': { cat: 'cause', tip: '"Vì vậy": nêu kết quả, văn viết.' },
  '53|十分': { cat: 'degree', tip: '"Vô cùng": mức độ cao, trang trọng hơn 很.' },
  '54|并且': { cat: 'progressive', tip: '"Đồng thời, hơn nữa": nối hai hành động / vế cùng chủ ngữ.' },
  '54|大概': { cat: 'guess', tip: '"Đại khái, có lẽ": phỏng đoán hoặc ước chừng.' },
  '54|然而': { cat: 'contrast', tip: '"Thế nhưng": văn viết, đứng đầu vế sau.' },
  '55|在于': { cat: 'opinion', tip: '"Nằm ở chỗ": chỉ ra nguyên nhân / bản chất.' },
  '55|记住 / 记得': { cat: 'verbs', tip: '记住: ghi nhớ lại (kết quả). 记得: còn nhớ (trạng thái).' },
  '56|通过……来……': { cat: 'purpose', tip: '"Thông qua… để…": phương thức thực hiện.' },
  '56|相反': { cat: 'contrast', tip: '"Ngược lại": nêu ý trái với vế trước.' },
  '56|偶尔': { cat: 'scope', tip: '"Thỉnh thoảng": tần suất thấp.' },
  '56|对于': { cat: 'prep', tip: '"Đối với": như 对 nhưng không dùng cho thái độ với người (✗ 对于我很好).' },
  '57|在……看来': { cat: 'opinion', tip: '"Theo… thấy": quan điểm của ai.' },
  '59|Động + 着 (zháo)': { cat: 'resultComp', tip: '着 (zháo): đạt được, chạm tới (睡着, 找着).' },
  '60|把……叫作……': { cat: 'ba', tip: '"Gọi… là…": đặt tên, mệnh danh.' },
  '61|之前': { cat: 'sequence', tip: '"Trước khi": nhấn thứ tự, thời điểm gần (khác 以前 đứng đầu câu được).' },
  '61|弄': { cat: 'verbs', tip: '"Làm": thay cho nhiều động từ cụ thể (弄坏, 弄丢), khẩu ngữ.' },
  '61|同时': { cat: 'progressive', tip: '"Đồng thời": song song, hoặc "hơn nữa".' },
  '62|总的来说': { cat: 'opinion', tip: '"Nói chung": tổng kết nhận định.' },
  '62|到底': { cat: 'tone', tip: '"Rốt cuộc": truy hỏi, hoặc "cuối cùng" sau thời gian dài.' },
  '63|难道': { cat: 'tone', tip: '"Lẽ nào": phản vấn, thường đi với 吗.' },
  '64|一 + Lượng + 一 + Lượng + 地': { cat: 'measure', tip: '"Từng… một": 一个一个地, lần lượt.' },
  '64|光': { cat: 'scope', tip: '"Chỉ" (khẩu ngữ) = 只.' },
  '68|究竟': { cat: 'tone', tip: '"Rốt cuộc": như 到底 nhưng trang trọng hơn.' },
  '68|受不了': { cat: 'resultComp', tip: '"Không chịu nổi" (bổ ngữ khả năng).' },
  '69|之': { cat: 'particle', tip: '之: "của" trong văn viết (= 的).' },
  '70|倒': { cat: 'contrast', tip: '倒: "lại": trái với dự đoán.' },
  '70|一方面…另一方面…': { cat: 'choice', tip: '"Một mặt…, mặt khác…": hai khía cạnh song song.' },
}

export function handbookKey(lesson: number, hanzi: string): string {
  return `${lesson}|${hanzi}`
}
