// Lý thuyết mở rộng cho 73 điểm ngữ pháp (18 bài "Seoul Korean 2") — key = `${lesson}|${front}`,
// `front` phải khớp CHÍNH XÁC chuỗi trong seed.ts (kể cả khi front bị lỗi encoding) để tra cứu đúng thẻ.
// Nội dung dưới đây dùng chính tả CHUẨN khi giải thích, bất kể `front`/`example` gốc có bị lỗi hay không —
// xem ghi chú cuối file về lỗi encoding trong dữ liệu gốc.
export const GRAMMAR_THEORY: Record<string, string> = {
  '1|N(이)라고 하다':
    "Dùng để giới thiệu tên gọi của người, vật, địa danh — dịch là 'được gọi là N' hoặc khi tự giới thiệu thì dịch tự nhiên là 'tôi tên là N'.\n\nGắn trực tiếp N + (이)라고 하다: nếu N có patchim thì thêm '이라고 하다', không patchim thì '라고 하다'. Đây cũng là dạng gián tiếp hoá của câu trích dẫn trực tiếp 'N이다' → 'N(이)라고 하다', nên còn dùng để thuật lại tên gọi mà người khác đã nói.\n\nLưu ý: khi tự giới thiệu tên mình, người Hàn thường dùng câu này thay vì '저는 N이에요' để nghe trang trọng, khách sáo hơn một chút, phù hợp khi giới thiệu bản thân lần đầu hoặc giới thiệu địa danh/sự vật cho người khác.",
  '1|V(으)랜고':
    "Đây là mẫu ngữ pháp -(으)려고, diễn tả mục đích hoặc ý định của hành động ở vế sau — dịch là 'để V' hoặc 'với ý định V'.\n\nCấu trúc: động từ có patchim + 으려고, không patchim + 려고. Vế sau thường là một hành động cụ thể được thực hiện nhằm đạt mục đích đó.\n\nLưu ý: -(으)려고 không dùng ở câu mệnh lệnh/rủ rê ngay sau nó, và chủ ngữ hai vế phải giống nhau. Đừng nhầm với -(으)러 (dùng sau động từ di chuyển 가다/오다) hay -기 위해서 (trang trọng hơn, có thể dùng với danh từ).",

  '2|V-는 것':
    "Gắn '것' sau động từ ở dạng hiện tại '는' để biến cả cụm động từ thành một cụm danh từ, tương đương 'việc/sự V' trong tiếng Việt, giúp động từ có thể đóng vai trò chủ ngữ hoặc tân ngữ trong câu.\n\nCấu trúc cố định 'V-는 것' (không phân biệt patchim). Có thể rút gọn '것' thành '거' trong văn nói suồng sã.\n\nThường đi kèm các động từ như 좋아하다, 싫어하다, 재미있다/재미없다, 어렵다 để nói về sở thích hoặc nhận xét một hành động. So với -기: -는 것 nhấn vào 'việc đang/thường xảy ra', còn -기 khái quát, trừu tượng hơn và dùng được với ít động từ đi kèm hơn.",
  '2|V-(으)ㄹ 줄 알다 [모르다]':
    "Diễn tả năng lực/hiểu biết cách thực hiện một hành động — 'biết cách V' (알다) hoặc 'không biết cách V' (모르다). Đây là mẫu nói về KỸ NĂNG, khác với '-을 수 있다/없다' vốn nói về khả năng nói chung (có thể do hoàn cảnh cho phép hay không).\n\nCấu trúc: động từ + (으)ㄹ 줄 알다/모르다 (patchim + 을 줄, không patchim + ㄹ 줄, patchim 'ㄹ' thì lược bỏ ㄹ rồi thêm 줄).\n\nSo sánh: '수영할 줄 알아요' (biết bơi, có kỹ năng) khác '수영할 수 있어요' (có thể bơi được, ví dụ vì hôm nay không bị cảm) — hai cấu trúc này hay bị nhầm nên cần chú ý ngữ cảnh.",
  '2|V–(으)ㄴ N (định ngữ quá khứ)':
    "Định ngữ động từ ở thì quá khứ: động từ đứng trước bổ nghĩa cho danh từ đứng sau, diễn tả một hành động ĐÃ xảy ra và hoàn tất trước thời điểm nói — dịch là 'N đã được V, N đã V'.\n\nCấu trúc: patchim + 은 N, không patchim + ㄴ N, patchim 'ㄹ' thì lược bỏ ㄹ rồi thêm ㄴ N (살다 → 산 N).\n\nPhân biệt 3 dạng định ngữ động từ theo thời: -는 N (đang diễn ra, hiện tại), -(으)ㄴ N (đã xảy ra, quá khứ), -(으)ㄹ N (sẽ xảy ra, tương lai/giả định) — ba dạng này cùng hệ thống nên nên học và ôn cùng nhau để không lẫn.",
  '2|V/A–지 않다':
    "Cách phủ định dài (formal negation), gắn trực tiếp sau gốc động từ/tính từ — 'không V/A'. Về nghĩa tương đương với phủ định ngắn '안 + V/A' nhưng trang trọng hơn, hay dùng trong văn viết, báo cáo hoặc khi vị ngữ quá dài/phức tạp khiến 안 đặt trước nghe không tự nhiên.\n\nCấu trúc không đổi theo patchim: gốc từ + 지 않다, chia thì bình thường ở '않다' (지 않아요/지 않았어요/지 않을 거예요).\n\nLưu ý: với động từ dạng 'danh từ + 하다' (vd 공부하다), phủ định ngắn phải tách '공부 안 해요', trong khi -지 않다 chỉ cần thêm thẳng vào 하다: '공부하지 않아요' — vì vậy -지 않다 thường an toàn và dễ dùng hơn phủ định ngắn.",

  '3|V 아/어 보다':
    "Diễn tả việc THỬ làm một hành động — 'thử V' (hiện tại/tương lai với -아/어 보다, -아/어 볼게요, -아/어 보세요) hoặc khi chia ở QUÁ KHỨ -아/어 봤어요 thì mang nghĩa kinh nghiệm 'đã từng V'.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아 보다, các nguyên âm còn lại + 어 보다, 하다 → 해 보다.\n\nPhân biệt với -(으)ㄴ 적이 있다 (cũng nói về kinh nghiệm): -아/어 보다 ở quá khứ nhấn vào TRẢI NGHIỆM một lần thử, còn -(으)ㄴ 적이 있다 nhấn vào việc TỪNG có sự việc đó xảy ra, dùng được cho cả tình huống không chủ động 'thử'.",
  '3|N 동안':
    "Gắn sau danh từ chỉ khoảng thời gian (số + đơn vị thời gian, hoặc danh từ trừu tượng như 방학, 여름) để diễn tả 'trong suốt khoảng thời gian N' — nhấn vào ĐỘ DÀI thời gian một hành động kéo dài liên tục.\n\nCấu trúc không đổi theo patchim: N + 동안.\n\nPhân biệt với '만에' (thời gian đã trôi qua rồi mới làm gì, không nhấn tính liên tục): '3시간 동안 공부했어요' = học liên tục suốt 3 tiếng, còn '3시간 만에 끝났어요' = (sau) 3 tiếng thì xong.",
  '3|A-(으)ㄴ데, V-는데 (1) — Bối cảnh':
    "-는데/(으)ㄴ데 dùng để nêu BỐI CẢNH, tình huống nền cho câu hỏi, đề nghị, hoặc thông tin ở vế sau — giúp câu nói mượt mà, có ngữ cảnh thay vì đưa thẳng câu hỏi cộc lốc.\n\nCấu trúc theo từ loại: tính từ có patchim + 은데, không patchim + ㄴ데; động từ + 는데 (không phân biệt patchim); danh từ + 인데; thì quá khứ dùng chung 았/었는데 cho cả V/A.\n\nVí dụ: '더운데 에어컨을 켤까요?' — vế trước 'trời đang nóng' là bối cảnh giải thích lý do cho đề nghị bật điều hoà ở vế sau. Đây là 1 trong 2 nghĩa chính của -는데 (nghĩa 'nhưng' sẽ gặp ở bài 10), cần phân biệt theo ngữ cảnh.",
  '3|N 인데 (1)':
    "Dạng danh từ của -는데 ở mục trên: '(N)인데' gắn sau danh từ để nêu bối cảnh/thông tin nền liên quan đến danh từ đó trước khi nói tiếp ở vế sau.\n\nCấu trúc: danh từ có patchim hoặc không patchim đều dùng '인데' (không phân biệt).\n\nVí dụ '제 친구인데 한국말을 진짜 잘해요' — vế trước giới thiệu 'là bạn tôi' làm bối cảnh, vế sau đưa ra nhận xét/thông tin chính liên quan đến người đó. Thường dùng khi giới thiệu người/vật lần đầu trong hội thoại trước khi kể thêm chi tiết.",
  '3|V–(으)ㄹ N (định ngữ tương lai)':
    "Định ngữ động từ diễn tả hành động SẼ xảy ra hoặc chưa xảy ra tại thời điểm nói, dùng để bổ nghĩa cho danh từ đứng sau — 'N sẽ được V, N để V'.\n\nCấu trúc: patchim + 을 N, không patchim + ㄹ N, patchim 'ㄹ' giữ nguyên + ㄹ N.\n\nCùng hệ với -는 N (hiện tại) và -(으)ㄴ N (quá khứ) đã học — ba dạng chỉ khác ở cách chia đuôi theo thời, còn ý nghĩa 'bổ nghĩa cho danh từ' giữ nguyên. Ví dụ '먹을 것' (đồ sẽ ăn/để ăn) khác '먹는 것' (việc ăn, đang ăn) và '먹은 것' (đồ đã ăn).",

  '4|A–(으)ㄴ/V-는/N인 것 같다 (hiện tại)':
    "Diễn tả sự suy đoán, phỏng đoán không chắc chắn 100% về một trạng thái/sự việc đang diễn ra ở HIỆN TẠI, dựa trên quan sát hoặc cảm nhận — dịch mềm là 'hình như, có vẻ, chắc là'.\n\nCấu trúc theo từ loại ở hiện tại: tính từ có patchim + 은 것 같다, không patchim + ㄴ 것 같다; động từ + 는 것 같다; danh từ + 인 것 같다; riêng 있다/없다 luôn dùng 는 것 같다.\n\nNgười Hàn dùng '것 같다' rất thường xuyên kể cả khi khá chắc chắn, để câu nói nghe khiêm tốn, nhẹ nhàng, tránh khẳng định thẳng — người học hay bỏ sót mẫu này khi dịch vì tiếng Việt ít có thói quen nói giảm nhẹ tương tự.",
  '4|N 보다':
    "Trợ từ so sánh, gắn sau danh từ làm mốc so sánh — '(so với) N thì...'. Thường đi kèm phó từ '더' (hơn) ở vế sau để nhấn mạnh mức độ hơn kém, nhưng '더' có thể lược bỏ mà nghĩa so sánh vẫn còn nguyên nhờ '보다'.\n\nCấu trúc không đổi theo patchim: N + 보다, vị trí khá linh hoạt tuỳ câu.\n\nVí dụ '딸기는 사과보다 싸요' = 'dâu tây rẻ hơn (so với) táo'. Lưu ý 보다 không tự mang nghĩa 'hơn' — nghĩa hơn/kém đến từ tính từ hoặc từ '더' đi kèm, bản thân 보다 chỉ đánh dấu vật được đem ra so sánh.",
  '4|A/V–았으면/었으면 좋겠다':
    "Diễn tả ước muốn, đặc biệt là ước muốn về điều trái với thực tế hiện tại (giả định) — 'ước gì, giá mà, mong là...'. Cấu trúc dùng đuôi quá khứ 았/었 nhưng mang ý nghĩa GIẢ ĐỊNH chứ không phải thời gian đã qua.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 았으면 좋겠다, các nguyên âm khác + 었으면 좋겠다, 하다 → 했으면 좋겠다.\n\nSo với '-고 싶다' (muốn làm gì, chủ động, tự mình làm được): '-았으면/었으면 좋겠다' thường dùng cho điều mình MONG MUỐN xảy ra nhưng không tự quyết định được — ví dụ '비가 안 왔으면 좋겠어요' (mong trời đừng mưa) không thể thay bằng -고 싶다.",

  '5|V/A–(으)ㄹ까요?':
    "Câu hỏi dùng để hỏi ý kiến đối phương hoặc tự hỏi bản thân trước khi quyết định — 'Hay là...nhỉ?, ...được không nhỉ?'. Khi chủ ngữ là 'chúng ta' (rủ rê) thì gần nghĩa 'Chúng ta...nhé?'; khi chủ ngữ ngôi thứ 3/sự vật thì mang nghĩa phỏng đoán 'Không biết...nhỉ?'.\n\nCấu trúc: patchim + 을까요?, không patchim + ㄹ까요?, patchim 'ㄹ' lược bỏ + ㄹ까요?.\n\nPhân biệt với -(으)ㅂ시다 (rủ rê trực tiếp, khá mạnh) — -(으)ㄹ까요? lịch sự và mềm hơn nhiều vì để ngỏ cho đối phương từ chối, nên thường được ưu tiên dùng trong giao tiếp hằng ngày.",
  '5|A/V (으)ㄹ 거예요 (suy đoán)':
    "Đây là một trong hai chức năng của '(으)ㄹ 거예요' — ngoài nghĩa 'dự định sẽ làm gì' (chủ ngữ ngôi 1/2), khi dùng với chủ ngữ ngôi thứ 3 hoặc để phỏng đoán về việc mình không chắc chắn, nó mang nghĩa suy đoán 'chắc là sẽ...'.\n\nCấu trúc: patchim + 을 거예요, không patchim + ㄹ 거예요, patchim 'ㄹ' lược bỏ + ㄹ 거예요.\n\nSo với -겠- (bài 8) và -(으)ㄴ/는 것 같다: cả ba đều là suy đoán nhưng mức độ chắc chắn khác nhau — (으)ㄹ 거예요 dựa trên suy luận logic/thông tin đã biết, thường chắc chắn hơn '것 같다' (dựa cảm giác) một chút.",
  '5|A/V–(으)니까, N(이)니까':
    "Nêu LÝ DO cho hành động, đề nghị, mệnh lệnh, lời rủ ở vế sau — 'Vì... nên...'. Khác với '-아서/어서' (cũng là lý do) ở chỗ '-(으)니까' bắt buộc phải dùng khi vế sau là câu mệnh lệnh, đề nghị, rủ rê, trong khi '-아서/어서' KHÔNG được dùng trong các câu đó.\n\nCấu trúc: động từ/tính từ có patchim + 으니까, không patchim + 니까, patchim 'ㄹ' lược bỏ + 니까; danh từ có patchim + 이니까, không patchim + 니까.\n\nVí dụ '오늘은 바쁘니까 내일 만날까요?' (đề nghị) bắt buộc dùng -니까, không thể thay bằng -아서/어서 dù nghĩa lý do tương tự.",
  '5|V–고 나서':
    "Diễn tả trình tự hai hành động: hành động vế trước hoàn tất XONG rồi mới thực hiện hành động vế sau — 'V xong rồi thì...'. Nhấn mạnh việc hoàn tất trọn vẹn trước khi chuyển sang hành động tiếp theo, mạnh hơn '-고' (chỉ nối tiếp đơn thuần, không nhấn hoàn tất).\n\nCấu trúc không đổi theo patchim: động từ + 고 나서 (chỉ dùng với động từ, không dùng với tính từ).\n\nHai vế phải cùng chủ ngữ. So với '-(으)ㄴ 후에' (sau khi V, bài 15) — hai mẫu gần nghĩa và có thể thay thế trong nhiều trường hợp, nhưng -고 나서 nhấn 'ngay sau khi hoàn tất' rõ hơn.",

  '6|N(으)로':
    "Trợ từ đa nghĩa, ở bài này dùng để chỉ PHƯƠNG TIỆN/PHƯƠNG PHÁP/CHẤT LIỆU thực hiện hành động — 'bằng N, bằng cách N'.\n\nCấu trúc: danh từ có patchim (trừ patchim ㄹ) + 으로, danh từ không patchim hoặc patchim ㄹ + 로.\n\nNgoài nghĩa phương tiện, (으)로 còn dùng chỉ hướng di chuyển ('đi về hướng N') — cần dựa vào động từ đi kèm để xác định đúng nghĩa: đi với 가다/오다 thường là hướng, đi với 만들다/찍다/쓰다 thường là phương tiện/chất liệu.",
  '6|N(이)라서':
    "Nêu LÝ DO xuất phát từ một danh từ (thân phận, tính chất, thời điểm) — 'vì là N nên...'. Là biến thể của '(이)어서/여서' dùng riêng cho danh từ, mang sắc thái khách quan, nêu sự thật hiển nhiên hơn là cảm xúc cá nhân.\n\nCấu trúc: danh từ có patchim + 이라서, không patchim + 라서.\n\nLưu ý: N(이)라서 KHÔNG dùng được ở câu mệnh lệnh/đề nghị (giống -아서/어서, khác với -(으)니까) — ví dụ không nói '주말이라서 쉽시다' mà phải dùng '주말이니까 쉽시다'.",
  "6|'ㄹ' 불규칙 (Bất quy tắc ㄹ)":
    "Bất quy tắc 'ㄹ' xảy ra ở một số động từ/tính từ có gốc kết thúc bằng '르' (다르다, 부르다, 빠르다, 모르다...) khi kết hợp với ngữ pháp bắt đầu bằng nguyên âm 아/어: âm '으' trong '르' bị lược bỏ, đồng thời thêm patchim 'ㄹ' vào âm tiết ngay trước đó.\n\nQuy tắc: nếu nguyên âm trước '르' là ㅏ hoặc ㅗ → biến thành '...ㄹ라' (자르다 → 잘라요); nếu là nguyên âm khác (ㅓ,ㅡ,ㅣ...) → biến thành '...ㄹ러' (부르다 → 불러요, 다르다 → 달라요, 모르다 → 몰라요).\n\nLưu ý: đây là bất quy tắc RIÊNG với gốc '르', khác với bất quy tắc 'ㄹ' của patchim ㄹ thông thường (vd 살다, 만들다) vốn chỉ lược bỏ ㄹ khi gặp ㄴ/ㅂ/(으).",
  '6|V-(으)면 되다':
    "Diễn tả điều kiện tối thiểu, đủ để đạt được mục đích — 'chỉ cần V là được/đủ'. Thường dùng để trả lời câu hỏi về cách làm gì đó một cách đơn giản hoá, trấn an người nghe rằng không cần làm gì phức tạp hơn.\n\nCấu trúc: động từ có patchim + 으면 되다, không patchim hoặc patchim ㄹ + 면 되다.\n\nDạng phủ định '-(으)면 안 되다' (không được làm gì, bài 14) đối lập trực tiếp với mẫu này — hai mẫu hay xuất hiện cùng nhau trong hội thoại hỏi-đáp về quy định, thủ tục.",
  '6|V-(으)ㄴ 것 같다 (quá khứ)':
    "Biến thể QUÁ KHỨ của '것 같다' đã học ở bài 4 — suy đoán về một việc đã/vừa xảy ra, dựa trên dấu hiệu quan sát được ở hiện tại chứ không phải nghe kể lại — 'hình như đã..., chắc là đã...'.\n\nCấu trúc: động từ có patchim + 은 것 같다, không patchim + ㄴ 것 같다, patchim 'ㄹ' lược bỏ + ㄴ 것 같다.\n\nSo sánh 3 dạng '것 같다' theo thời: -는 것 같다 (đang xảy ra), -(으)ㄴ 것 같다 (đã xảy ra — dùng với ĐỘNG TỪ), -았/었을 것 같다 (đã xảy ra, dùng cho TÍNH TỪ hoặc quá khứ xa hơn) — cần chọn đúng dạng theo từ loại.",

  '7|V/A-(으)ㄹ 것 같다 (tương lai)':
    "Biến thể TƯƠNG LAI của '것 같다' — phỏng đoán về điều CHƯA xảy ra, sẽ xảy ra trong tương lai hoặc nhận định chủ quan về khả năng — 'chắc là sẽ..., có lẽ sẽ...'.\n\nCấu trúc: động từ/tính từ có patchim + 을 것 같다, không patchim + ㄹ 것 같다, patchim 'ㄹ' lược bỏ + ㄹ 것 같다.\n\nĐây là mẫu suy đoán được dùng nhiều nhất trong 3 thời của '것 같다' vì tiếng Hàn ưa lối nói giảm nhẹ — kể cả khi khá chắc chắn, người Hàn vẫn hay nói '-(으)ㄹ 것 같아요' thay vì khẳng định thẳng.",
  '7|V-는지 알다 [모르다]':
    "Gắn sau động từ để tạo mệnh đề danh từ hoá mang tính NGHI VẤN gián tiếp, làm tân ngữ cho 알다/모르다 (hoặc các động từ nhận thức khác) — 'biết/không biết là (có)...không, biết là...thế nào'.\n\nCấu trúc: động từ + 는지 알다/모르다 (không phân biệt patchim); nếu câu hỏi gốc có từ nghi vấn (뭐, 언제, 어디...) thì giữ nguyên từ đó trong mệnh đề.\n\nVí dụ '유진 씨가 무슨 음식을 좋아하는지 아세요?' = biến câu hỏi trực tiếp thành mệnh đề gián tiếp để hỏi lịch sự, tế nhị hơn.",
  '7|N 인지 알다 [모르다]':
    "Dạng danh từ của '-는지' ở trên — gắn '인지' sau danh từ để tạo mệnh đề nghi vấn gián tiếp làm tân ngữ cho 알다/모르다 — 'biết/không biết là N gì, N thế nào'.\n\nCấu trúc: danh từ (có/không patchim đều dùng) + 인지 알다/모르다.\n\nVí dụ '박물관 입장료가 얼마인지 잘 모르겠어요' = không biết giá vé vào bảo tàng là bao nhiêu. Thường kết hợp với từ nghi vấn 얼마, 뭐, 언제, 누구... đứng ngay trước 인지.",
  '7|V-(으)려면':
    "Nêu ĐIỀU KIỆN gắn với Ý ĐỊNH: 'nếu muốn V (như vế trước) thì (cần làm gì đó ở vế sau)'. Là sự kết hợp giữa -(으)려고 (ý định) và -면 (điều kiện), nên vế sau thường là lời khuyên, yêu cầu, hướng dẫn để đạt được điều ở vế trước.\n\nCấu trúc: động từ có patchim + 으려면, không patchim + 려면, patchim 'ㄹ' + 려면.\n\nVí dụ '한국말을 잘하려면 매일 연습하세요' = nếu muốn giỏi tiếng Hàn thì hãy luyện tập mỗi ngày — vế sau gần như luôn là câu mệnh lệnh/đề nghị/lời khuyên.",
  '7|V-다가':
    "Diễn tả một hành động ĐANG diễn ra thì bị GIÁN ĐOẠN giữa chừng bởi một hành động/sự việc khác — 'đang V thì (bỗng)...'. Hai hành động thường loại trừ nhau hoặc đối lập, và chủ ngữ hai vế phải giống nhau.\n\nCấu trúc không đổi theo patchim: động từ + 다가 (chia ở gốc động từ, không chia thì trực tiếp trên 다가).\n\nVí dụ '일을 하다가 밖으로 나갔어요' = đang làm việc thì (dừng lại) đi ra ngoài. Phân biệt với -고 (chỉ nối tiếp, không có ý gián đoạn) và -는 동안 (diễn ra song song, không có ý dừng lại).",

  '8|V/A-걨-':
    "Vĩ tố '-겠-' chèn vào giữa gốc từ và đuôi câu, mang nghĩa PHỎNG ĐOÁN dựa trên tình huống/bằng chứng ngay trước mắt tại thời điểm nói — 'chắc là sẽ...' — khác với '(으)ㄹ 것 같다' (phỏng đoán chung, ít gắn với tình huống cụ thể tức thời).\n\nCấu trúc không đổi theo patchim: gốc từ + 겠 + đuôi câu (겠어요, 겠습니다...).\n\nNgoài nghĩa phỏng đoán, -겠- còn dùng diễn tả Ý CHÍ mạnh mẽ của người nói ngôi thứ nhất ('제가 하겠습니다' = tôi sẽ làm) — cần phân biệt hai chức năng theo ngữ cảnh và ngôi chủ ngữ.",
  '8|N 때문에':
    "Nêu NGUYÊN NHÂN/LÝ DO trực tiếp dẫn đến kết quả ở vế sau, thường mang sắc thái KHÁCH QUAN hoặc hơi tiêu cực (nguyên nhân gây ra vấn đề, trở ngại) — 'vì/tại N mà...'.\n\nCấu trúc không đổi theo patchim: danh từ + 때문에; với động từ/tính từ, phải danh từ hoá bằng '-기 때문에' (bài 13).\n\nSo với -아서/어서 và -(으)니까 (cũng chỉ lý do): 때문에 thường nhấn mạnh nguyên nhân RÕ RÀNG, cụ thể hơn, hay dùng khi đổ lỗi/giải thích trở ngại; không dùng ở vế sau là câu mệnh lệnh/đề nghị.",
  '8|V-아/어 버리다':
    "Vĩ tố bổ trợ diễn tả một hành động đã HOÀN TẤT trọn vẹn, kèm theo sắc thái cảm xúc của người nói — có thể là TIẾC NUỐI (việc không mong muốn nhưng đã lỡ xảy ra) hoặc NHẸ NHÕM (trút được gánh nặng vì đã xong việc).\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아 버리다, các nguyên âm khác + 어 버리다, 하다 → 해 버리다 (chỉ dùng với động từ).\n\nVí dụ '음식을 다 먹어 버렸어요' tuỳ ngữ cảnh có thể hiểu 'lỡ ăn hết mất rồi' (tiếc) hoặc 'ăn hết luôn cho xong' (nhẹ nhõm) — sắc thái do ngữ điệu và tình huống quyết định.",
  '8|V/A–(으)ㄹ 때':
    "Chỉ THỜI ĐIỂM mà hành động/trạng thái ở vế sau xảy ra — 'khi, lúc V/A...'. Có thể dùng với động từ (hành động đang diễn ra) hoặc tính từ (trạng thái tại thời điểm đó).\n\nCấu trúc: động từ/tính từ có patchim + 을 때, không patchim + ㄹ 때, patchim 'ㄹ' lược bỏ + ㄹ 때; với danh từ chỉ thời gian như 방학, 시험 thì dùng trực tiếp '때' không cần (으)ㄹ.\n\nLưu ý dạng quá khứ '았/었을 때' (khi ĐÃ..., bài 14) khác với '-(으)ㄹ 때' (khi đang/sắp...) về sắc thái thời gian.",

  '9|A-(으)ㄴ데요, V-는데요, N 인데요':
    "Dạng đuôi câu kết thúc bằng '-는데요/(으)ㄴ데요/인데요' — dùng để cung cấp thông tin nhưng để ngỏ, CHỜ ĐỢI phản ứng/câu trả lời tiếp theo của người nghe, giúp cuộc hội thoại tiếp diễn tự nhiên thay vì kết thúc cộc lốc.\n\nCấu trúc: giống hệ thống -는데/(으)ㄴ데 đã học (bài 3) nhưng đứng ở CUỐI CÂU thay vì giữa câu — tính từ có patchim + 은데요, không patchim + ㄴ데요; động từ + 는데요; danh từ + 인데요.\n\nVí dụ '이건 예쁜데 너무 비싼데요' — người nói vừa nhận xét vừa để ngỏ ý kiến, ngầm chờ đối phương phản hồi thay vì chốt câu bằng đuôi khẳng định.",
  '9|V-는 중이다':
    "Diễn tả một hành động đang được TIẾN HÀNH ngay tại thời điểm nói — 'đang V'. Gần nghĩa với '-고 있다' đã học ở HP1, nhưng '-는 중이다' nhấn mạnh việc đang Ở GIỮA quá trình thực hiện, thường dùng để giải thích lý do không thể làm việc khác ngay lúc đó.\n\nCấu trúc không đổi theo patchim: động từ + 는 중이다.\n\nVí dụ '지금 수업 듣는 중이니까 통화가 불가능합니다' — dùng để từ chối/giải thích khéo léo lý do bận, sắc thái trang trọng hơn '-고 있다' một chút.",
  '9|N 중이다':
    "Dạng danh từ của '-는 중이다' — gắn trực tiếp sau danh từ chỉ trạng thái/quá trình (회의, 휴가, 공사...) để nói đang trong quá trình/tình trạng đó — 'đang trong N, đang N'.\n\nCấu trúc không đổi theo patchim: danh từ + 중이다.\n\nVí dụ '마이 씨는 휴가 중이라서 회사에 안 계세요' = đang trong kỳ nghỉ phép nên không có ở công ty. Hay dùng với các danh từ công việc/thủ tục hành chính (회의 중, 통화 중, 수리 중, 예약 중...) để thông báo tình trạng ngắn gọn.",
  '9|A-(으)ㄴ가요?, V-나요?, N 인가요?':
    "Đuôi câu hỏi mang sắc thái LỊCH SỰ, NHẸ NHÀNG hơn '-아요?/어요?' thông thường — thường dùng khi hỏi người mới quen, hỏi thông tin một cách gián tiếp, tế nhị, hoặc trong văn viết trang trọng nhẹ.\n\nCấu trúc: động từ + 나요? (không phân biệt patchim); tính từ có patchim + 은가요?, không patchim + ㄴ가요?; danh từ + 인가요? (không phân biệt patchim).\n\nSo với -습니까?/ㅂ니까? (trang trọng, cứng): -나요?/(으)ㄴ가요?/인가요? mềm mại, thân thiện hơn, phù hợp giao tiếp hằng ngày khi muốn tỏ ý lịch sự mà không quá xa cách.",
  '9|N 밖에':
    "Trợ từ nhấn mạnh giới hạn, LUÔN đi kèm VỊ NGỮ PHỦ ĐỊNH ở vế sau — 'chỉ có N (mà không có gì/ai khác)'. Gần giống '만' (chỉ) nhưng 밖에 nhấn mạnh sắc thái ÍT ỎI, THIẾU HỤT hơn mức mong đợi, còn '만' trung tính hơn.\n\nCấu trúc không đổi theo patchim: danh từ + 밖에 + động từ/tính từ dạng phủ định (안, 없다, 못...).\n\nVí dụ '지갑에 만 동밖에 없어요' = trong ví CHỈ CÓ 10.000 đồng (ít quá) — nếu dùng '만 원이 있어요' thì chỉ đơn thuần thông báo số tiền, không có sắc thái than ít.",

  '10|N 중에(서)':
    "Diễn tả việc chọn/so sánh MỘT ĐỐI TƯỢNG trong SỐ NHIỀU đối tượng thuộc một tập hợp/danh mục — 'trong (số) N'. Thường đi cùng cấu trúc so sánh nhất (가장/제일) hoặc câu hỏi chọn lựa.\n\nCấu trúc không đổi theo patchim: danh từ (số nhiều/tập hợp) + 중에(서), '서' có thể lược bỏ mà nghĩa không đổi.\n\nVí dụ '저는 운동 중에서 야구를 가장 좋아해요' = trong các môn thể thao, tôi thích bóng chày nhất. Phân biệt với '중이다' (bài 9, nghĩa 'đang trong quá trình') — '중에(서)' luôn đi với danh từ SỐ NHIỀU/tập hợp, không liên quan nghĩa 'đang diễn ra'.",
  '10|반말':
    "반말 (lời nói suồng sã/thân mật) là cách nói lược bỏ đuôi lịch sự '요' và các đuôi trang trọng khác, dùng khi nói chuyện với người THÂN THIẾT, ngang vai vế (bạn bè cùng tuổi, người nhỏ tuổi hơn nhiều, người thân trong gia đình) — không hạ thấp cũng không nâng đối phương, chỉ đơn thuần là cách nói KHÔNG TRANG TRỌNG.\n\nCách chuyển: bỏ '요' ở cuối câu 해요체, đồng thời đổi đại từ xưng hô '저→나', '당신/씨→너' và một số đuôi câu đặc trưng (뭐 해? 밥 먹었어? 가자!).\n\nLưu ý: 반말 chỉ nên dùng khi ĐÃ được đối phương cho phép hoặc quan hệ đã đủ thân — dùng sai đối tượng bị coi là bất lịch sự, mất lễ phép.",
  '10|V-(으)ㄹ램요':
    "Diễn tả Ý ĐỊNH, sự CAM KẾT/SẴN SÀNG của người nói đối với hành động sắp làm, thường có tính hứa hẹn với người nghe — 'tôi sẽ V (nhé)'. Chỉ dùng cho chủ ngữ ngôi thứ nhất ở câu trần thuật; ở câu hỏi thì dùng để hỏi Ý ĐỊNH/mong muốn của người nghe.\n\nCấu trúc chuẩn là -(으)ㄹ게요: động từ có patchim + 을게요, không patchim + ㄹ게요, patchim 'ㄹ' lược bỏ + ㄹ게요.\n\nSo với -(으)ㄹ 거예요 (dự định nói chung, có thể đã lên kế hoạch từ trước): -(으)ㄹ게요 mang tính QUYẾT ĐỊNH TỨC THỜI ngay tại thời điểm nói và ngầm có ý hứa/thông báo cho người nghe biết, nên hay dùng trong hội thoại trực tiếp hơn văn viết.",
  '10|A-(으)닀, V-는닀, N 인닀 (2)':
    "Đây là nghĩa thứ hai của hệ thống -는데/(으)ㄴ데/인데 (nghĩa thứ nhất 'bối cảnh' đã học ở bài 3): dùng để nối hai vế câu có nội dung TƯƠNG PHẢN, ĐỐI LẬP nhau — 'nhưng, tuy... nhưng'.\n\nCấu trúc giữ nguyên như đã học: tính từ có patchim + 은데, không patchim + ㄴ데; động từ + 는데; danh từ + 인데; quá khứ dùng chung 았/었는데.\n\nVí dụ '이 꽃이 예쁜데 향이 안 좋아요' = hoa này đẹp NHƯNG mùi không thơm. Cần dựa vào nội dung hai vế (bổ sung thông tin hay đối lập nhau) để phân biệt đây là nghĩa 'bối cảnh' hay 'nhưng' — đây là điểm hay gây nhầm lẫn nhất của -는데.",

  "11|'ㅅ' bất quy tắc":
    "Bất quy tắc 'ㅅ' xảy ra ở một số động từ/tính từ có patchim 'ㅅ' (짓다, 낫다, 붓다, 젓다...) khi kết hợp với ngữ pháp bắt đầu bằng nguyên âm (아/어, (으)): patchim 'ㅅ' bị LƯỢC BỎ hoàn toàn, sau đó kết hợp bình thường như từ không có patchim.\n\nVí dụ: 낫다 + 아/어서 → 나아서; 짓다 + (으)니까 → 지으니까; 붓다 + 아/어서 → 부어서.\n\nLưu ý QUAN TRỌNG: một số từ có patchim ㅅ nhưng KHÔNG thuộc bất quy tắc (chia đều đặn, giữ nguyên ㅅ) như 웃다 (cười), 씻다 (rửa), 벗다 (cởi), 빗다 (chải) — cần học thuộc riêng nhóm ngoại lệ này để tránh chia sai.",
  '11|N 마다':
    "Gắn sau danh từ chỉ thời gian hoặc đơn vị đếm để diễn tả sự LẶP LẠI đều đặn theo chu kỳ đó — 'mỗi, cứ mỗi...'; cũng dùng được với danh từ chỉ đối tượng cá thể để nói 'mọi N, N nào cũng vậy'.\n\nCấu trúc không đổi theo patchim: danh từ/số từ + 마다.\n\nVí dụ '사람마다 성격이 달라요' = mỗi người mỗi tính; '40분마다 버스가 와요' = cứ mỗi 40 phút xe buýt lại đến. Phân biệt với '매' (mỗi, VD 매일, 매주 — ghép cố định trước danh từ) — 마다 linh hoạt hơn, gắn được sau hầu hết danh từ chỉ đơn vị/chu kỳ.",
  '11|V-는 게 어녕요?':
    "Đưa ra LỜI ĐỀ NGHỊ hoặc hỏi ý kiến đối phương một cách nhẹ nhàng, gián tiếp — 'Hay là (làm gì đó) nhỉ?, ...thì thế nào?'. Cấu trúc gồm '-는 것' (danh từ hoá động từ, bài 2, rút gọn thành '게' trong văn nói) + '어때요?' (thế nào?).\n\nCấu trúc chuẩn: động từ + 는 게 어때요? (không phân biệt patchim).\n\nSo với -(으)ㄹ까요? (cũng là đề nghị/rủ rê): -는 게 어때요? thiên về ĐƯA RA GIẢI PHÁP/gợi ý cụ thể cho một vấn đề đã nêu trước đó, còn -(으)ㄹ까요? thiên về hỏi ý kiến chung chung hơn.",
  '11|V-기로 하다':
    "Diễn tả một QUYẾT ĐỊNH, LỜI HỨA, hoặc KẾ HOẠCH đã được chốt (một mình hoặc thoả thuận với người khác) — 'quyết định V, đã hẹn sẽ V'. Vế trước là hành động được quyết định, động từ '하다' chia thì để chỉ thời điểm quyết định đó.\n\nCấu trúc không đổi theo patchim: động từ + 기로 하다 (chỉ dùng với động từ).\n\nVí dụ '주말에 친구를 만나기로 했어요' = đã hẹn/quyết định gặp bạn vào cuối tuần. Thường chia ở quá khứ '-기로 했어요' để nói về quyết định đã đưa ra trước đó, dù hành động có thể còn chưa xảy ra.",

  '12|A-아/어 보이다':
    "Diễn tả NHẬN XÉT/CẢM NHẬN của người nói dựa trên VẺ NGOÀI, hình thức bên ngoài của người/vật/sự việc — 'trông có vẻ...'. Chỉ dùng với TÍNH TỪ (không dùng với động từ) và chỉ là cảm nhận chủ quan qua quan sát.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아 보이다, các nguyên âm khác + 어 보이다, 하다 → 해 보이다.\n\nVí dụ '그 가방 비싸 보이는데요' = cái túi đó trông có vẻ đắt (chưa chắc thực sự đắt). Phân biệt với '것 같다' (suy đoán nói chung, dựa nhiều căn cứ) — '아/어 보이다' CHỈ dựa trên vẻ ngoài nhìn thấy được.",
  '12|N 철럼[같이]':
    "Diễn tả sự SO SÁNH TƯƠNG ĐỒNG, giống hệt hoặc gần giống với danh từ đứng trước — 'giống như N'. Dạng chuẩn là '처럼' và '같이', có thể dùng thay thế nhau trong hầu hết trường hợp mang nghĩa này.\n\nCấu trúc không đổi theo patchim: danh từ + 처럼 hoặc danh từ + 같이.\n\nVí dụ '민수 씨는 가수처럼 노래를 잘해요' = anh Minsu hát hay như ca sĩ vậy. Lưu ý '같이' còn có nghĩa khác là 'cùng nhau' (저랑 같이 가요 = đi cùng tôi) — cần dựa vào ngữ cảnh để phân biệt hai nghĩa của '같이'.",
  '12|A-(으)ㄴ 편이다, V-는 편이다':
    "Diễn tả một nhận xét mang tính TƯƠNG ĐỐI, không tuyệt đối — 'thuộc dạng, thuộc loại, khá là...'. Dùng khi muốn nói giảm nhẹ mức độ khẳng định, thay vì nói thẳng 'A/V' thì nói 'thuộc diện A/V' để câu nói mềm mỏng, khiêm tốn hơn.\n\nCấu trúc: động từ + 는 편이다 (không phân biệt patchim); tính từ có patchim + 은 편이다, không patchim + ㄴ 편이다, patchim 'ㄹ' lược bỏ + ㄴ 편이다.\n\nVí dụ '저는 매운 음식을 잘 먹는 편이에요' = tôi thuộc dạng ăn cay khá tốt (nhận xét tương đối, không khẳng định tuyệt đối là ăn cay giỏi nhất).",
  '12|A-게':
    "Biến tính từ thành TRẠNG TỪ để bổ nghĩa cho động từ đứng sau, diễn tả MỨC ĐỘ hoặc CÁCH THỨC của hành động — 'một cách A, A A'.\n\nCấu trúc không đổi theo patchim: tính từ + 게 (chỉ dùng với tính từ).\n\nVí dụ '예쁘게 입었어요' = ăn mặc một cách đẹp đẽ; '재미있게 놀았어요' = chơi một cách vui vẻ. Nhiều tính từ khi biến thành trạng từ theo '-게' đã trở thành cụm quen thuộc, hay gặp trong văn nói hằng ngày (맛있게 드세요, 편하게 앉으세요...).",

  '13|V/A-(으)ㄹ지 모르겠다':
    "Diễn tả sự KHÔNG CHẮC CHẮN, băn khoăn của người nói về một khả năng có xảy ra hay không — 'không biết là...có...hay không, có lẽ...'. Gần giống -(으)ㄹ까요? khi tự hỏi bản thân, nhưng '-(으)ㄹ지 모르겠다' nhấn mạnh sự PHÂN VÂN, LO LẮNG rõ hơn.\n\nCấu trúc: động từ/tính từ có patchim + 을지 모르겠다, không patchim + ㄹ지 모르겠다, patchim 'ㄹ' lược bỏ + 지 모르겠다.\n\nVí dụ '선물을 샀는데 좋아할지 모르겠어요' = đã mua quà rồi nhưng không biết (bạn ấy) có thích hay không — thể hiện sự băn khoăn, hồi hộp chờ kết quả.",
  '13|V/A-기는 하지만':
    "Thừa nhận nội dung ở vế trước là ĐÚNG nhưng vẫn đưa ra ý kiến/thông tin trái ngược hoặc bổ sung ở vế sau — 'A/V thì có A/V (thật) nhưng...'. Dùng để tránh phủ nhận hoàn toàn ý trước đó mà vẫn khéo léo bổ sung góc nhìn khác.\n\nCấu trúc không đổi theo patchim: động từ/tính từ + 기는 하지만 (có thể rút gọn '기는' thành '긴' trong văn nói).\n\nVí dụ '음식이 맛있기는 하지만 가격이 비싸요' = món ăn ngon thì có ngon thật, nhưng giá đắt. Rất tự nhiên khi muốn KHEN CHÊ cùng lúc mà không gây mất lòng.",
  '13|V/A-기 때문에, N(이)기 때문에':
    "Dạng ĐỘNG TỪ/TÍNH TỪ của '때문에' đã học ở bài 8 (vốn chỉ dùng trực tiếp sau danh từ) — gắn '-기' để danh từ hoá động từ/tính từ trước khi thêm '때문에', nêu NGUYÊN NHÂN rõ ràng, khách quan cho kết quả ở vế sau.\n\nCấu trúc: động từ/tính từ + 기 때문에 (không phân biệt patchim); danh từ có patchim + 이기 때문에, không patchim + 기 때문에 (khác với 'N 때문에' trực tiếp ở bài 8).\n\nVí dụ '집에서 학교까지 멀기 때문에 일찍 나와야 해요' = vì (khoảng cách) từ nhà đến trường xa nên phải ra sớm. Không dùng được ở vế sau là câu mệnh lệnh/đề nghị, giống các mẫu chỉ lý do khác.",
  '13|V-기(가) A':
    "Danh từ hoá động từ bằng '-기' rồi dùng làm chủ ngữ cho một tính từ ĐÁNH GIÁ/NHẬN XÉT về mức độ dễ-khó-thích hợp của hành động đó — thường đi cùng các tính từ như 쉽다, 어렵다, 좋다, 나쁘다, 편하다, 불편하다.\n\nCấu trúc không đổi theo patchim: động từ + 기(가) + tính từ đánh giá ('가' có thể lược bỏ trong văn nói).\n\nVí dụ '이 음식은 매워서 먹기가 좋아요' = món này cay nên ăn rất hợp/đã. '-기' ở đây đóng vai trò chủ ngữ của câu, khác với '-는 것' (bài 2) thường làm tân ngữ — cần phân biệt vai trò ngữ pháp của hai cách danh từ hoá này.",

  '14|V-(으)ㄴ 적(이) 있다[없다]':
    "Diễn tả việc CÓ hay KHÔNG CÓ kinh nghiệm đã từng làm một việc gì đó trong quá khứ — 'đã từng/chưa từng V'. Nhấn vào TRẢI NGHIỆM đáng nhớ, đặc biệt (thường là lần đầu hoặc việc hiếm gặp), khác với thì quá khứ thông thường chỉ đơn thuần thuật lại sự việc đã xảy ra.\n\nCấu trúc: động từ có patchim + 은 적이 있다[없다], không patchim + ㄴ 적이 있다[없다], patchim 'ㄹ' lược bỏ + ㄴ 적이 있다[없다].\n\nVí dụ '한국에 가 본 적이 있어요' = đã từng đi Hàn Quốc (một trải nghiệm đáng nhớ), khác với '한국에 갔어요' (chỉ đơn thuần: đã đi Hàn Quốc, có thể là việc thường xuyên).",
  '14|V/A-았을/었을 땄':
    "Biến thể QUÁ KHỨ của '-(으)ㄹ 때' (bài 8) — chỉ thời điểm mà một trạng thái/hành động ĐÃ hoàn toàn xảy ra/kết thúc trong quá khứ, không còn tiếp diễn ở hiện tại — 'khi đã..., lúc đã...'.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 았을 때, các nguyên âm khác + 었을 때, 하다 → 했을 때.\n\nSo sánh '학교에 다닐 때' (khi còn đi học, diễn ra trong một khoảng thời gian) với '학교에 다녔을 때' (khi đã (từng) đi học, nhấn mạnh việc đó đã hoàn toàn thuộc về quá khứ) — sắc thái thời gian khác nhau rõ rệt.",
  '14|V-아도/어도 돼다':
    "Dùng để HỎI XIN PHÉP hoặc CHO PHÉP thực hiện một hành động — 'V có được không?, được phép V'. Cấu trúc gồm '-아도/어도' (dù, cho dù) + 되다 (được), nghĩa đen là 'dù có V thì cũng được (không sao)'.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아도 되다, các nguyên âm khác + 어도 되다, 하다 → 해도 되다.\n\nVí dụ '내일 내도 돼요?' = mai nộp có được không?; có thể thay '되다' bằng '괜찮다' với nghĩa tương đương. Đối lập trực tiếp với '-(으)면 안 되다' (không được phép) học ngay sau đây.",
  '14|V-(으)면 안 돼다':
    "Diễn tả sự KHÔNG CHO PHÉP, CẤM thực hiện một hành động — 'không được phép V, nếu V thì không được'. Là dạng phủ định của '-아도/어도 되다', dùng để nêu quy định, luật lệ, hoặc lời nhắc nhở nghiêm khắc.\n\nCấu trúc: động từ có patchim + 으면 안 되다, không patchim hoặc patchim ㄹ + 면 안 되다.\n\nVí dụ '교실에서 음식을 먹으면 안 됩니다' = trong lớp học không được ăn uống. Hay xuất hiện ở biển báo, nội quy, hướng dẫn nơi công cộng — mang sắc thái khá trang trọng, nghiêm túc hơn cách nói cấm đoán thông thường.",

  '15|A-아지다/어지다':
    "Gắn sau TÍNH TỪ để diễn tả sự BIẾN ĐỔI dần dần của một trạng thái theo thời gian — 'trở nên, dần dần...'. Sau khi gắn '아지다/어지다', tính từ vốn tĩnh sẽ mang tính chất ĐỘNG (một quá trình thay đổi), nên có thể chia như động từ (아져요, 아지고 있어요...).\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아지다, các nguyên âm khác + 어지다, 하다 → 해지다.\n\nVí dụ '날씨가 더워졌어요' = trời đã trở nên nóng (có một quá trình thay đổi), khác với '더워요' (chỉ đơn thuần: trời nóng, trạng thái tĩnh).",
  '15|V-게 돼다':
    "Diễn tả sự THAY ĐỔI sang một trạng thái/tình huống mới, thường do TÁC ĐỘNG KHÁCH QUAN từ bên ngoài hoặc hoàn cảnh đưa đẩy, KHÔNG PHẢI do ý muốn chủ động của người nói — 'trở nên, thành ra, (bị/được) đưa đến chỗ...'.\n\nCấu trúc không đổi theo patchim: động từ + 게 되다.\n\nVí dụ '한국 노래를 좋아해서 한국어를 배우게 되었어요' = (do) thích nhạc Hàn nên rồi thành ra học tiếng Hàn (một cách tự nhiên, không hẳn chủ đích ban đầu). Phân biệt với '-게 하다' (làm cho ai đó/cái gì đó trở nên..., mang tính chủ động) — dễ nhầm vì hình thức gần giống nhau.",
  '15|V-기 전에':
    "Diễn tả một hành động xảy ra TRƯỚC KHI hành động khác diễn ra — 'trước khi V'. Động từ trong '-기 전에' KHÔNG chia thì (dù cả câu ở thì nào, '-기 전에' vẫn giữ nguyên dạng này).\n\nCấu trúc không đổi theo patchim: động từ + 기 전에 (có thể dùng cả với danh từ: N 전에).\n\nVí dụ '밥을 먹기 전에 손을 씻으세요' = trước khi ăn cơm hãy rửa tay. Đối lập trực tiếp với '-(으)ㄴ 후에' (sau khi V) học ngay sau đây — hai mẫu hay được luyện tập cùng nhau để nắm trình tự trước/sau.",
  '15|V-(으)ㄴ 후에':
    "Diễn tả một hành động xảy ra SAU KHI hành động khác đã hoàn tất — 'sau khi V'. Khác với '-기 전에' (không chia patchim), '-(으)ㄴ 후에' chia theo patchim vì bản chất là dạng định ngữ quá khứ + danh từ '후' (sau).\n\nCấu trúc: động từ có patchim + 은 후에, không patchim + ㄴ 후에, patchim 'ㄹ' lược bỏ + ㄴ 후에 (cũng dùng được N 후에 với danh từ chỉ thời gian).\n\nGần nghĩa với '-고 나서' (bài 5) nhưng '-(으)ㄴ 후에' dùng được cả khi chủ ngữ hai vế KHÁC NHAU (linh hoạt hơn '-고 나서' vốn yêu cầu cùng chủ ngữ).",

  '16|V-아/어 놓다':
    "Diễn tả một hành động đã HOÀN TẤT và TRẠNG THÁI KẾT QUẢ của nó vẫn được DUY TRÌ, chuẩn bị sẵn cho việc sử dụng sau này — 'V sẵn, V để đấy'. Nhấn mạnh tính CHỦ ĐỘNG chuẩn bị trước của người thực hiện.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아 놓다, các nguyên âm khác + 어 놓다, 하다 → 해 놓다.\n\nGần nghĩa với '-아/어 두다' (có thể thay thế trong đa số trường hợp) và khác với '-아/어 있다' (bài 17, chỉ trạng thái kết quả tồn tại nhưng không nhấn mạnh yếu tố CHỦ ĐỘNG chuẩn bị).",
  '16|N 대신':
    "Diễn tả sự THAY THẾ — hành động/sự vật ở vế sau THAY CHO danh từ đứng trước '대신' — 'thay vì N, thay cho N'.\n\nCấu trúc không đổi theo patchim: danh từ + 대신 (có thể thêm '에' thành '대신에' mà nghĩa không đổi); cũng dùng được sau mệnh đề định ngữ: 'V-는 대신(에)'.\n\nVí dụ '밥 대신 우유만 한 잔 마셨어요' = thay vì (ăn) cơm, chỉ uống một ly sữa. Với dạng mệnh đề 'V-는 대신에' còn mang thêm sắc thái 'bù lại, đổi lại' (làm việc A nhưng bù lại làm việc B để cân bằng).",
  '16|V-(으)ㄹ까 하다':
    "Diễn tả một Ý ĐỊNH còn MƠ HỒ, CHƯA CHẮC CHẮN, người nói đang cân nhắc chứ chưa quyết định dứt khoát — 'đang định, đang phân vân có nên...'. CHỈ dùng được với chủ ngữ ngôi thứ NHẤT.\n\nCấu trúc: động từ có patchim + 을까 하다, không patchim + ㄹ까 하다, patchim 'ㄹ' lược bỏ + ㄹ까 하다.\n\nSo với '-(으)ㄹ 거예요' (dự định đã khá chắc chắn): '-(으)ㄹ까 하다' thể hiện mức độ chắc chắn THẤP hơn nhiều, có thể thay đổi ý định bất cứ lúc nào, hay dùng khi ướm hỏi ý kiến người khác trước khi quyết định hẳn.",
  '16|V/A-(으)ㄹ 타니까':
    "Kết hợp giữa Ý CHÍ/PHỎNG ĐOÁN mạnh mẽ của người nói (vế trước) và một ĐỀ NGHỊ/YÊU CẦU dành cho người nghe (vế sau) — 'Tôi sẽ (chắc chắn) V1, vậy nên hãy V2 nhé' (khi chủ ngữ vế trước là 'tôi') hoặc 'Vì chắc chắn sẽ A/V nên...' (khi phỏng đoán về việc khách quan). Dạng chuẩn là -(으)ㄹ 테니까.\n\nCấu trúc: động từ/tính từ có patchim + 을 테니까, không patchim + ㄹ 테니까, patchim 'ㄹ' lược bỏ + ㄹ 테니까.\n\nVí dụ '제가 곧 도착할 테니까 조금만 기다리세요' = tôi sẽ đến ngay bây giờ, vậy nên (bạn) đợi một chút nhé.",

  '17|V-아다/어다 주다':
    "Diễn tả HAI hành động diễn ra nối tiếp Ở HAI ĐỊA ĐIỂM khác nhau (khác với '-아/어 주다' thông thường chỉ giúp đỡ tại MỘT chỗ) — hành động đầu thực hiện ở nơi A, rồi mang/đưa kết quả đến nơi B cho ai đó — 'V (ở đâu đó) xong rồi mang đến/cho...'.\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아다 주다, các nguyên âm khác + 어다 주다, 하다 → 해다 주다.\n\nRiêng khi kết hợp với 모시다 (đưa/dẫn người lớn tuổi), 데리다 (dẫn/đưa người, con vật) thì '-아다/어다 주다' mang nghĩa ĐI CÙNG, DẪN ĐẾN TẬN NƠI — ví dụ '아이를 학교에 데려다 주고 왔어요' = đã đưa (dẫn) con đến tận trường.",
  '17|V-(으)ㄹ 뻔하다':
    "Diễn tả một việc CÓ NGUY CƠ RẤT CAO xảy ra nhưng THỰC TẾ ĐÃ KHÔNG xảy ra (may mắn tránh được) — 'suýt nữa thì...'. Luôn chia ở dạng QUÁ KHỨ '-(으)ㄹ 뻔했어요'.\n\nCấu trúc: động từ có patchim + 을 뻔하다, không patchim + ㄹ 뻔하다, patchim 'ㄹ' lược bỏ + ㄹ 뻔하다.\n\nVí dụ '늦게 일어나서 약속에 늦을 뻔했어요' = dậy muộn nên suýt nữa trễ hẹn (nhưng cuối cùng không trễ). Thường đi kèm những tình huống có phần nguy hiểm/đáng tiếc nếu xảy ra thật (사고가 날 뻔했다, 넘어질 뻔했다...).",
  "17|'ㅎ' bất quy tắc":
    "Bất quy tắc 'ㅎ' xảy ra ở hầu hết tính từ có patchim 'ㅎ' (그렇다, 어떻다, 노랗다, 하얗다, 까맣다, 이렇다...; ngoại trừ 좋다 chia đều đặn) khi kết hợp với ngữ pháp bắt đầu bằng '(으)' hoặc nguyên âm.\n\nQuy tắc: khi gặp '(으)' → cả 'ㅎ' và '으' đều bị lược bỏ (그렇다 + (으)니까 → 그러니까); khi gặp nguyên âm 아/어 → 'ㅎ' bị lược bỏ VÀ nguyên âm biến thành 'ㅐ' (하얗다 + 아/어요 → 하얘요, 그렇다 + 아/어요 → 그래요).\n\nĐây là bất quy tắc thường gặp nhất với NHÓM TÍNH TỪ CHỈ MÀU SẮC và các đại từ chỉ định (이렇다/그렇다/저렇다/어떻다) — gặp rất nhiều trong giao tiếp hằng ngày, cần luyện chia thật kỹ.",
  '17|V-아/어 있다':
    "Diễn tả một hành động đã xảy ra và TRẠNG THÁI KẾT QUẢ của nó vẫn còn TỒN TẠI, kéo dài đến hiện tại — 'đang ở trạng thái đã V' (kết quả). CHỈ dùng được với các động từ có kết quả để lại trạng thái quan sát được (앉다, 서다, 눕다, 걸리다, 켜지다, 입원하다...).\n\nCấu trúc theo nguyên âm cuối gốc từ: ㅏ/ㅗ + 아 있다, các nguyên âm khác + 어 있다, 하다 → 해 있다 (rất ít động từ 하다 dùng được dạng này).\n\nPhân biệt với '-고 있다' (đang trong QUÁ TRÌNH thực hiện hành động): '문이 열려 있어요' (cửa đang mở, kết quả) khác '문을 열고 있어요' (đang thực hiện hành động mở cửa).",

  '18|V-(으)ㄴ 지':
    "Dùng để hỏi/nói về KHOẢNG THỜI GIAN đã trôi qua TÍNH TỪ THỜI ĐIỂM một hành động xảy ra CHO ĐẾN NAY — 'kể từ khi V thì đã được (bao lâu)'. Luôn đi kèm động từ '되다' hoặc '지나다' ở vế sau.\n\nCấu trúc: động từ có patchim + 은 지, không patchim + ㄴ 지, patchim 'ㄹ' lược bỏ + ㄴ 지 (kết hợp với danh từ chỉ thời lượng + 되다/지나다).\n\nVí dụ '대학교를 졸업한 지 일 년이 되었어요' = đã một năm kể từ khi tốt nghiệp đại học. Khác hoàn toàn với '-는지' (bài 7, mang nghĩa nghi vấn gián tiếp) dù viết gần giống.",
  '18|N(이)나 (2)':
    "Đây là nghĩa thứ hai của trợ từ '(이)나' (nghĩa thứ nhất 'hoặc' đã học ở HP1): khi đứng sau SỐ LƯỢNG, '(이)나' diễn tả số lượng NHIỀU HƠN, VƯỢT XA so với suy nghĩ/mong đợi của người nói — 'những, tận, đến tận...'.\n\nCấu trúc: danh từ/số từ có patchim + 이나, không patchim + 나.\n\nVí dụ '우리 가족은 아홉 명이나 있어요' = gia đình tôi có TẬN chín người (nhiều hơn mức bình thường). Cần dựa vào ngữ cảnh (đi với số lượng + sắc thái ngạc nhiên) để phân biệt với nghĩa 'hoặc'.",
  '18|A-다, V-ㄴ다/는다':
    "Đuôi câu TRẦN THUẬT dùng trong VĂN VIẾT khách quan (báo chí, luận văn, nghiên cứu, nhật ký) thay cho đuôi '-아요/어요' hay dùng trong văn nói — gọi là văn thể viết (문어체).\n\nCấu trúc thì hiện tại: tính từ (mọi patchim) + 다 (giữ nguyên dạng từ điển); động từ có patchim + 는다, không patchim + ㄴ다, patchim 'ㄹ' lược bỏ + ㄴ다. Thì quá khứ/tương lai chia bình thường rồi thêm '다' (았다/었다, (으)ㄹ 것이다).\n\nVí dụ nhật ký '나는 매일 아침 8시에 출근한다' = tôi đi làm lúc 8 giờ sáng mỗi ngày — không dùng đuôi này khi nói chuyện trực tiếp vì nghe cộc lốc, thiếu lịch sự trong khẩu ngữ.",
  '18|N(이)다':
    "Dạng DANH TỪ của lối văn viết trần thuật '-다' ở trên — dùng '(이)다' thay cho '이에요/예요' trong văn viết khách quan (báo chí, nhật ký, luận văn...).\n\nCấu trúc: danh từ có patchim + 이다, không patchim + 다; thì quá khứ '이었다/였다', tương lai/suy đoán '일 것이다'.\n\nVí dụ '여기는 내가 일하는 회사다' = đây là công ty tôi làm việc; '어제는 아버지 생신이었다' = hôm qua là sinh nhật bố. Cùng hệ thống văn thể viết với 'A-다, V-ㄴ다/는다' ở trên — nên học và ghi nhớ chung với nhau vì luôn xuất hiện cùng nhau trong một đoạn văn viết.",
}

// Ghi chú: một số `front`/`example` trong seed.ts bị lỗi encoding (vd "돼다" thay vì "되다",
// "땄" thay vì "때", "철럼" thay vì "처럼"...) — có vẻ do lỗi copy/OCR khi nhập liệu gốc từ Notion.
// Lý thuyết ở trên luôn dùng chính tả CHUẨN khi giải thích để không dạy sai ngữ pháp cho người học.
