import { nanoid } from 'nanoid'
import type { KoreanCard, KoreanCardKind } from './types'

// Toàn bộ nội dung 18 bài "Seoul Korean 2" (Notion) — 73 điểm ngữ pháp + 573 từ vựng.
type SeedEntry = [kind: KoreanCardKind, lesson: number, front: string, meaning: string, note: string, example: string]

const ENTRIES: SeedEntry[] = [
  ["grammar", 1, "N(이)라고 하다", "Đuôi gián tiếp danh từ, để gọi tên ngưới, sự vật, sự việc – 'được gọi là N'.", "N: (이)라고 하다 · N받침O: 이라고 하다 · N받침X: 라고 하다", "저는 트엡이라고 합니다.\n여기는 환끼솠 호수라고 하고 하닸이의 명삤입니다."],
  ["grammar", 1, "V(으)랜고", "dùng để diễn tả ý định thực hiện hành động gì – 'để V'.", "V: (으)랜고 · V받침O: 랜고 · V받침X: (으)랜고 · V받침\"ㄹ\": 랜고", "한국 희구들과 이야기하도월 공부이요.\n내염 아을 먹도월 주스를 샨엄요.\n오끭 저랐에 비곡군를 들랙도월 소고긴를 샨엄요."],
  ["vocab", 1, "성", "họ", "last name", ""],
  ["vocab", 1, "생년월일", "ngày sinh", "date of birth", ""],
  ["vocab", 1, "매년", "mỗi năm", "every year", ""],
  ["vocab", 1, "외국인", "người nước ngoài", "foreigner", ""],
  ["vocab", 1, "외국인등록증", "thẻ đăng ký người nước ngoài", "alien registration card", ""],
  ["vocab", 1, "연락처", "thông tin liên lạc", "contact information", ""],
  ["vocab", 1, "성별", "giới tính", "sex; gender", ""],
  ["vocab", 1, "신분증", "giấy tờ tùy thân", "identification card", ""],
  ["vocab", 1, "주소", "địa chỉ", "address", ""],
  ["vocab", 1, "종교", "tôn giáo", "religion", ""],
  ["vocab", 1, "매달", "mỗi tháng", "every month", ""],
  ["vocab", 1, "국적", "quốc tịch", "nationality", ""],
  ["vocab", 1, "이메일", "email", "e-mail", ""],
  ["vocab", 1, "매주", "mỗi tuần", "every week", ""],
  ["vocab", 1, "성명", "họ và tên", "full name", ""],
  ["vocab", 1, "매일", "mỗi ngày", "everyday", ""],
  ["vocab", 1, "친구를 사귀다", "kết bạn", "to make a friend", ""],
  ["vocab", 1, "(이름을) 부르다", "gọi (tên)", "to call (a name)", ""],
  ["vocab", 1, "형제들", "anh chị em", "siblings", ""],
  ["vocab", 1, "전화", "điện thoại", "telephone", ""],
  ["grammar", 2, "V-는 것", "Gắn vào sau động từ để biến động từ thành cụm danh từ (việc làm cái gì đó)", "V: 는 것 · V받침O: 는 것 · V받침X: 는 것", "저는 책 읽는 것을 좋아해요.\n한국어 배우는 것 재미있지만 어려워요."],
  ["grammar", 2, "V-(으)ㄹ 줄 알다 [모르다]", "Biết làm gì / không biết làm gì", "V: (으)ㄹ 줄 알다 [모르다] · V받침O: 을 줄 알다 [모르다] · V받침X: ㄹ 줄 알다 [모르다] · V받침ㄹ: ㄹ 줄 알다 [모르다]", "민수 씨는 수영할 줄 몰라요.\n한국 음식을 만들 줄 알아요."],
  ["grammar", 2, "V–(으)ㄴ N (định ngữ quá khứ)", "Động từ bổ nghĩa cho danh từ, diễn tả hành động đã xảy ra trong quá khứ", "V: (으)ㄴ N · V받침O: 은 N · V받침X: ㄴ N · V받침ㄹ: ㄹ(X) → ㄴ N", "저는 베트남에서 온 히엔입니다.\n어제 만든 음식 이름은 퍼입니다."],
  ["grammar", 2, "V/A–지 않다", "Phủ định động từ hoặc tính từ — 'không V/A'", "V/A: 지 않다 · V/A받침O: 지 않다 · V/A받침X: 지 않다", "내 방은 크지 않지만 싸고 좋아요.\n어제 아파서 학교에 가지 않았어요."],
  ["vocab", 2, "블로그", "blog", "blog", ""],
  ["vocab", 2, "(노래를) 부르다", "hát (bài hát)", "to sing (a song)", ""],
  ["vocab", 2, "그림을 그리다", "vẽ tranh", "to draw a picture", ""],
  ["vocab", 2, "등산", "leo núi", "mountain climbing; hiking", ""],
  ["vocab", 2, "라틴 댄스", "nhảy Latin", "Latin dance", ""],
  ["vocab", 2, "대회에 나가다", "tham gia cuộc thi", "to enter a contest", ""],
  ["vocab", 2, "영화 감상", "xem phim (sở thích)", "watching a movie", ""],
  ["vocab", 2, "운동", "tập thể dục", "exercise", ""],
  ["vocab", 2, "연습실", "phòng tập", "practice room", ""],
  ["vocab", 2, "컴퓨터 게임", "chơi game máy tính", "computer game", ""],
  ["vocab", 2, "태권도복", "đồng phục Taekwondo", "Taekwondo uniform", ""],
  ["vocab", 2, "문화 센터", "trung tâm văn hóa", "cultural/community center", ""],
  ["vocab", 2, "요리", "nấu ăn", "cooking", ""],
  ["vocab", 2, "등산화", "giày leo núi", "hiking boots", ""],
  ["vocab", 2, "인터넷을 하다", "lên mạng", "to browse the Internet", ""],
  ["vocab", 2, "회비", "hội phí", "(membership) fee", ""],
  ["vocab", 2, "사진을 찍다", "chụp ảnh", "to take a photo", ""],
  ["vocab", 2, "음악 감상", "nghe nhạc (sở thích)", "listening to music", ""],
  ["vocab", 2, "가입하다", "gia nhập, tham gia", "to join", ""],
  ["vocab", 2, "모이다", "tập hợp, tụ họp", "to gather", ""],
  ["vocab", 2, "악기", "nhạc cụ", "musical instrument", ""],
  ["vocab", 2, "소설", "tiểu thuyết", "novel", ""],
  ["vocab", 2, "동호회", "hội/câu lạc bộ", "club", ""],
  ["vocab", 2, "독서", "đọc sách", "reading", ""],
  ["vocab", 2, "요가", "yoga", "yoga", ""],
  ["vocab", 2, "(사진을) 올리다", "đăng (ảnh)", "to post (a photo)", ""],
  ["vocab", 2, "음악을 듣다", "nghe nhạc", "to listen to music", ""],
  ["vocab", 2, "낚시", "câu cá", "fishing", ""],
  ["vocab", 2, "인형을 모으다", "sưu tầm búp bê", "to collect dolls", ""],
  ["vocab", 2, "관심", "sự quan tâm, sở thích", "interest", ""],
  ["grammar", 3, "V 아/어 보다", "Hiện tại: thử làm gì đó — 'thử V'; Quá khứ: đã từng làm — 'đã từng V'", "V: 아/어 보다 · V(ㅏ/ㅗ): 아 보다 · V(ㅓ,ㅡ,ㅣ...): 어 보다 · V하다: 해 보다", "한국에 가 보고 싶어요.\n작년에 저는 처음 한국에 가 봤어요."],
  ["grammar", 3, "N 동안", "Diễn tả khoảng thời gian — 'trong lúc / trong suốt N'", "N: 동안 · N받침O/X: 동안", "어제 4시간 동안 공부했습니다.\n두 시간 동안 쉬지 않고 공부했어요."],
  ["grammar", 3, "A-(으)ㄴ데, V-는데 (1) — Bối cảnh", "Mệnh đề trước là tiền đề/bối cảnh để đưa ra câu hỏi hoặc yêu cầu ở sau", "A받침O hiện tại: 은데 · A받침X hiện tại: ㄴ데, quá khứ: 았/었는데, 있다/없다: 는데 · V: 는데", "더운데 에어컨을 켤까요?\n저는 이 책이 없는데 좀 빌려 주세요."],
  ["grammar", 3, "N 인데 (1)", "Mệnh đề trước là bối cảnh/lý do cho mệnh đề sau", "N: 인데 · N받침O/X: 인데", "제 친구인데 한국말을 진짜 잘해요.\n여기는 하노이인데 베트남의 수도입니다."],
  ["grammar", 3, "V–(으)ㄹ N (định ngữ tương lai)", "Động từ bổ nghĩa cho danh từ, diễn tả sự việc sẽ xảy ra trong tương lai", "V: (으)ㄹ N · V받침O: 을 N · V받침X: ㄹ N · V받침ㄹ: ㄹ N", "내일은 만날 시간이 없어요?\n이 도시락은 점심에 먹을 것입니다."],
  ["vocab", 3, "공연", "buổi diễn", "performance", ""],
  ["vocab", 3, "국립극장", "Nhà hát Quốc gia Hàn Quốc", "The National Theater of Korea", ""],
  ["vocab", 3, "전시회", "cuộc triển lãm", "exhibition", ""],
  ["vocab", 3, "체험", "trải nghiệm thực tế", "(firsthand) experience", ""],
  ["vocab", 3, "음악회", "buổi hòa nhạc", "(classical) music performance", ""],
  ["vocab", 3, "뮤지컬", "nhạc kịch", "musical", ""],
  ["vocab", 3, "영화제", "liên hoan phim", "movie festival", ""],
  ["vocab", 3, "예술의전당", "Nhà hát Nghệ thuật Seoul", "Seoul Art Center", ""],
  ["vocab", 3, "재즈", "nhạc jazz", "jazz", ""],
  ["vocab", 3, "번지 점프", "nhảy bungee", "bungee jumping", ""],
  ["vocab", 3, "공연장", "nhà hát, hội trường", "performance hall", ""],
  ["vocab", 3, "박물관", "bảo tàng", "museum", ""],
  ["vocab", 3, "기억에 남다", "đọng lại trong trí nhớ", "to remain in one's memory", ""],
  ["vocab", 3, "액션 영화", "phim hành động", "action movie", ""],
  ["vocab", 3, "축제", "lễ hội", "festival", ""],
  ["vocab", 3, "연극", "kịch (sân khấu)", "theater play", ""],
  ["vocab", 3, "전시", "vật trưng bày", "exhibit", ""],
  ["vocab", 3, "미술관", "bảo tàng nghệ thuật", "art museum", ""],
  ["vocab", 3, "놀이공원", "công viên giải trí", "amusement park", ""],
  ["vocab", 3, "김치박물관", "Bảo tàng Kimchi", "Kimchi Museum", ""],
  ["vocab", 3, "사물놀이", "samullori (hòa tấu gõ truyền thống)", "samullori (traditional percussion quartet)", ""],
  ["vocab", 3, "콘서트", "buổi hòa nhạc/concert", "concert", ""],
  ["vocab", 3, "배우", "diễn viên", "actor", ""],
  ["vocab", 3, "경험", "kinh nghiệm, trải nghiệm", "experience", ""],
  ["vocab", 3, "상영", "chiếu (phim)", "screening", ""],
  ["vocab", 3, "상을 받다", "nhận giải thưởng", "to win an award", ""],
  ["vocab", 3, "다도", "trà đạo", "tea ceremony", ""],
  ["vocab", 3, "코미디 영화", "phim hài", "comedy movie", ""],
  ["vocab", 3, "애니메이션", "phim hoạt hình", "animation", ""],
  ["vocab", 3, "국립국악원", "Trung tâm Quốc nhạc Quốc gia", "National Gugak Center", ""],
  ["vocab", 3, "갔다 오다", "đã đi (đâu đó) và về", "to have gone (somewhere)", ""],
  ["vocab", 3, "참가하다", "tham gia", "to participate; take part", ""],
  ["vocab", 3, "초대를 받다", "được mời", "to receive an invitation", ""],
  ["vocab", 3, "전통문화", "văn hóa truyền thống", "traditional culture", ""],
  ["vocab", 3, "국립극장", "Nhà hát Quốc gia Hàn Quốc", "The National Theater of Korea", ""],
  ["vocab", 3, "불꽃놀이", "bắn pháo hoa", "fireworks", ""],
  ["vocab", 3, "말하기 대회", "cuộc thi nói", "speech contest", ""],
  ["vocab", 3, "국악", "nhạc truyền thống Hàn Quốc", "Korean classical music", ""],
  ["vocab", 3, "스쿠버 다이빙", "lặn biển", "scuba diving", ""],
  ["vocab", 3, "감독", "đạo diễn", "director", ""],
  ["vocab", 3, "참가비", "phí tham gia", "entry fee", ""],
  ["vocab", 3, "공연", "buổi diễn", "performance", ""],
  ["vocab", 3, "경험", "kinh nghiệm, trải nghiệm", "experience", ""],
  ["vocab", 3, "국악", "nhạc truyền thống Hàn Quốc", "Korean classical music", ""],
  ["vocab", 3, "국립국악원", "Trung tâm Quốc nhạc Quốc gia", "National Gugak Center", ""],
  ["vocab", 3, "갔다 오다", "đã đi (đâu đó) và về", "to have gone (somewhere)", ""],
  ["vocab", 3, "공연장", "nhà hát, hội trường", "performance hall", ""],
  ["vocab", 3, "감독", "đạo diễn", "director", ""],
  ["grammar", 4, "A–(으)ㄴ/V-는/N인 것 같다 (hiện tại)", "Suy đoán về điều gì đó ở hiện tại — 'hình như, có lẽ'", "V: 는 것 같다 · A받침O: 은 것 같다 · A받침X: ㄴ 것 같다 · N: 인 것 같다 · 있다/없다: 는 것 같다", "내일 너무 추운 것 같아요.\n지금 밖에 비가 내리는 것 같아요."],
  ["grammar", 4, "N 보다", "So sánh hơn — 'so với N thì...'", "N: 보다 · N받침O/X: 보다", "딸기는 사과보다 싸요.\n저는 여름보다 겨울을 더 좋아해요."],
  ["grammar", 4, "A/V–았으면/었으면 좋겠다", "Diễn đạt sự ước muốn đối lập với thực tại — 'ước gì, giá như...'", "V/A: 았/었으면 좋겠다 · V/A(ㅗ/ㅏ): 았으면 좋겠다 · V/A(ㅓ,ㅡ,ㅣ...): 었으면 좋겠다 · V/A하다: 했으면 좋겠다", "돈이 많았으면 좋겠습니다.\n삶이 행복했으면 좋겠어요."],
  ["vocab", 4, "끼다", "đeo (găng tay, kính)", "to wear (gloves, glasses)", ""],
  ["vocab", 4, "교환하다", "đổi (hàng)", "to exchange", ""],
  ["vocab", 4, "굽이 높다", "gót giày cao", "(shoe) heels are high", ""],
  ["vocab", 4, "청바지", "quần jean", "(blue) jeans", ""],
  ["vocab", 4, "옷값", "giá quần áo", "price of clothes", ""],
  ["vocab", 4, "블라우스", "áo blouse", "blouse", ""],
  ["vocab", 4, "어둡다", "tối (màu)", "to be dark", ""],
  ["vocab", 4, "좀 작다", "hơi nhỏ", "to be a little small", ""],
  ["vocab", 4, "양말", "vớ, tất", "socks", ""],
  ["vocab", 4, "끼다", "đeo (găng tay, kính)", "to wear (gloves, glasses)", ""],
  ["vocab", 4, "빨간색", "màu đỏ", "red", ""],
  ["vocab", 4, "환불하다", "hoàn tiền", "to refund", ""],
  ["vocab", 4, "마음에 안 들다", "không vừa ý", "to not like", ""],
  ["vocab", 4, "신다", "đi/mang (giày, vớ)", "to wear (footwear)", ""],
  ["vocab", 4, "마음에 들다", "vừa ý, thích", "to like", ""],
  ["vocab", 4, "비싸다", "đắt", "to be expensive", ""],
  ["vocab", 4, "넥타이", "cà vạt", "tie", ""],
  ["vocab", 4, "디자인", "thiết kế, kiểu dáng", "design", ""],
  ["vocab", 4, "싸다", "rẻ", "to be cheap", ""],
  ["vocab", 4, "하다", "đeo (cà vạt, vòng cổ)", "to wear (tie, necklace)", ""],
  ["vocab", 4, "잘 어울리다", "hợp, vừa", "to match well", ""],
  ["vocab", 4, "스카프", "khăn quàng cổ", "scarf", ""],
  ["vocab", 4, "티셔츠", "áo phông", "T-shirt", ""],
  ["vocab", 4, "유행하다", "hợp thời trang", "to be in fashion", ""],
  ["vocab", 4, "가격", "giá cả", "price", ""],
  ["vocab", 4, "좀 크다", "hơi lớn/rộng", "to be a little big", ""],
  ["vocab", 4, "길다", "dài", "to be long", ""],
  ["vocab", 4, "교환하다", "đổi (hàng)", "to exchange", ""],
  ["vocab", 4, "스웨터", "áo len", "sweater", ""],
  ["vocab", 4, "장갑", "găng tay", "gloves", ""],
  ["vocab", 4, "쓰다", "đội (mũ), đeo (kính)", "to wear (hat, glasses)", ""],
  ["vocab", 4, "잘 맞다", "vừa (size)", "to fit well", ""],
  ["vocab", 4, "사이즈", "kích cỡ", "size", ""],
  ["vocab", 4, "양복", "bộ vest", "suit", ""],
  ["vocab", 4, "잘 안 어울리다", "không hợp", "to not match well", ""],
  ["vocab", 4, "입다", "mặc (quần áo)", "to wear (clothes)", ""],
  ["vocab", 4, "색깔", "màu sắc", "color", ""],
  ["vocab", 4, "밝다", "sáng (màu)", "to be bright", ""],
  ["vocab", 4, "굽이 높다", "gót giày cao", "(shoe) heels are high", ""],
  ["vocab", 4, "넥타이", "cà vạt", "tie", ""],
  ["vocab", 4, "디자인", "thiết kế, kiểu dáng", "design", ""],
  ["vocab", 4, "마음에 들다", "vừa ý, thích", "to like", ""],
  ["vocab", 4, "길다", "dài", "to be long", ""],
  ["vocab", 4, "가격", "giá cả", "price", ""],
  ["grammar", 5, "V/A–(으)ㄹ까요?", "Hỏi ý kiến hoặc tự hỏi bản thân — 'Hay là... nhỉ?'", "V/A: (으)ㄹ까요? · V/A받침O: 을까요? · V/A받침X: ㄹ까요? · V/A받침ㄹ: ㄹ까요?", "오늘 저녁에 뭘 먹을까요?\n이번 주말에 집에서 쉴까요?"],
  ["grammar", 5, "A/V (으)ㄹ 거예요 (suy đoán)", "Dự đoán hoặc truyền đạt suy nghĩ một cách khéo léo — 'Chắc là sẽ...'", "V/A: (으)ㄹ 거예요 · V/A받침O: 을 거예요 · V/A받침X: ㄹ 거예요 · V/A받침ㄹ: ㄹ 거예요", "이 신발이 민수 씨에게 작을 거예요.\n내일부터 날씨가 더울 거예요."],
  ["grammar", 5, "A/V–(으)니까, N(이)니까", "Mệnh đề trước là lý do cho mệnh đề sau — 'Vì... nên...'", "V/A: (으)니까 · V/A받침O: 으니까 · V/A받침X: 니까 · V/A받침ㄹ: ㄹ(X) → 니까 · N받침O: 이니까 · N받침X: 니까", "오늘은 바쁘니까 내일 만날까요?\n오늘은 토요일이니까 문을 일찍 닫을 거예요."],
  ["grammar", 5, "V–고 나서", "Hành động này xong rồi mới có hành động khác — 'V xong rồi thì...'", "V: 고 나서 · V받침O/X: 고 나서", "이 책을 다 읽고 나서 친구에게 빌려 줄 거예요.\n밥을 먹고 나서 숙제를 해야 돼요."],
  ["vocab", 5, "온천", "suối nước nóng", "hot spring", ""],
  ["vocab", 5, "출발", "khởi hành", "departure", ""],
  ["vocab", 5, "한옥마을", "làng Hanok", "Hanok Village", ""],
  ["vocab", 5, "여행", "du lịch", "traveling", ""],
  ["vocab", 5, "여행 상품", "sản phẩm du lịch", "tour product", ""],
  ["vocab", 5, "비즈니스석", "hạng thương gia", "business class", ""],
  ["vocab", 5, "며칠", "mấy ngày", "how many days", ""],
  ["vocab", 5, "벚꽃", "hoa anh đào", "cherry blossoms", ""],
  ["vocab", 5, "기념하다", "kỷ niệm", "to commemorate", ""],
  ["vocab", 5, "숙소", "nơi lưu trú", "accommodation", ""],
  ["vocab", 5, "건축물", "công trình kiến trúc", "architecture", ""],
  ["vocab", 5, "수산 시장", "chợ hải sản", "fisheries wholesale market", ""],
  ["vocab", 5, "경희궁", "cung Gyeonghui", "a palace in Seoul", ""],
  ["vocab", 5, "도착", "sự đến nơi", "arrival", ""],
  ["vocab", 5, "광장", "quảng trường", "square", ""],
  ["vocab", 5, "일등석", "hạng nhất", "first class", ""],
  ["vocab", 5, "한라산", "núi Halla", "a mountain in Jeju", ""],
  ["vocab", 5, "배낭여행", "du lịch phượt", "backpacking", ""],
  ["vocab", 5, "명승지", "danh lam thắng cảnh", "scenic spot", ""],
  ["vocab", 5, "요금", "phí, lệ phí", "charge; fee", ""],
  ["vocab", 5, "원룸", "phòng trọ studio", "studio apartment", ""],
  ["vocab", 5, "빈방", "phòng trống", "vacancy", ""],
  ["vocab", 5, "유명하다", "nổi tiếng", "to be famous", ""],
  ["vocab", 5, "출장", "đi công tác", "business trip", ""],
  ["vocab", 5, "박", "đêm (lưu trú)", "number of nights for a stay", ""],
  ["vocab", 5, "노량진", "Noryangjin", "a place in Seoul", ""],
  ["vocab", 5, "식비", "tiền ăn", "food expenses", ""],
  ["vocab", 5, "자리/좌석", "chỗ ngồi", "seat", ""],
  ["vocab", 5, "물어보다", "hỏi thử", "to ask", ""],
  ["vocab", 5, "사막", "sa mạc", "desert", ""],
  ["vocab", 5, "경복궁", "cung Gyeongbok", "a palace in Seoul", ""],
  ["vocab", 5, "동네", "khu phố, xóm", "town; neighborhood", ""],
  ["vocab", 5, "일반석", "hạng thường", "economy class", ""],
  ["vocab", 5, "펜션", "nhà nghỉ kiểu villa", "rental cottage", ""],
  ["vocab", 5, "분위기", "không khí, bầu không khí", "atmosphere", ""],
  ["vocab", 5, "출국 날짜", "ngày xuất cảnh", "departure date", ""],
  ["vocab", 5, "조선 시대", "triều đại Joseon", "Joseon Dynasty", ""],
  ["vocab", 5, "귀국 날짜", "ngày về nước", "return date", ""],
  ["vocab", 5, "덕수궁", "cung Deoksu", "a palace in Seoul", ""],
  ["vocab", 5, "항공권", "vé máy bay", "flight ticket", ""],
  ["vocab", 5, "민박", "nhà nghỉ tư nhân", "private rental room", ""],
  ["vocab", 5, "당일", "trong ngày", "that day", ""],
  ["vocab", 5, "동상", "tượng", "statue", ""],
  ["vocab", 5, "왕복", "khứ hồi", "round trip", ""],
  ["vocab", 5, "바라다", "mong, ước", "to wish", ""],
  ["vocab", 5, "추천하다", "giới thiệu, khuyên dùng", "to recommend", ""],
  ["vocab", 5, "여행자 보험료", "phí bảo hiểm du lịch", "traveler's insurance premium", ""],
  ["vocab", 5, "입장료", "phí vào cổng", "entrance fee", ""],
  ["vocab", 5, "한옥", "nhà truyền thống Hàn Quốc", "traditional Korean style house", ""],
  ["vocab", 5, "거제도", "đảo Geoje", "an island in Korea", ""],
  ["vocab", 5, "편도", "một chiều", "one way", ""],
  ["vocab", 5, "항공료", "giá vé máy bay", "airfare", ""],
  ["vocab", 5, "패키지여행", "du lịch trọn gói", "tour package", ""],
  ["vocab", 5, "콘도", "căn hộ (condo)", "condo", ""],
  ["vocab", 5, "일정", "lịch trình", "schedule", ""],
  ["vocab", 5, "게스트하우스", "nhà khách", "guest house", ""],
  ["vocab", 5, "자연", "thiên nhiên", "nature", ""],
  ["vocab", 5, "아프리카", "châu Phi", "Africa", ""],
  ["vocab", 5, "여행지", "điểm đến du lịch", "travel destination", ""],
  ["vocab", 5, "유럽", "châu Âu", "Europe", ""],
  ["vocab", 5, "가이드", "hướng dẫn viên", "guide", ""],
  ["vocab", 5, "숙박비", "phí lưu trú", "room charge", ""],
  ["vocab", 5, "포함되어 있다", "được bao gồm", "to be included", ""],
  ["grammar", 6, "N(으)로", "Diễn tả phương pháp, vật liệu, phương tiện — 'bằng, bằng cách N'", "N: (으)로 · N받침O: 으로 · N받침ㄹ/X: 로", "매일 버스로 회사에 가요.\n저는 스마트폰으로 사진을 찍는 것을 좋아해요."],
  ["grammar", 6, "N(이)라서", "Vế trước là lý do của vế sau — 'vì là... nên'", "N: (이)라서 · N받침O: 이라서 · N받침X: 라서", "내일 주말이라서 이 식당이 문을 열지 않아요."],
  ["grammar", 6, "'ㄹ' 불규칙 (Bất quy tắc ㄹ)", "Khi kết hợp với ngữ pháp bắt đầu bằng nguyên âm 아/어", "Nguyên âm trước ㄹ là ㅏ/ㅗ → ㄹ라 (vd: 자르다 → 잘라요) · Nguyên âm trước ㄹ là ㅓ,ㅡ... → ㄹ러 (vd: 부르다 → 불러서)", "한국어를 모라서 불편해요.\n우리 누나하고 저는 성격이 아주 달라요."],
  ["grammar", 6, "V-(으)면 되다", "Chỉ cần làm việc gì đó là đủ — 'Chỉ cần... là được'", "V: (으)면 되다 · V받침O: 으면 되다 · V받침X/ㄹ: 면 되다", "지금 빨리 출발하면 돼요."],
  ["grammar", 6, "V-(으)ㄴ 것 같다 (quá khứ)", "Suy đoán về điều gì đó đã xảy ra trong quá khứ — 'hình như đã, có lẽ đã...'", "V: (으)ㄴ 것 같다 · V받침O: 은 것 같다 · V받침X: ㄴ 것 같다 · V받침ㄹ: ㄹ(X) → ㄴ 것 같다", "수업이 끝난 것 같아요."],
  ["vocab", 6, "환율", "tỷ giá hối đoái", "exchange rate", ""],
  ["vocab", 6, "택배", "chuyển hàng tận nhà", "door-to-door delivery", ""],
  ["vocab", 6, "편지를 부치다", "gửi thư", "to send a letter", ""],
  ["vocab", 6, "돈을 보내다", "gửi/chuyển tiền", "to send money", ""],
  ["vocab", 6, "돈을 모으다", "tiết kiệm tiền", "to save money", ""],
  ["vocab", 6, "품명", "tên hàng hóa", "(names of) goods", ""],
  ["vocab", 6, "환전", "đổi ngoại tệ", "currency exchange", ""],
  ["vocab", 6, "봉투에 넣다", "cho vào phong bì", "to put in an envelope", ""],
  ["vocab", 6, "소포를 포장하다", "gói bưu phẩm", "to wrap a package", ""],
  ["vocab", 6, "현금 카드", "thẻ ghi nợ", "debit card", ""],
  ["vocab", 6, "신용 카드", "thẻ tín dụng", "credit card", ""],
  ["vocab", 6, "저울", "cân", "scale", ""],
  ["vocab", 6, "상자", "hộp, thùng", "box", ""],
  ["vocab", 6, "맡기다", "gửi, ký gửi", "to leave (something with someone)", ""],
  ["vocab", 6, "출금", "rút tiền", "withdrawal", ""],
  ["vocab", 6, "현금 인출기", "máy rút tiền", "ATM; cash machine", ""],
  ["vocab", 6, "엽서를 부치다", "gửi bưu thiếp", "to send a postcard", ""],
  ["vocab", 6, "주소를 쓰다", "viết địa chỉ", "to write an address", ""],
  ["vocab", 6, "접수하다", "nhận hồ sơ, tiếp nhận", "to accept", ""],
  ["vocab", 6, "신청하다", "đăng ký, yêu cầu", "to request", ""],
  ["vocab", 6, "수량", "số lượng", "quantity", ""],
  ["vocab", 6, "입금", "nộp tiền vào", "deposit", ""],
  ["vocab", 6, "돈을 넣다", "gửi tiền vào", "to deposit money", ""],
  ["vocab", 6, "우편", "thư tín, bưu chính", "mail", ""],
  ["vocab", 6, "돈을 바꾸다", "đổi tiền", "to exchange money", ""],
  ["vocab", 6, "유로", "đồng euro", "euro", ""],
  ["vocab", 6, "택배 기사", "người giao hàng", "delivery man", ""],
  ["vocab", 6, "돈을 찾다", "rút tiền", "to withdraw money", ""],
  ["vocab", 6, "송금", "chuyển tiền qua ngân hàng", "wire transfer", ""],
  ["vocab", 6, "위안", "đồng nhân dân tệ", "yuan", ""],
  ["vocab", 6, "도장", "con dấu", "stamp/seal", ""],
  ["vocab", 6, "엔", "đồng yên", "yen", ""],
  ["grammar", 7, "V/A-(으)ㄹ 것 같다 (tương lai)", "Phỏng đoán về tương lai — 'chắc là sẽ...'", "V/A: (으)ㄹ 것 같다 · V/A받침O: 을 것 같다 · V/A받침X: ㄹ 것 같다", "이 옷은 좀 클 것 같아요.\n회의가 많아서 다음 주부터 엄청 바쁜 것 같네요."],
  ["grammar", 7, "V-는지 알다 [모르다]", "Hỏi hoặc thể hiện sự không chắc chắn — 'Không biết là... / Có biết là...?'", "V: 는지 알다 · V받침O/X: 는지 알다 [모르다]", "유진 씨가 무슨 음식을 좋아하는지 아세요?"],
  ["grammar", 7, "N 인지 알다 [모르다]", "Không biết là N / Có biết là N?", "N: 인지 알다 · N받침O/X: 인지 알다 [모르다]", "박물관 입장료가 얼마인지 잘 모르겠어요."],
  ["grammar", 7, "V-(으)려면", "Nếu muốn V... thì / Để V thì...", "V: (으)려면 · V받침O: 으려면 · V받침X: 려면", "한국말을 잘하려면 매일 연습하세요."],
  ["grammar", 7, "V-다가", "Đang làm gì thì đột nhiên dừng và làm việc khác — 'đang V...thì...'", "V: 다가 · V받침O/X: 다가", "일을 하다가 밖으로 나갔어요.\n공부하다가 너무 저려서 잠긄 쌌어요."],
  ["vocab", 7, "한참", "một lúc lâu, khá lâu", "for a long time", ""],
  ["vocab", 7, "횡단보도", "vạch qua đường", "crosswalk", ""],
  ["vocab", 7, "근처", "gần đó, lân cận", "vicinity", ""],
  ["vocab", 7, "사거리", "ngã tư", "4-way intersection", ""],
  ["vocab", 7, "직진하다", "đi thẳng", "to go straight", ""],
  ["vocab", 7, "육교", "cầu vượt", "overpass", ""],
  ["vocab", 7, "길이 막히다", "tắc đường, kẹt xe", "to have heavy traffic", ""],
  ["vocab", 7, "지하도", "đường hầm", "underpass", ""],
  ["vocab", 7, "내려가다", "đi xuống", "to go down", ""],
  ["vocab", 7, "간판", "biển hiệu cửa hàng", "store sign", ""],
  ["vocab", 7, "차비", "tiền xe, vé xe", "(bus/train/taxi) fare", ""],
  ["vocab", 7, "표지판", "bảng chỉ dẫn", "sign; notice", ""],
  ["vocab", 7, "택시 정류장", "trạm taxi", "taxi stop", ""],
  ["vocab", 7, "신호등", "đèn giao thông", "traffic light", ""],
  ["vocab", 7, "거리", "khoảng cách", "distance", ""],
  ["vocab", 7, "나가다", "đi ra", "to go out", ""],
  ["vocab", 7, "왼쪽으로 돌아가다", "rẽ sang trái", "to turn left", ""],
  ["vocab", 7, "좌회전하다", "rẽ trái", "to turn left", ""],
  ["vocab", 7, "내리다", "xuống (xe)", "to get off; to go down", ""],
  ["vocab", 7, "버스 정류장", "trạm xe buýt", "bus stop", ""],
  ["vocab", 7, "우회전하다", "rẽ phải", "to turn right", ""],
  ["vocab", 7, "지하철역", "trạm tàu điện ngầm", "subway station", ""],
  ["vocab", 7, "세우다", "dừng (xe)", "to stop", ""],
  ["vocab", 7, "걸어오다", "đi bộ đến", "to come on foot", ""],
  ["vocab", 7, "오른쪽으로 돌아가다", "rẽ sang phải", "to turn right", ""],
  ["vocab", 7, "건너다", "đi qua, qua đường", "to cross", ""],
  ["vocab", 7, "교통편", "phương tiện giao thông", "transportation", ""],
  ["grammar", 8, "V/A-걨-", "Suy đoán dựa trên tình huống tại thời điểm nói — 'Chắc sẽ V/A...'", "V/A: 걨 · V/A받침O/X: 걨", "월급을 받아서 기분이 좋겠어요.\n오후에 비가 오겠어요."],
  ["grammar", 8, "N 때문에", "N đó chính là nguyên nhân/lý do — 'Tại/Vì N nên...'", "N: 때문에 · N받침O/X: 때문에", "날씨 때문에 비행기가 출발하지 못했어요."],
  ["grammar", 8, "V-아/어 버리다", "Kết quả gây cảm giác tiếc nuối hoặc đã xong và trút gánh nặng — 'V... mất rồi'", "V: 아/어 버리다 · V(ㅏ,ㅗ): 아 버리다 · V(ㅓ,ㅡ,ㅣ...): 어 버리다 · V하다: 해 버리다", "빙이 너무 고파서 엄마가 남겼 준 음식을 다 먹어 버렸어요."],
  ["grammar", 8, "V/A–(으)ㄹ 때", "Chỉ ra thời gian mà hành động diễn ra — 'Khi, lúc V/A...'", "V/A: (으)ㄹ 때 · V/A받침O: 을 때 · V/A받침X/ㄹ: ㄹ 때", "스트레스를 받을 때 쇼핑하거나 산책하는 것이 좋아요."],
  ["vocab", 8, "생각(이) 나다", "nhớ ra, nghĩ đến", "to come into one's mind", ""],
  ["vocab", 8, "넘어지다", "ngã, té", "to fall", ""],
  ["vocab", 8, "외롭다", "cô đơn", "to be lonely", ""],
  ["vocab", 8, "긴장되다", "căng thẳng, hồi hộp", "to be nervous", ""],
  ["vocab", 8, "기분이 좋다", "cảm thấy vui", "to feel good", ""],
  ["vocab", 8, "표현하다", "biểu đạt, thể hiện", "to express", ""],
  ["vocab", 8, "운이 없다", "không may, vận xấu", "to have no luck", ""],
  ["vocab", 8, "속상하다", "buồn lòng", "to feel awful", ""],
  ["vocab", 8, "잘못", "sai, nhầm", "wrongly", ""],
  ["vocab", 8, "교통사고가 나다", "bị tai nạn giao thông", "to have a traffic accident", ""],
  ["vocab", 8, "잃어버리다", "làm mất, đánh mất", "to lose", ""],
  ["vocab", 8, "걱정되다", "lo lắng", "to be worried", ""],
  ["vocab", 8, "창피하다", "xấu hổ", "to be embarrassed", ""],
  ["vocab", 8, "무엇보다", "hơn hết", "most of all", ""],
  ["vocab", 8, "슬프다", "buồn", "to be sad", ""],
  ["vocab", 8, "짜증이 나다", "bực mình", "to be annoyed", ""],
  ["vocab", 8, "힘들다", "mệt, khó khăn", "to be hard", ""],
  ["vocab", 8, "졸다", "ngủ gật", "to doze", ""],
  ["vocab", 8, "기쁘다", "vui mừng", "to be happy", ""],
  ["vocab", 8, "고장이 나다", "bị hỏng", "to break down", ""],
  ["vocab", 8, "놓치다", "bỏ lỡ, trễ", "to miss", ""],
  ["vocab", 8, "화가 나다", "tức giận", "to be angry", ""],
  ["vocab", 8, "당황하다", "bối rối, lúng túng", "to be confused/taken aback", ""],
  ["vocab", 8, "기분이 나쁘다", "cảm thấy buồn bực", "to be upset; unhappy", ""],
  ["vocab", 8, "스트레스를 받다", "bị căng thẳng", "to get stress", ""],
  ["vocab", 8, "사고가 나다", "bị tai nạn", "to have an accident", ""],
  ["vocab", 8, "스트레스를 풀다", "giải tỏa căng thẳng", "to release stress", ""],
  ["vocab", 8, "잠이 들다", "ngủ quên", "to fall asleep", ""],
  ["vocab", 8, "노트북", "máy tính xách tay", "laptop computer", ""],
  ["grammar", 9, "A-(으)ㄴ데요, V-는데요, N 인데요", "Chờ đợi phản ứng của đối phương, muốn tiếp tục cuộc hội thoại", "A받침O hiện tại: 은데요 · A받침X hiện tại: ㄴ데요, quá khứ: 았/었는데요 · V: 는데요 · N: 인데요, quá khứ: 이었/였는데요", "이건 예쁜데 너무 비싼데요."],
  ["grammar", 9, "V-는 중이다", "Việc gì đó đang được tiến hành — 'đang V...'", "V: 는 중이다 · V받침O/X: 는 중이다", "지금 수업 듣는 중이니까 통화가 불가능합니다."],
  ["grammar", 9, "N 중이다", "Đang..., đang trong quá trình...", "N: 중이다 · N받침O/X: 중이다", "마이 씨는 휴가 중이라서 회사에 안 계세요."],
  ["grammar", 9, "A-(으)ㄴ가요?, V-나요?, N 인가요?", "Hỏi ai đó một cách lịch sự và nhẹ nhàng", "V: 나요? · A받침O: 은가요? · A받침X: ㄴ가요? · N받침O: 인가요? · N받침X: 인가요?", "이 음식은 어느 나라 음식인가요?"],
  ["grammar", 9, "N 밖에", "Chỉ có N, không có lựa chọn nào khác (dùng với phủ định) — 'chỉ N'", "N: 밖에 + phủ định · N받침O/X: 밖에", "지갑에 만 동밖에 없어요.\n우리 반에 외국인 학생 한 명밖에 없어요."],
  ["vocab", 9, "문자 보내다", "gửi tin nhắn", "to send a text message", ""],
  ["vocab", 9, "기간", "thời hạn, khoảng thời gian", "period", ""],
  ["vocab", 9, "상담원", "nhân viên tư vấn", "operator", ""],
  ["vocab", 9, "장소", "nơi, địa điểm", "place", ""],
  ["vocab", 9, "접수", "tiếp nhận, đăng ký", "receipt", ""],
  ["vocab", 9, "정보를 얻다", "lấy/nhận thông tin", "to get information", ""],
  ["vocab", 9, "대상", "đối tượng", "target audience", ""],
  ["vocab", 9, "전화를 걸다", "gọi điện", "to make a call", ""],
  ["vocab", 9, "부탁하다", "nhờ vả, yêu cầu giúp đỡ", "to ask someone for a favor", ""],
  ["vocab", 9, "전화를 바꾸다", "chuyển máy", "to give the phone to someone else", ""],
  ["vocab", 9, "통역", "phiên dịch (nói)", "interpretation", ""],
  ["vocab", 9, "전화를 끊다", "tắt máy", "to hang up the phone", ""],
  ["vocab", 9, "창구", "quầy (giao dịch)", "counter", ""],
  ["vocab", 9, "말하다", "nói (kính ngữ)", "to say (honorific expression)", ""],
  ["vocab", 9, "전화를 받다", "nghe điện thoại", "to answer the phone", ""],
  ["vocab", 9, "서비스", "dịch vụ", "service", ""],
  ["vocab", 9, "통역하다", "phiên dịch (động từ)", "to interpret", ""],
  ["vocab", 9, "문자 받다", "nhận tin nhắn", "to receive a text message", ""],
  ["vocab", 9, "전화가 오다", "có điện thoại gọi đến", "to have a phone call", ""],
  ["vocab", 9, "문자를 지우다", "xóa tin nhắn", "to delete a text message", ""],
  ["vocab", 9, "문제가 있다", "có vấn đề/sự cố", "to have a problem", ""],
  ["vocab", 9, "무료", "miễn phí", "no charge", ""],
  ["vocab", 9, "갑자기", "bất ngờ, đột nhiên", "suddenly", ""],
  ["vocab", 9, "문의", "hỏi/thắc mắc, yêu cầu thông tin", "inquiry", ""],
  ["vocab", 9, "궁금하다", "thắc mắc, tò mò", "to be curious", ""],
  ["grammar", 10, "N 중에(서)", "Trong, trong số N", "N: 중에서 · N받침O: 중에서 · N받침X: 중에서", "저는 운동 중에서 야구를 가장 좋아해요.\n지금까지 본 영화 중에(서) 뭐가 제일 재밌있었어요?"],
  ["grammar", 10, "반말", "Tỉnh lược đuôi '요', đổi cách xưng hô (나,너) sử dụng khi đối phương là người có mối quan hệ thân thiết, thân mật với mình. Không hạ thấp cũng không nâng đối phương.", "", "감기 괜찮나? 많이 힘들어?\n난 여자쯤구랑 헤어졌어.\n점심 먹으러 가자. 배고파."],
  ["grammar", 10, "V-(으)ㄹ램요", "diễn tả ý định, sự sẵn sàng của người nói trong câu trần thuật. Ở câu hỏi, nó được dùng để hỏi về ý định, ý thích, nguyện vọng của người nghe.", "V: (으)ㄹ램요 · V받침O: 을램요 · V받침X: ㄹ램요 · V받침ㄹ: 램요", "오끭 시간 있으도월 겙이 영화 보러 갈램요?\n저는 주랙에 그렁 혜자만 있고 요가를 할램요."],
  ["grammar", 10, "A-(으)닀, V-는닀, N 인닀 (2)", "Tuy nhiên, nhưng mà, nhưng...", "A받침O hiện tại: 은닀, quá khứ: 았/었닀 · A받침X hiện tại: ㄴ닀 · V: 는닀 · N: 인닀, quá khứ: 이었/였닀", "이 꿃이 쇔킨닀 향이 안 좋아요.\n열수하구 일을 했는닀 볼이 다 어닀가 갈아요?\n휝생인닀 화쟥을 진하게 하닝요."],
  ["vocab", 10, "시키다", "gọi món", "to order", ""],
  ["vocab", 10, "붕어빵", "bánh cá", "fish-shaped bread", ""],
  ["vocab", 10, "김치찌개", "canh kimchi", "Kimchi stew", ""],
  ["vocab", 10, "갈비찜", "sườn hầm", "short-rib stew", ""],
  ["vocab", 10, "감자탕", "canh xương khoai tây", "potato stew with pork", ""],
  ["vocab", 10, "그릇", "cái bát/tô", "bowl", ""],
  ["vocab", 10, "비빔국수", "mì trộn kiểu Hàn", "noodles mixed with vegetables and red pepper sauce", ""],
  ["vocab", 10, "한정식", "cơm Hàn nhiều món", "Korean multi-course meal", ""],
  ["vocab", 10, "젓다", "khuấy, trộn", "to stir", ""],
  ["vocab", 10, "야채", "rau củ", "vegetable", ""],
  ["vocab", 10, "매운탕", "canh cá cay", "spicy fish stew", ""],
  ["vocab", 10, "후식", "món tráng miệng", "dessert", ""],
  ["vocab", 10, "싱겁다", "nhạt", "to be bland", ""],
  ["vocab", 10, "입에 맞다", "hợp khẩu vị", "to be to one's taste", ""],
  ["vocab", 10, "맛", "vị, mùi vị", "taste", ""],
  ["vocab", 10, "삼겹살", "thịt ba chỉ", "pork belly", ""],
  ["vocab", 10, "떡갈비", "sườn băm nướng", "marinated ground rib meat on the bone", ""],
  ["vocab", 10, "칼국수", "mì cắt tay", "(handmade) chopped noodles", ""],
  ["vocab", 10, "쓰다", "đắng", "to be bitter", ""],
  ["vocab", 10, "배(가) 부르다", "no bụng", "to have a full stomach", ""],
  ["vocab", 10, "짜다", "mặn", "to be salty", ""],
  ["vocab", 10, "케밥", "kebab", "kebab", ""],
  ["vocab", 10, "시다", "chua", "to be sour", ""],
  ["vocab", 10, "순두부찌개", "canh đậu phụ non", "soft tofu stew", ""],
  ["vocab", 10, "된장찌개", "canh tương đậu", "soybean paste stew", ""],
  ["vocab", 10, "냉면", "mì lạnh", "cold noodles", ""],
  ["vocab", 10, "채소", "rau củ", "vegetable", ""],
  ["vocab", 10, "설렁탕", "canh hầm xương", "stock soup of bone and stew meat", ""],
  ["vocab", 10, "끓다", "sôi", "to boil", ""],
  ["vocab", 10, "상", "bàn ăn", "table", ""],
  ["vocab", 10, "맛집", "quán ăn ngon nổi tiếng", "restaurant for renowned delicious food", ""],
  ["vocab", 10, "맵다", "cay", "to be spicy", ""],
  ["vocab", 10, "재료", "nguyên liệu", "ingredient", ""],
  ["vocab", 10, "끓이다", "nấu sôi, đun sôi", "to boil (something)", ""],
  ["vocab", 10, "장을 보다", "đi chợ, mua thực phẩm", "to shop for groceries", ""],
  ["grammar", 11, "'ㅅ' bất quy tắc", "Bất quy tắc (BQT) 'ㅅ' ở một số động từ, tính từ xảy ra khi kết hợp với ngữ pháp bắt đầu bằng nguyên âm, 'ㅅ' sẽ bị tàng hình sau đó kết hợp như từ có patchim bình thưống. Lưu ý các từ 웃다, 씯다, 쇓다, 볓다… là nhớng từ không thể lược bỏ 'ㅅ'.", "V/A받침ㅅ (thuộc BQT), kết hợp với 아/어, (으): 'ㅅ' tàng hình → tiếp tục kết hợp (vd: 나다 + 아/어요 → 냈요; 짓다 + (으)니까 → 지으니까; 붓다 + 아/어서 → 부어서)", "감기가 뵠리 나았으르 좋겠어요.\n밤에 닷면을 먹어서 아읱에 얼굴이 좀 부은 것 같아요."],
  ["grammar", 11, "N 마다", "gắn vào sau từ chỉ thời gian để diễn tả sự lặp lại của hành động hay tình huống nào đó theo thời gian – 'mỗi...' hoặc gắn sau danh từ riêng lẻ, cá thể.", "N: 마다 · N받침O: 마다 · N받침X: 마다", "사람마다 성격이 달랐요.\n40분마다 34불 버스가 와요."],
  ["grammar", 11, "V-는 게 어녕요?", "đưa ra một đề nghị hoặc hỏi ý kiến đối phương nhẹ nhàng – 'Sao không (làm gì đó) nhỉ?, hay là (làm gì đó) đi nhé?'.", "V: 는 게 어녕요? · V받침O: 는 게 어녕요? · V받침X: 는 게 어녕요? · V받침ㄹ: ㄹ(X) + 는 게 어녕요?", "여행가고 싶으면 제주도로 가는 게 어녕요?\n길이 막히는데 지하절을 타는 게 어녕요?"],
  ["grammar", 11, "V-기로 하다", "đưa ra quyết định về một hành động nào đó (thể hiện sự quyết tâm, lời hứa hoặc kế hoạch) – 'quyết định, xác định, định làm...'.", "V: 기로 하다 · V받침O: 기로 하다 · V받침X: 기로 하다 · V받침ㄹ: 기로 하다", "주랐에 희구를 난랐기로 했어요.\n내일 단운 씨와 저랐을 먹기로 했어요."],
  ["vocab", 11, "잠을 잘 못 자다", "ngủ không ngon", "to not sleep well", ""],
  ["vocab", 11, "토하다", "nôn, ói", "to vomit", ""],
  ["vocab", 11, "식후", "sau khi ăn", "after a meal", ""],
  ["vocab", 11, "파스", "cao dán giảm đau", "pain relief patch", ""],
  ["vocab", 11, "알", "viên (thuốc)", "unit noun for pills, etc.", ""],
  ["vocab", 11, "배탈이 나다", "bị đau bụng, rối loạn tiêu hóa", "to have an upset stomach", ""],
  ["vocab", 11, "기운이 없다", "mệt mỏi, không có sức", "to feel feeble/down", ""],
  ["vocab", 11, "진료를 받다", "đi khám bệnh", "to receive medical treatment", ""],
  ["vocab", 11, "낫다", "khỏi bệnh, hồi phục", "to recover", ""],
  ["vocab", 11, "정형외과", "khoa chỉnh hình", "orthopedics", ""],
  ["vocab", 11, "(약을) 먹다", "uống thuốc", "to take (medicine)", ""],
  ["vocab", 11, "기침이 나다", "bị ho", "to have a cough", ""],
  ["vocab", 11, "영양제", "thực phẩm bổ sung dinh dưỡng", "nutritional supplements", ""],
  ["vocab", 11, "다리를 다치다", "bị thương ở chân", "to hurt one's leg", ""],
  ["vocab", 11, "피부과", "khoa da liễu", "dermatology", ""],
  ["vocab", 11, "예방하다", "phòng ngừa", "to prevent", ""],
  ["vocab", 11, "마르다", "gầy, ốm", "to be skinny", ""],
  ["vocab", 11, "속이 안 좋다", "khó chịu trong bụng", "to not feel well in one's stomach", ""],
  ["vocab", 11, "소화가 안 되다", "khó tiêu", "to have indigestion", ""],
  ["vocab", 11, "두통약", "thuốc đau đầu", "headache pill", ""],
  ["vocab", 11, "날씬하다", "thon thả, mảnh mai", "to be slim", ""],
  ["vocab", 11, "입맛이 없다", "chán ăn, không thèm ăn", "to have no appetite", ""],
  ["vocab", 11, "똥똥하다", "béo, mập", "to be fat", ""],
  ["vocab", 11, "붓다", "sưng", "to swell", ""],
  ["vocab", 11, "(안약을) 넣다", "nhỏ (thuốc mắt)", "to put in (eye drops)", ""],
  ["vocab", 11, "멀미를 하다", "bị say xe/tàu", "to have motion sickness", ""],
  ["vocab", 11, "(연고를) 바르다", "bôi (thuốc mỡ)", "to apply (an ointment)", ""],
  ["vocab", 11, "안약", "thuốc nhỏ mắt", "eye drops", ""],
  ["vocab", 11, "(파스를) 붙이다", "dán (cao dán giảm đau)", "to apply (a pain relief patch)", ""],
  ["vocab", 11, "안과", "khoa mắt", "ophthalmology", ""],
  ["vocab", 11, "감기약", "thuốc cảm", "cold medicine", ""],
  ["vocab", 11, "어지럽다", "chóng mặt", "to be dizzy", ""],
  ["vocab", 11, "연고", "thuốc mỡ", "ointment", ""],
  ["vocab", 11, "내과", "khoa nội", "internal medicine", ""],
  ["vocab", 11, "얼굴에 뭐가 나다", "bị mọc mụn/nổi trên mặt", "to have one's face break out", ""],
  ["vocab", 11, "멀미약", "thuốc say xe", "motion sickness medicine", ""],
  ["vocab", 11, "소화제", "thuốc tiêu hóa", "digestive medicine", ""],
  ["vocab", 11, "해열제", "thuốc hạ sốt", "fever reducer", ""],
  ["vocab", 11, "치과", "khoa răng, nha khoa", "the dentist", ""],
  ["grammar", 12, "A-아/어 보이다", "Diễn tả sự phỏng đoán hoặc cảm nhận của người nói dựa trên vẻ bề ngoài của người, sự vật, sự việc – 'trông có vẻ, có vẻ...'.", "A: 아/어 보이다 · A(ㅏ,ㅗ): 아 보이다 · A(ㅓ,ㅜ,ㅣ...): 어 보이다 · A(하다): 해 보이다", "그 가방 뱄싸 보이는데요.\n요끭은 건강해 보이니요. 운동 열심히 했어요?"],
  ["grammar", 12, "N 철럼[같이]", "Diễn tả hành động hay sự việc nào đó có biểu hiện giống nhau hoặc đồng nhất với danh từ đứng trước nó – 'Giống như N'.", "N: 철럼[같이] · N받침O: 철럼[같이] · N받침X: 철럼[같이]", "모랐 씨는 가수철럼 덼래를 잘해요.\n하띴 종일 밥 볼 먹는 것철럼 먹뗠요."],
  ["grammar", 12, "A-(으)ㄴ 편이다, V-는 편이다", "Thuộc diện, thuộc loại, thuộc tuýp, thuộc kiểu...", "V받침O: 는 편이다 · V받침X: 는 편이다 · A받침O: 은 편이다 · A받침X: ㄴ편이다 · A받침ㄹ: ㄹ(X)+ㄴ 편이다", "제 동생은 좀 마릸 편이에요.\n저는 매운 음식을 잘 먹는 편이에요."],
  ["grammar", 12, "A-게", "Đóng vai trò như một trạng từ trong câu, dùng để biểu thị mức độ, phương thức hoặc suy nghĩ về hành động nào đó – 'Một cách A'.", "A: 게 · A받침O: 게 · A받침X: 게 · A받침ㄹ: 게", "오끭 데이트가 있어서 예쁜게 입었어요.\n주랐에 희구를과 재밌있게 랙았어요."],
  ["vocab", 12, "여성적이다", "có tính nữ tính", "to be feminine", ""],
  ["vocab", 12, "꼼꼼하다", "tỉ mỉ, cẩn thận", "to be meticulous", ""],
  ["vocab", 12, "내성적이다", "hướng nội, kín đáo", "to be introverted; reserved", ""],
  ["vocab", 12, "속마음", "suy nghĩ trong lòng", "inner thoughts", ""],
  ["vocab", 12, "첫인상", "ấn tượng đầu tiên", "first impression", ""],
  ["vocab", 12, "남성적이다", "có tính nam tính", "to be masculine", ""],
  ["vocab", 12, "활발하다", "năng động, hoạt bát", "to be active; to be outgoing", ""],
  ["vocab", 12, "(성격이) 급하다", "vội vàng, nóng tính", "to be hasty", ""],
  ["vocab", 12, "보통이다", "bình thường", "to be average", ""],
  ["vocab", 12, "눈", "Mắt", "", ""],
  ["vocab", 12, "눈이 크다", "Mắt to", "", ""],
  ["vocab", 12, "눈이 작다", "Mắt nhỏ", "", ""],
  ["vocab", 12, "눈썹이 진하다", "Lông mày đậm", "", ""],
  ["vocab", 12, "눈썹이 연하다", "Lông mày nhạt", "", ""],
  ["vocab", 12, "쌍꺼풀", "Mí mắt hai mí", "", ""],
  ["vocab", 12, "쌍꺼풀이 있다", "Có hai mí", "", ""],
  ["vocab", 12, "쌍꺼풀이 없다", "Không có hai mí", "", ""],
  ["vocab", 12, "코", "Mũi", "", ""],
  ["vocab", 12, "코가 높다", "Mũi cao", "", ""],
  ["vocab", 12, "코가 낮다", "Mũi thấp", "", ""],
  ["vocab", 12, "입", "Miệng", "", ""],
  ["vocab", 12, "입이 크다", "Miệng to", "", ""],
  ["vocab", 12, "입이 작다", "Miệng nhỏ", "", ""],
  ["vocab", 12, "입술", "Môi", "", ""],
  ["vocab", 12, "입술이 두껍다", "Môi dày", "", ""],
  ["vocab", 12, "입술이 얇다", "Môi mỏng", "", ""],
  ["vocab", 12, "이마", "Trán", "", ""],
  ["vocab", 12, "이마가 넓다", "Trán rộng", "", ""],
  ["vocab", 12, "이마가 좁다", "Trán hẹp", "", ""],
  ["vocab", 12, "어깨", "Vai", "", ""],
  ["vocab", 12, "어깨가 넓다", "Vai rộng", "", ""],
  ["vocab", 12, "어깨가 좁다", "Vai hẹp", "", ""],
  ["vocab", 12, "키", "Chiều cao", "", ""],
  ["vocab", 12, "키가 크다", "Cao", "", ""],
  ["vocab", 12, "키가 작다", "Thấp", "", ""],
  ["vocab", 12, "성격", "Tính cách", "", ""],
  ["vocab", 12, "활발하다", "Hoạt bát, năng động", "", ""],
  ["vocab", 12, "내성적이다", "Hướng nội", "", ""],
  ["vocab", 12, "꼼꼼하다", "Cẩn thận, tỉ mỉ", "", ""],
  ["vocab", 12, "성격이 급하다", "Nóng vội, hấp tấp", "", ""],
  ["vocab", 12, "날씬하다", "thon thả", "", ""],
  ["vocab", 12, "멋있다", "đẹp trai, ngầu", "", ""],
  ["vocab", 12, "똑똑하다", "thông minh", "", ""],
  ["vocab", 12, "어리다", "trẻ", "", ""],
  ["vocab", 12, "뚱뚱하다", "mập", "", ""],
  ["grammar", 13, "V/A-(으)ㄹ지 모르겠다", "Thể hiện sự không chắc chắn về một hành động, tính chất của sự việc, con người – 'Không biết...có...hay không, có thể/có lẽ...'", "V/A: (으)ㄹ지 모르겠다 · V/A받침O: 을지 모르겠다 · V/A받침X: ㄹ지 모르겠다 · V/A받침ㄹ: 지 모르겠다", "희엘 씨한타 선물을 샀는데 좋아할지 모르겠어요.\n담배를 꾠고 싶은데 꾠을 수 있을지 모르겠어요."],
  ["grammar", 13, "V/A-기는 하지만", "Vẫn công nhận nội dung của vế trước nhưng vẫn đưa ra ý kiến/thông tin khác hoàn toàn ở vế sau – 'A/V thì có A/V nhưng...'", "V/A: 기는 하지만 · V/A받침O: 기는 하지만 · V/A받침X: 기는 하지만 · V/A받침ㄹ: 기는 하지만", "이 식당은 음식이 마있기는 하지만 가이 뱄싸요.\n오끭 아을 먹기는 했지만 아직 배가 고파요."],
  ["grammar", 13, "V/A-기 때문에, N(이)기 때문에", "diễn tả vế trước là nguyên nhân cho vế sau – 'Vì..., bởi vì...'", "V/A받침O: 기 때문에 · V/A받침X: 기 때문에 · N받침O: 이기 때문에 · N받침X: 때문에", "집에서 학교까지 액기 땄문에 아에 일첨 나와야 해요.\n요끭 보도이기 땄문에 시간이 많아요."],
  ["grammar", 13, "V-기(가) A", "Thể hiện sự đánh giá, phán đoán, nhận xét ở vế sau cho hành động diễn ra ở vế trước, thường đi kèm các tính từ như 쉭다, 어렵다, 좋다, 나ư다, 편하다...", "V: 기(가) · V받침O: 기(가) · V받침X: 기(가)", "주변에 시장도 있고 지하철역도 가까워서 살기 편해요.\n이 음식은 니부 매웠서 추운 날씨 때 먹기가 좋아요."],
  ["vocab", 13, "월세", "tiền thuê hàng tháng", "monthly rent", ""],
  ["vocab", 13, "비어 있다", "trống, chưa có người ở", "to be unoccupied", ""],
  ["vocab", 13, "방값이 싸다", "tiền phòng rẻ", "to have cheap rent", ""],
  ["vocab", 13, "보증금", "tiền đặt cọc", "security deposit", ""],
  ["vocab", 13, "주변이 조용하다", "xung quanh yên tĩnh", "to have quiet surroundings", ""],
  ["vocab", 13, "방", "phòng", "room", ""],
  ["vocab", 13, "아파트", "chung cư", "apartment", ""],
  ["vocab", 13, "수도 요금", "tiền nước", "water bill", ""],
  ["vocab", 13, "전기 요금", "tiền điện", "electric bill", ""],
  ["vocab", 13, "계약", "hợp đồng", "contract", ""],
  ["vocab", 13, "주택", "nhà ở", "house", ""],
  ["vocab", 13, "원룸", "phòng trọ một phòng", "studio apartment", ""],
  ["vocab", 13, "고시원", "phòng trọ thi cử (gosiwon)", "examination preparation housing", ""],
  ["vocab", 13, "부동산", "bất động sản", "real estate", ""],
  ["vocab", 13, "베란다", "ban công", "veranda", ""],
  ["vocab", 13, "이웃", "hàng xóm", "neighbor", ""],
  ["vocab", 13, "방이 넓다", "phòng rộng", "to have a spacious room", ""],
  ["vocab", 13, "새로 지었다", "mới xây", "to be newly built", ""],
  ["vocab", 13, "거실", "phòng khách", "living room", ""],
  ["vocab", 13, "현관", "lối vào, sảnh trước", "front entrance", ""],
  ["vocab", 13, "하숙집", "nhà trọ có ăn (hasukjip)", "boarding house", ""],
  ["vocab", 13, "오피스텔", "officetel (căn hộ kết hợp văn phòng)", "office with kitchen and sleeping facilities", ""],
  ["vocab", 13, "집주인이 좋다", "chủ nhà tốt", "to have a nice landlord", ""],
  ["vocab", 13, "주변 환경", "môi trường xung quanh", "surroundings; neighborhood", ""],
  ["vocab", 13, "가스 요금", "tiền gas", "gas bill", ""],
  ["vocab", 13, "전망이 좋다", "có tầm nhìn đẹp", "to have a good view", ""],
  ["vocab", 13, "부엌", "nhà bếp", "kitchen", ""],
  ["vocab", 13, "전세", "jeonse (thuê nhà trả tiền cọc lớn)", "long term deposit lease", ""],
  ["vocab", 13, "빌라", "nhà villa", "villa", ""],
  ["vocab", 13, "기숙사", "ký túc xá", "dormitory", ""],
  ["vocab", 13, "집세", "tiền nhà", "rent", ""],
  ["vocab", 13, "관리비", "phí quản lý/dịch vụ", "maintenance fee", ""],
  ["vocab", 13, "화장실", "nhà vệ sinh", "bathroom", ""],
  ["vocab", 13, "시설이 잘되어 있다", "có cơ sở vật chất tốt", "to have good facilities", ""],
  ["grammar", 14, "V-(으)ㄴ 적(이) 있다[없다]", "thể hiện việc có hay không có kinh nghiệm trong việc nào đó – 'Đã từng/ chưa từng V'", "V: (으)ㄴ적이 있다[없다] · V받침O: 은 적이 있다[없다] · V받침X: ㄴ 적이 있다[없다] · V받침ㄹ: ㄹ(X) + ㄴ적이 있다[없다]", "저 사랐을 전에 난랐 적이 있어요.\n예전에 이 책을 읽은 적이 있어요."],
  ["grammar", 14, "V/A-았을/었을 땄", "biểu hiện thời điểm một việc nào đó trong quá khứ diễn ra hoặc tồn tại – ' Khi/Lúc đã...'", "V/A: 았/었을 땄 · V/A(ㅏ,ㅗ): 았을 땄 · V/A(ㅓ,ㅜ,ㅣ…): 었을 땄 · V/A(하다): 했을 땄", "어띨을 낞을 땄는 고개를 숨여서 인사해야 돼요.\n어래을 땄 한국에 와 봤을 적이 있어요."],
  ["grammar", 14, "V-아도/어도 돼다", "hỏi xin phép hoặc biểu hiện sự cho phép đối với một hành vi nào đó – 'Được phép V...', V...có được không?'", "V: 아/어도 돼다 · V(ㅏ,ㅗ): 아도 돼다 · V(ㅓ,ㅜ,ㅣ…): 어도 돼다 · V(하다): 해도 돼다", "5시 똈으니까 월저 가도 돼요.\n숙제를 오끭까지 내야 해요? – 아니요, 내일 내도 돼요."],
  ["grammar", 14, "V-(으)면 안 돼다", "biểu hiện sự không cho phép thực hiện hành vi nào đó – 'Không được phép V..., nếu V thì không được'.", "V: (으)면 안 돼다 · V받침O: 으면 안 돼다 · V받침X: 면 안 돼다 · V받침ㄹ: 면 안 돼다", "여기에서는 담배를 피우으면 안 됩니다.\n교실에서 음식을 먹으면 안 됩니다."],
  ["vocab", 14, "음식물 반입 금지", "cấm mang đồ ăn/thức uống vào", "No Food or Drinks", ""],
  ["vocab", 14, "만지다", "sờ, chạm vào", "to touch", ""],
  ["vocab", 14, "사진 촬영 금지", "cấm chụp ảnh", "No Photographs", ""],
  ["vocab", 14, "금연", "cấm hút thuốc", "No Smoking", ""],
  ["vocab", 14, "휴대 전화 사용 금지", "cấm sử dụng điện thoại", "No Cell Phones", ""],
  ["vocab", 14, "예절", "phép lịch sự, phép tắc", "", ""],
  ["vocab", 14, "반말", "ối nói không kính ngữ, dùng với bạn bè, người nhỏ tuổi hơn", "", ""],
  ["vocab", 14, "높임말[존댓말]을 해요", "높임말 = 존댓말 = lối nói lịch sự, tôn trọng, dùng với người lớn tuổi/cấp trên", "", ""],
  ["vocab", 14, "공중도덕", "đạo đức công cộng", "", ""],
  ["vocab", 14, "금연", "cấm hút thuốc", "", ""],
  ["vocab", 14, "주차 금지", "cấm đậu xe", "", ""],
  ["vocab", 14, "사진 촬영 금지", "cấm chụp ảnh", "", ""],
  ["vocab", 14, "음식물 반입 금지", "cấm mang thức ăn vào", "", ""],
  ["vocab", 14, "휴대 전화 사용 금지", "cấm sử dụng điện thoại di động", "", ""],
  ["grammar", 15, "A-아지다/어지다", "Diễn tả sự biến đổi của trạng thái theo thời gian – 'trở nên, càng, dần...'", "A: 아/어지다 · A(ㅏ,ㅗ): 아지다 · A(ㅓ,ㅜ,ㅣ…): 어지다 · A(하다): 해지다", "과일값이 많이 뱄싸졌어요.\n날씨가 점점 더워지똀요."],
  ["grammar", 15, "V-게 돼다", "Thể hiện sự thay đổi sang một trạng thái, tình huống nào đó do hoàn cảnh khách quan hoặc có sự tác động từ bên ngoài – ' trở nên, được, bị, phải...'", "V: 게 돼다 · V받침O: 게 돼다 · V받침X: 게 돼다 · V받침ㄹ: 게 돼다", "한국 돈 좋아해서 한국어를 뱰우게 되었어요.\n다음 뚜부탐 회샀 일도 출장가게 뙈어요."],
  ["grammar", 15, "V-기 전에", "Diễn tả sự việc này diễn ra trước khi thực hiện sự việc kia – 'trước khi V...'", "V: 기 전에 · V받침O: 기 전에 · V받침X: 기 전에 · V받침ㄹ: 기 전에", "주타에 뎤이가기 전에 흡산 여행을 할 거예요.\n밥을 먹기 전에 손을 쎘으세요."],
  ["grammar", 15, "V-(으)ㄴ 후에", "Diễn tả sự việc này diễn ra sau khi thực hiện sự việc kia – 'Sau khi V...'", "V: (으)ㄴ 후에 · V받침O: 은 후에 · V받침X: ㄴ 후에 · V받침ㄹ: ㄹ(X) + ㄴ 후에", "숙제부타 한 후에 녹는 게 어때?\n저는 아을 먹은 후에 커피를 마셔요."],
  ["vocab", 15, "유학", "du học", "studying abroad", ""],
  ["vocab", 15, "고개를 숙여서 인사하다", "cúi đầu chào", "to greet while bowing one's head", ""],
  ["vocab", 15, "예절", "lễ nghĩa, phép tắc", "etiquette", ""],
  ["vocab", 15, "두 손으로 드리다", "đưa bằng hai tay", "to give with both hands", ""],
  ["vocab", 15, "한 손으로 받다", "nhận bằng một tay", "to receive with one hand", ""],
  ["vocab", 15, "습관", "thói quen", "habit", ""],
  ["vocab", 15, "익숙하다", "quen, thành thói quen", "to be accustomed to", ""],
  ["vocab", 15, "친구를 사귀다", "kết bạn", "to make a friend", ""],
  ["vocab", 15, "자리를 양보하다", "nhường ghế", "to offer one's seat to others", ""],
  ["vocab", 15, "고개를 돌리고 마시다", "quay đầu sang một bên khi uống", "to drink turning one's head", ""],
  ["vocab", 15, "평소", "thường ngày", "usual day", ""],
  ["vocab", 15, "노력하다", "cố gắng, nỗ lực", "to make an effort", ""],
  ["vocab", 15, "정(이) 들다", "trở nên gắn bó, có tình cảm", "to become emotionally attached", ""],
  ["vocab", 15, "인생", "Nhân Sinh", "", ""],
  ["vocab", 15, "태어나다", "được sinh ra, chào đời", "태어났어요.", ""],
  ["vocab", 15, "입학하다", "nhập học", "", ""],
  ["vocab", 15, "친구를 사귀다", "kết bạn", "", ""],
  ["vocab", 15, "사랑에 빠지다", "yêu, phải lòng ai đó", "", ""],
  ["vocab", 15, "졸업하다", "tốt nghiệp", "", ""],
  ["vocab", 15, "취직하다", "xin được việc làm, đi làm", "", ""],
  ["vocab", 15, "결혼하다", "kết hôn", "", ""],
  ["vocab", 15, "아기를 낳다", "sinh con", "", ""],
  ["vocab", 15, "승진하다", "thăng chức", "", ""],
  ["vocab", 15, "은퇴하다", "nghỉ hưu", "", ""],
  ["vocab", 15, "죽다", "chết, qua đời", "", ""],
  ["vocab", 15, "늘다", "tăng lên, nhiều lên", "", ""],
  ["vocab", 15, "줄다", "giảm đi, ít lại", "", ""],
  ["vocab", 15, "오르다", "tăng, lên (giá cả, nhiệt độ...)", "", ""],
  ["vocab", 15, "내리다", "giảm, xuống (giá cả, nhiệt độ...)", "", ""],
  ["vocab", 15, "생기다", "xuất hiện, hình thành, mọc lên", "", ""],
  ["vocab", 15, "발전하다", "phát triển", "", ""],
  ["grammar", 16, "V-아/어 놓다", "Diễn tả một hành động đã hoàn tất nhưng trạng thái kết quả của nó vẫn được duy trì và kéo dài đến hiện tại và tương lai – 'V ...để đấy, V...sẵn, V...sẵn rồi..'", "V: 아/어 놓다 · V(ㅏ,ㅗ): 아 놓다 · V(ㅓ,ㅜ,ㅣ…): 어 놓다 · V(하다): 해 놓다", "동생에제 주랐고 가방을 샨 놓았어요.\n제가 봌랐 예약해 놓았으니까 걱정하지 번세요."],
  ["grammar", 16, "N 대신", "Diễn tả sự thay thế danh từ đi trước bằng danh từ đi sau – 'Thay, thay thế, thay cho N...'", "N: 대신 · N받침O: 대신 · N받침X: 대신", "제가 아파서 희구가 저 대신 운전을 했어요.\n시간이 없어서 밥 대신 우유만 한 잔 달았어요."],
  ["grammar", 16, "V-(으)ㄹ까 하다", "Thể hiện việc suy nghĩ, dự định sẽ làm một việc gì đó một cách mơ hồ, chưa chắc chắn, chỉ dùng cho ngôi thứ nhất – 'dự định, định, đang suy nghĩ...'", "V: (으)ㄹ까 하다 · V받침O: 을까 하다 · V받침X: ㄹ까 하다", "이분 휴가 때 부모랐과 여행갈까 해요.\n오끭 저랐에 한식을 먹을까 하는데 겙이 먹을램요?"],
  ["grammar", 16, "V/A-(으)ㄹ 타니까", "Thể hiện ý chí, thiện chí của người nói (V) và gợi ý cho người nghe làm theo ý mình, hoặc sự phán đoán (A) của người nói – 'Tôi sẽ V1, vậy nên bạn hãy V2 đi', 'vì sẽ...nên...'", "V/A: (으)ㄹ 타니까 · V/A받침O: 을 타니까 · V/A받침X: ㄹ 타니까", "제가 구부 도착할 타니까 조금만 기다래세요.\n밥을 제가 할 타니까 이뚙가 식사 후에 설거지하세요."],
  ["vocab", 16, "성묘(를) 하다", "đi tảo mộ", "to visit and pay one's respects at ancestors' grave", ""],
  ["vocab", 16, "한복을 입어요", "mặc hanbok", "to wear Korean traditional dress", ""],
  ["vocab", 16, "윷놀이(를) 하다", "chơi Yut (trò chơi truyền thống)", "to play Yut", ""],
  ["vocab", 16, "고향에 가다", "về quê", "to go to one's hometown", ""],
  ["vocab", 16, "세배(를) 하다", "lạy chào năm mới (sebae)", "to give a New Year's bow", ""],
  ["vocab", 16, "조상", "tổ tiên", "ancestor", ""],
  ["vocab", 16, "차례를 지내다", "cúng giỗ tổ tiên", "to perform ancestral rite", ""],
  ["vocab", 16, "떡국", "canh bánh gạo (tteokguk)", "rice-cake soup", ""],
  ["vocab", 16, "빈대떡을 부치다", "chiên bánh đậu xanh", "to make mung-bean pancake", ""],
  ["vocab", 16, "빈대떡", "bánh đậu xanh chiên", "mung-bean pancake", ""],
  ["vocab", 16, "한과", "bánh kẹo truyền thống Hàn Quốc", "Korean traditional sweets and cookies", ""],
  ["vocab", 16, "식혜", "nước gạo ngọt (sikhye)", "sweet rice drink", ""],
  ["vocab", 16, "음식을 차리다", "bày món ăn ra", "to set the table with food", ""],
  ["vocab", 16, "보름달", "trăng tròn", "full moon", ""],
  ["vocab", 16, "명절", "ngày lễ truyền thống", "traditional holidays", ""],
  ["vocab", 16, "돌잔치", "tiệc đầy năm", "first birthday party", ""],
  ["vocab", 16, "강강술래", "múa vòng tròn truyền thống", "traditional Korean circle dance", ""],
  ["vocab", 16, "소원을 빌다", "cầu nguyện điều ước", "to make a wish", ""],
  ["vocab", 16, "색동저고리", "áo khoác nhiều màu truyền thống", "multicolored Korean topcoat", ""],
  ["vocab", 16, "추수하다", "thu hoạch", "to harvest", ""],
  ["vocab", 16, "연휴", "kỳ nghỉ dài", "long weekend; holidays", ""],
  ["vocab", 16, "모시다", "đưa người lớn tuổi đi", "to take elders some place", ""],
  ["vocab", 16, "김치를 담그다", "làm/ướp kimchi", "to make kimchi", ""],
  ["vocab", 16, "민속촌", "làng dân gian", "folk village", ""],
  ["grammar", 17, "V-아다/어다 주다", "Hai hành động diễn ra tuần tự ở từng đặa điểm khác nhau – 'V1 xong rối mới đến V2'. Khi kết hợp với từ như '모시다, 데리다', hiểu là đưa (dẫn/đi cùng với) người/con vật đến tận nơi.", "V: 아/어다 주다 · V(ㅏ,ㅗ): 아다 주다 · V(ㅓ,ㅜ,ㅣ…): 어다 주다 · V(하다): 해다 주다", "오보가 고장 난 컴퓨타를 고철다 옃어요.\n아이를 학교에 데리다 주고 왔어요."],
  ["grammar", 17, "V-(으)ㄹ 뻔하다", "diễn tả sự may mắn khi việc gì đó có khả năng cao sẽ xảy ra nhưng thực tế lại đã không xảy ra – 'suýt nữa thì...' (luôn chia ở dạng quá khứ).", "V: (으)ㄹ 뻔하다 · V받침O: 을 뻔하다 · V받침X: ㄹ 뻔하다 · V받침ㄹ: ㄹ 뻔하다", "학교에 오다가 사고가 난 뻔했어요.\n뛱게 일어랐서 약쇐에 뚜을 뻔했어요."],
  ["grammar", 17, "'ㅎ' bất quy tắc", "BQT 'ㅎ' với một số V/A kết thúc bằng ㅎ, khi gặp nguyên âm thì ㅎ sẽ bị lược bỏ, khi gặp –(으) thì cả ㅎ và 으 sẽ bị lược bỏ.", "V/A thuộc BQT 'ㅎ', kết hợp với (으): ㅎ(X) — vd: 까랐하다+(으)니까→까랤니까; kết hợp với 아/어: ㅎ(X)→애/어 — vd: 하얖하다+아/어요→하얖요", "한국 사랐의 래랐 색깔은 까래요.\n뛀이 많이 와서 뱄이 하얖요."],
  ["grammar", 17, "V-아/어 있다", "Diễn tả hành động đã xảy ra nhưng trạng thái vẫn được duy trì đến hiện tại – 'đang V'.", "V: 아/어 있다 · V(ㅏ,ㅗ): 아 있다 · V(ㅓ,ㅜ,ㅣ…): 어 있다 · V(하다): 해 있다", "희구가 교통사고가 나서 지금 병원에 입원해 있어요.\n모자를 쓰고 있는 사랐의 스티블 씨예요."],
  ["vocab", 17, "잃어버리다", "làm mất", "", ""],
  ["vocab", 17, "놓치다", "lỡ, bỏ lỡ", "to miss", ""],
  ["vocab", 17, "넘어지다", "ngã, té", "to fall over", ""],
  ["vocab", 17, "거의", "hầu như, gần như", "almost", ""],
  ["vocab", 17, "부딪히다", "va vào, đụng phải", "to bump into", ""],
  ["vocab", 17, "떨어뜨리다", "làm rơi", "to drop", ""],
  ["vocab", 17, "불(이) 나다", "bị) cháy, hỏa hoạn", "", ""],
  ["vocab", 17, "사고가 나다", "xảy ra tai nạn", "to have an accident", ""],
  ["vocab", 17, "고장이 나다", "(bị) hỏng, hư (xe, máy móc...)", "", ""],
  ["vocab", 17, "큰일이 나다", "xảy ra việc lớn/nghiêm trọng", "to have a big problem", ""],
  ["vocab", 17, "줄무늬", "họa tiết kẻ sọc", "", ""],
  ["vocab", 17, "꽃무늬", "họa tiết hoa", "", ""],
  ["vocab", 17, "체크무늬", "họa tiết caro/ô vuông", "", ""],
  ["vocab", 17, "물방울무늬", "họa tiết chấm bi", "", ""],
  ["vocab", 17, "후회가 되다", "hối hận", "to feel regret", ""],
  ["vocab", 17, "야단(을) 맞다", "bị mắng", "to get a scolding", ""],
  ["vocab", 17, "사정이 있다", "có lý do/hoàn cảnh", "to have a reason/situation", ""],
  ["vocab", 17, "시간을 지키다", "đúng giờ", "to keep time", ""],
  ["vocab", 17, "다행이다", "may mắn, thật may", "to be fortunate", ""],
  ["vocab", 17, "태풍이 오다", "có bão tới", "to have a typhoon come", ""],
  ["vocab", 17, "실수하다", "mắc lỗi, phạm sai lầm", "to make a mistake", ""],
  ["vocab", 17, "정신(이) 없다", "rối trí, mất bình tĩnh", "to be out of one's senses", ""],
  ["vocab", 17, "마침", "vừa kịp, đúng lúc", "just in time; luckily", ""],
  ["grammar", 18, "V-(으)ㄴ 지", "Diễn tả từ khi làm một việc nào đó thì đã được bao lâu rối – 'Kể từ khi V...'", "V: (으)ㄴ 지 · V받침O: 은 지 · V받침X: ㄴ 지 · V받침ㄹ: ㄹ(X) + ㄴ 지", "대학교를 졸업한 지 일 랐이 되었어요.\n기숙사에 산 지 얼마니 똈어요? – 한 뛀밖에 안 똈어요."],
  ["grammar", 18, "N(이)나 (2)", "Diễn tả số lượng nhiều hơn so với suy nghĩ và mong đợi của người nói – 'nhớng, tận, đến tận...'", "N: (이)나 · N받침O: 이나 · N받침X: 나", "우랐 가족은 아홉 목이나 있어요.\n민영 씨는 건가 다섯 래랐는 키워요."],
  ["grammar", 18, "A-다, V-ㄴ다/는다", "Sử dụng khi trần thuật sự việc, sự kiện trong các văn bản như bài báo, văn nghị luận, bài nghiên cứu, nhật ký...", "A받침O: 다 · A받침X: 다 · V받침O: 는다 · V받침X: ㄴ다", "밤에 바래이 부어서 아주 시원하다.\n나랐 자기 전에 책을 읽는다.\n나랐 매일 아 8시에 출구한다."],
  ["grammar", 18, "N(이)다", "Sử dụng khi trần thuật sự việc, sự kiện trong các văn bản như bài báo, văn nghị luận, bài nghiên cứu, nhật ký...", "N: (이)다 · N받침O: 이다 · N받침X: 다", "여기는 나가 일하는 회샀다.\n어제는 어버지 생신이었다."],
  ["vocab", 18, "시간이 지나가다", "thời gian trôi qua", "time goes by", ""],
  ["vocab", 18, "나이가 들다", "lớn tuổi hơn, già đi", "to get older", ""],
  ["vocab", 18, "변화", "sự thay đổi", "change", ""],
  ["vocab", 18, "오랜만에", "sau một thời gian dài", "after a long time", ""],
  ["vocab", 18, "바뀌다", "thay đổi", "to be changed", ""],
  ["vocab", 18, "추억", "kỷ niệm", "memory", ""],
  ["vocab", 18, "실력이 늘다", "tiến bộ, nâng cao trình độ", "to improve oneself", ""],
  ["vocab", 18, "오래간만이다", "đã lâu rồi", "It's been a long time", ""],
  ["vocab", 18, "발전하다", "phát triển", "to develop", ""],
  ["vocab", 18, "아직도", "vẫn còn", "still", ""],
]

export function createDefaultCards(): KoreanCard[] {
  const now = new Date().toISOString()
  return ENTRIES.map(([kind, lesson, front, meaning, note, example], index) => ({
    id: nanoid(),
    kind,
    lesson,
    front,
    meaning,
    note,
    example,
    sortOrder: index,
    createdAt: now,
  }))
}
