// Bộ câu hỏi luyện nói theo từng bài, do LLM soạn dựa trên đúng từ vựng/ngữ pháp của bài học.
// Độ khó tăng dần: dễ (Yes/No, thông tin cơ bản) → trung bình (ý kiến, kinh nghiệm) → nâng cao (lý do, so sánh, suy đoán).
export interface SpeakingPracticeItem {
  level: 'Dễ' | 'Trung bình' | 'Nâng cao'
  question: string
  questionVi: string
  answer: string
  grammar: string
  answerVi: string
}

export interface SpeakingPracticeSet {
  intro: string
  items: SpeakingPracticeItem[]
  grammarSummary: { label: string; note: string }[]
  vocabSummary: string
}

export const SPEAKING_PRACTICE: Record<number, SpeakingPracticeSet> = {
  1: {
    intro:
      'Bám sát 20 từ vựng và 2 ngữ pháp của Bài 1: N(이)라고 하다 — giới thiệu/gọi tên, và V-(으)려고 — diễn tả mục đích, ý định.',
    items: [
      {
        level: 'Dễ',
        question: '안녕하세요? 이름이 뭐예요?',
        questionVi: 'Xin chào, bạn tên là gì?',
        answer: '안녕하세요. 저는 후엔이라고 해요.',
        grammar: 'N(이)라고 하다',
        answerVi: 'Xin chào. Tôi tên là Huyền.',
      },
      {
        level: 'Dễ',
        question: '성함이 어떻게 되세요? 성이 뭐예요?',
        questionVi: 'Họ tên đầy đủ của bạn là gì? Họ của bạn là gì?',
        answer: '제 성은 팜이라고 하고 이름은 후엔이라고 해요. 성명은 팜티후엔이에요.',
        grammar: 'N(이)라고 하다',
        answerVi: 'Họ của tôi là Phạm, tên là Huyền. Họ tên đầy đủ của tôi là Phạm Thị Huyền.',
      },
      {
        level: 'Dễ',
        question: '형제들이 있어요?',
        questionVi: 'Bạn có anh chị em không?',
        answer: '네, 언니가 한 명 있어요. 언니는 마이라고 해요.',
        grammar: 'N(이)라고 하다',
        answerVi: 'Vâng, tôi có một chị gái. Chị ấy tên là Mai.',
      },
      {
        level: 'Trung bình',
        question: '외국인 등록증을 만들어 봤어요? 어땠어요?',
        questionVi: 'Bạn đã từng làm thẻ đăng ký người nước ngoài chưa? Thế nào rồi?',
        answer: '네, 만들어 봤어요. 주소하고 연락처를 쓰려고 서류를 준비했어요. 좀 복잡했지만 괜찮았어요.',
        grammar: 'V-(으)려고',
        answerVi: 'Vâng, tôi làm rồi. Tôi đã chuẩn bị giấy tờ để viết địa chỉ và thông tin liên lạc. Hơi phức tạp nhưng cũng ổn.',
      },
      {
        level: 'Trung bình',
        question: '처음 만난 사람 이름을 어떻게 불러요? 성이나 이름 중에서 뭐라고 불러요?',
        questionVi: 'Bạn gọi tên người mới gặp như thế nào? Gọi bằng họ hay tên?',
        answer: '저는 보통 이름으로 불러요. 예를 들어서 제가 "저는 후엔이라고 해요"라고 말하면 친구들은 그냥 "후엔"이라고 불러요.',
        grammar: 'N(이)라고 하다',
        answerVi: 'Tôi thường gọi bằng tên. Ví dụ khi tôi nói "Tôi tên là Huyền" thì bạn bè chỉ gọi là "Huyền" thôi.',
      },
      {
        level: 'Trung bình',
        question: '종교가 있어요? 가족들하고는 자주 연락해요?',
        questionVi: 'Bạn có tôn giáo không? Bạn có thường liên lạc với gia đình không?',
        answer: '저는 종교가 없어요. 그렇지만 가족들한테 전화하려고 매주 시간을 내요. 그게 저한테 힘이 돼요.',
        grammar: 'V-(으)려고',
        answerVi: 'Tôi không có tôn giáo. Nhưng tôi dành thời gian mỗi tuần để gọi điện cho gia đình. Điều đó tiếp thêm sức mạnh cho tôi.',
      },
      {
        level: 'Trung bình',
        question: '전화하는 것과 이메일을 보내는 것 중에서 뭐가 더 편해요?',
        questionVi: 'Giữa gọi điện và gửi email, cái nào tiện hơn với bạn?',
        answer: '저는 이메일이 더 편해요. 주소나 전화번호 같은 정보를 보내려고 할 때 실수가 적어요.',
        grammar: 'V-(으)려고',
        answerVi: 'Tôi thấy email tiện hơn. Vì khi định gửi những thông tin như địa chỉ hay số điện thoại thì ít bị sai sót hơn.',
      },
      {
        level: 'Nâng cao',
        question: '왜 한국어를 배우려고 해요?',
        questionVi: 'Vì sao bạn định học tiếng Hàn?',
        answer: '한국 친구를 더 많이 사귀려고 한국어를 배워요. 그리고 제 이름을 한국어로 자연스럽게 소개하고 싶어요.',
        grammar: 'V-(으)려고',
        answerVi: 'Tôi học tiếng Hàn để kết bạn với nhiều người Hàn Quốc hơn. Và tôi muốn giới thiệu tên mình một cách tự nhiên bằng tiếng Hàn.',
      },
      {
        level: 'Nâng cao',
        question: '베트남에서 친구를 사귀는 것과 한국에서 외국인 친구를 사귀는 것이 다르다고 생각해요?',
        questionVi: 'Bạn nghĩ việc kết bạn ở Việt Nam và kết bạn với người nước ngoài ở Hàn Quốc có khác nhau không?',
        answer:
          '네, 좀 달라요. 베트남에서는 이름만 말하면 되지만, 한국에서는 국적하고 연락처도 같이 이야기해요. 그래서 처음 만나면 "저는 후엔이라고 하고 베트남 사람이에요"라고 소개해요.',
        grammar: 'N(이)라고 하다',
        answerVi:
          'Vâng, hơi khác. Ở Việt Nam chỉ cần nói tên là được, nhưng ở Hàn Quốc thì phải nói cả quốc tịch và thông tin liên lạc nữa. Vì vậy khi mới gặp, tôi luôn giới thiệu là "Tôi tên là Huyền và tôi là người Việt Nam".',
      },
      {
        level: 'Nâng cao',
        question: '다음 달에 외국인 등록증을 신청하러 가면 어떤 서류가 필요할 것 같아요?',
        questionVi: 'Nếu tháng sau bạn đi đăng ký làm thẻ người nước ngoài thì bạn nghĩ cần giấy tờ gì?',
        answer: '아마 신분증하고 사진이 필요할 것 같아요. 그리고 주소를 증명하려고 서류도 준비해야 할 거예요.',
        grammar: 'V-(으)려고',
        answerVi: 'Chắc là cần giấy tờ tùy thân và ảnh. Và chắc cũng phải chuẩn bị giấy tờ để chứng minh địa chỉ nữa.',
      },
    ],
    grammarSummary: [
      {
        label: 'N(이)라고 하다',
        note: 'patchim có: 이라고 하다, patchim không: 라고 하다. Dùng để giới thiệu/gọi tên người, vật, địa danh (Câu 1, 2, 3, 5, 9).',
      },
      {
        label: 'V-(으)려고',
        note: 'patchim có: 으려고, patchim không: 려고. Diễn tả mục đích, ý định của hành động (Câu 4, 6, 7, 8, 10).',
      },
    ],
    vocabSummary:
      '성/성명 (họ/họ tên), (이름을) 부르다 (gọi tên), 형제들 (anh chị em), 외국인등록증 (thẻ đăng ký người nước ngoài), 주소 (địa chỉ), 연락처 (thông tin liên lạc), 신분증 (giấy tờ tùy thân), 종교 (tôn giáo), 매주 (mỗi tuần), 전화 (điện thoại), 이메일 (email), 친구를 사귀다 (kết bạn), 국적 (quốc tịch).',
  },
  2: {
    intro:
      'Bám sát chủ đề sở thích và 4 ngữ pháp của Bài 2: V-는 것 — danh từ hoá động từ, V-(으)ㄹ 줄 알다[모르다] — biết/không biết cách làm, V-(으)ㄴ N — định ngữ quá khứ, V/A-지 않다 — phủ định dài.',
    items: [
      {
        level: 'Dễ',
        question: '취미가 뭐예요?',
        questionVi: 'Sở thích của bạn là gì?',
        answer: '제 취미는 사진을 찍는 것이에요.',
        grammar: 'V-는 것',
        answerVi: 'Sở thích của tôi là chụp ảnh.',
      },
      {
        level: 'Dễ',
        question: '등산 좋아해요?',
        questionVi: 'Bạn có thích leo núi không?',
        answer: '네, 저는 등산하는 것을 아주 좋아해요. 그런데 등산화가 없어서 새로 사야 해요.',
        grammar: 'V-는 것',
        answerVi: 'Vâng, tôi rất thích leo núi. Nhưng tôi không có giày leo núi nên phải mua mới.',
      },
      {
        level: 'Dễ',
        question: '악기를 연주할 줄 알아요?',
        questionVi: 'Bạn có biết chơi nhạc cụ không?',
        answer: '아니요, 저는 악기를 연주할 줄 몰라요. 그렇지만 노래는 부를 줄 알아요.',
        grammar: 'V-(으)ㄹ 줄 알다[모르다]',
        answerVi: 'Không, tôi không biết chơi nhạc cụ. Nhưng tôi biết hát.',
      },
      {
        level: 'Trung bình',
        question: '동호회에 가입해 봤어요? 어땠어요?',
        questionVi: 'Bạn đã từng tham gia câu lạc bộ nào chưa? Thế nào rồi?',
        answer: '네, 작년에 독서 동호회에 가입했어요. 한 달에 한 번 모이는데 회비가 비싸지 않아서 좋아요.',
        grammar: 'V/A-지 않다',
        answerVi: 'Vâng, năm ngoái tôi đã tham gia câu lạc bộ đọc sách. Mỗi tháng tụ họp một lần, hội phí không đắt nên tôi thấy thích.',
      },
      {
        level: 'Trung bình',
        question: '컴퓨터 게임을 자주 해요?',
        questionVi: 'Bạn có hay chơi game máy tính không?',
        answer: '아니요, 저는 컴퓨터 게임을 별로 좋아하지 않아요. 인터넷을 하는 것은 좋아하지만 게임은 재미없어요.',
        grammar: 'V/A-지 않다',
        answerVi: 'Không, tôi không thích chơi game máy tính lắm. Tôi thích lên mạng nhưng chơi game thì thấy chán.',
      },
      {
        level: 'Trung bình',
        question: '지난주에 찍은 사진 봤어요? 어땠어요?',
        questionVi: 'Bạn đã xem ảnh chụp tuần trước chưa? Thế nào?',
        answer: '네, 봤어요. 친구가 등산할 때 찍은 사진인데 정말 멋있었어요.',
        grammar: 'V-(으)ㄴ N',
        answerVi: 'Vâng, tôi xem rồi. Đó là ảnh bạn tôi chụp lúc đi leo núi, thật sự rất đẹp.',
      },
      {
        level: 'Trung bình',
        question: '라틴 댄스 동호회에 가입하고 싶어요?',
        questionVi: 'Bạn có muốn tham gia câu lạc bộ nhảy Latin không?',
        answer: '네, 사실 라틴 댄스를 배우고 싶어요. 그런데 아직 출 줄 몰라요.',
        grammar: 'V-(으)ㄹ 줄 알다[모르다]',
        answerVi: 'Vâng, thật ra tôi muốn học nhảy Latin. Nhưng tôi vẫn chưa biết nhảy.',
      },
      {
        level: 'Nâng cao',
        question: '왜 그림을 그리는 것을 좋아해요?',
        questionVi: 'Vì sao bạn thích vẽ tranh?',
        answer: '그림을 그리는 것은 스트레스를 풀어 줘서 좋아해요. 그리고 제가 그린 그림을 블로그에 올리는 것도 재미있어요.',
        grammar: 'V-는 것',
        answerVi: 'Vẽ tranh giúp tôi giải tỏa căng thẳng nên tôi thích. Và việc đăng những bức tranh mình vẽ lên blog cũng rất thú vị.',
      },
      {
        level: 'Nâng cao',
        question: '독서하고 낚시 중에서 어느 게 더 조용한 취미예요?',
        questionVi: 'Giữa đọc sách và câu cá, cái nào là sở thích yên tĩnh hơn?',
        answer: '저는 책 읽는 것을 더 좋아해요. 낚시는 아직 할 줄 몰라요.',
        grammar: 'V-(으)ㄹ 줄 알다[모르다]',
        answerVi: 'Tôi thích đọc sách hơn. Câu cá thì tôi vẫn chưa biết làm.',
      },
      {
        level: 'Nâng cao',
        question: '새 동호회에 가입할 때 뭐가 필요해요?',
        questionVi: 'Khi tham gia câu lạc bộ mới thì cần gì?',
        answer: '저는 정확히는 모르지만, 제가 아는 친구가 가입한 동호회는 신청서부터 쓰라고 했어요.',
        grammar: 'V-(으)ㄴ N',
        answerVi: 'Tôi không biết chính xác, nhưng người bạn tôi biết đã tham gia câu lạc bộ đó bảo là phải bắt đầu từ việc viết đơn đăng ký.',
      },
    ],
    grammarSummary: [
      { label: 'V-는 것', note: "Biến động từ thành cụm danh từ ('việc/sự V'), hay đi kèm 좋아하다/싫어하다 (Câu 1, 2, 8, 10)." },
      { label: 'V-(으)ㄹ 줄 알다[모르다]', note: 'Biết/không biết CÁCH làm gì, khác với khả năng chung -(으)ㄹ 수 있다 (Câu 3, 7, 9).' },
      { label: 'V-(으)ㄴ N', note: 'Định ngữ quá khứ — N đã được V, N đã V (Câu 6, 10).' },
      { label: 'V/A-지 않다', note: 'Phủ định dài, trang trọng hơn 안 (Câu 4, 5).' },
    ],
    vocabSummary:
      '취미 (sở thích), 등산/등산화 (leo núi/giày leo núi), 악기 (nhạc cụ), 동호회 (câu lạc bộ), 회비 (hội phí), 라틴 댄스 (nhảy Latin), 컴퓨터 게임 (chơi game máy tính), 인터넷을 하다 (lên mạng), 그림을 그리다 (vẽ tranh), 블로그 (blog), 독서 (đọc sách), 낚시 (câu cá).',
  },
  3: {
    intro:
      'Bám sát chủ đề trải nghiệm văn hoá – giải trí và 5 ngữ pháp của Bài 3: V-아/어 보다, N 동안, A/V-는데 (bối cảnh), N인데, V-(으)ㄹ N (định ngữ tương lai).',
    items: [
      {
        level: 'Dễ',
        question: '콘서트에 가 봤어요?',
        questionVi: 'Bạn đã đi xem concert chưa?',
        answer: '네, 작년에 재즈 콘서트에 가 봤어요. 정말 좋았어요.',
        grammar: 'V-아/어 보다',
        answerVi: 'Vâng, năm ngoái tôi đã đi xem concert nhạc jazz rồi. Thực sự rất hay.',
      },
      {
        level: 'Dễ',
        question: '뮤지컬을 좋아해요?',
        questionVi: 'Bạn có thích nhạc kịch không?',
        answer: '네, 저는 공연을 좋아하는데 아직 뮤지컬은 못 봤어요.',
        grammar: 'A/V-는데 (bối cảnh)',
        answerVi: 'Vâng, tôi thích xem biểu diễn, nhưng vẫn chưa xem được nhạc kịch lần nào.',
      },
      {
        level: 'Dễ',
        question: '미술관에 가 봤어요?',
        questionVi: 'Bạn đã đến bảo tàng mỹ thuật chưa?',
        answer: '아니요, 아직 안 가 봤어요. 그렇지만 박물관은 가 봤어요.',
        grammar: 'V-아/어 보다',
        answerVi: 'Chưa, tôi vẫn chưa đến. Nhưng tôi đã đến bảo tàng (lịch sử) rồi.',
      },
      {
        level: 'Trung bình',
        question: '축제에 참가해 봤어요? 어땠어요?',
        questionVi: 'Bạn đã từng tham gia lễ hội chưa? Thế nào rồi?',
        answer: '네, 작년 축제 동안 불꽃놀이를 봤는데 정말 멋있었어요.',
        grammar: 'N 동안',
        answerVi: 'Vâng, trong suốt lễ hội năm ngoái tôi đã xem bắn pháo hoa, thực sự rất đẹp.',
      },
      {
        level: 'Trung bình',
        question: '오늘 시간 있는데 같이 전시회에 갈래요?',
        questionVi: 'Hôm nay tôi có thời gian đấy, bạn có muốn đi triển lãm cùng không?',
        answer: '좋아요! 사실 저도 오늘 시간이 있는데 뭘 할지 몰랐어요.',
        grammar: 'N인데',
        answerVi: 'Được đó! Thật ra hôm nay tôi cũng có thời gian mà chưa biết làm gì.',
      },
      {
        level: 'Trung bình',
        question: '어떤 공연을 보고 싶어요?',
        questionVi: 'Bạn muốn xem buổi biểu diễn nào?',
        answer: '저는 다음 달에 열릴 콘서트를 보고 싶어요. 제가 제일 좋아하는 가수가 나와요.',
        grammar: 'V-(으)ㄹ N',
        answerVi: 'Tôi muốn xem concert sẽ được tổ chức vào tháng sau. Ca sĩ tôi thích nhất sẽ biểu diễn.',
      },
      {
        level: 'Trung bình',
        question: '영화제에 갈 거예요?',
        questionVi: 'Bạn sẽ đi liên hoan phim chứ?',
        answer: '네, 이번 영화제에 가는데 볼 영화를 아직 못 골랐어요.',
        grammar: 'A/V-는데 (bối cảnh)',
        answerVi: 'Vâng, tôi sẽ đi liên hoan phim lần này, nhưng vẫn chưa chọn được phim để xem.',
      },
      {
        level: 'Nâng cao',
        question: '왜 그 가수의 콘서트에 꼭 가고 싶어요?',
        questionVi: 'Vì sao bạn nhất định muốn đi concert của ca sĩ đó?',
        answer: '사실 어릴 때부터 팬이었는데 아직 한 번도 콘서트에 못 가 봤어요. 이번에는 꼭 가 보고 싶어요.',
        grammar: 'V-아/어 보다',
        answerVi: 'Thật ra tôi đã là fan từ nhỏ nhưng chưa từng đi concert lần nào. Lần này tôi thực sự muốn thử đi xem.',
      },
      {
        level: 'Nâng cao',
        question: '미술관 전시회하고 박물관 전시 중에서 뭐가 더 좋아요?',
        questionVi: 'Giữa triển lãm ở bảo tàng mỹ thuật và trưng bày ở bảo tàng, bạn thích cái nào hơn?',
        answer: '저는 방학 동안 미술관에 자주 가 봐서 미술관 전시회를 더 좋아해요.',
        grammar: 'N 동안',
        answerVi: 'Vì trong suốt kỳ nghỉ tôi hay đến bảo tàng mỹ thuật nên tôi thích triển lãm ở đó hơn.',
      },
      {
        level: 'Nâng cao',
        question: '다음 축제 동안 어떤 공연이 있을 것 같아요?',
        questionVi: 'Bạn nghĩ trong lễ hội tới sẽ có buổi biểu diễn nào?',
        answer: '다음 축제 동안 열릴 공연은 아마 콘서트하고 불꽃놀이일 거예요.',
        grammar: 'V-(으)ㄹ N',
        answerVi: 'Buổi biểu diễn sẽ được tổ chức trong lễ hội tới chắc là concert và bắn pháo hoa.',
      },
    ],
    grammarSummary: [
      { label: 'V-아/어 보다', note: 'Thử làm gì / (quá khứ) đã từng làm (Câu 1, 3, 8).' },
      { label: 'N 동안', note: 'Trong suốt khoảng thời gian N (Câu 4, 9, 10).' },
      { label: 'A/V-는데 (bối cảnh)', note: 'Nêu bối cảnh trước khi hỏi/đề nghị (Câu 2, 7).' },
      { label: 'N인데', note: 'Dạng danh từ của -는데, nêu bối cảnh liên quan đến danh từ (Câu 5).' },
      { label: 'V-(으)ㄹ N', note: 'Định ngữ tương lai — N sẽ được V (Câu 6, 10).' },
    ],
    vocabSummary:
      '공연 (buổi diễn), 전시회 (triển lãm), 뮤지컬 (nhạc kịch), 영화제 (liên hoan phim), 재즈 (nhạc jazz), 박물관 (bảo tàng), 축제 (lễ hội), 콘서트 (concert), 미술관 (bảo tàng nghệ thuật), 불꽃놀이 (bắn pháo hoa), 감독 (đạo diễn).',
  },
  4: {
    intro:
      'Bám sát chủ đề mua sắm quần áo và 3 ngữ pháp của Bài 4: A/V-는/(으)ㄴ 것 같다 (hiện tại), N보다, A/V-았으면/었으면 좋겠다.',
    items: [
      {
        level: 'Dễ',
        question: '이 티셔츠 어때요?',
        questionVi: 'Cái áo phông này thế nào?',
        answer: '색깔은 예쁜데 사이즈가 좀 작은 것 같아요.',
        grammar: 'A/V-는/(으)ㄴ 것 같다',
        answerVi: 'Màu thì đẹp nhưng hình như size hơi nhỏ.',
      },
      {
        level: 'Dễ',
        question: '이 바지가 저 바지보다 비싸요?',
        questionVi: 'Cái quần này có đắt hơn cái quần kia không?',
        answer: '네, 이 청바지가 저것보다 조금 더 비싸요.',
        grammar: 'N보다',
        answerVi: 'Vâng, cái quần jean này đắt hơn cái kia một chút.',
      },
      {
        level: 'Dễ',
        question: '그 신발 마음에 들어요?',
        questionVi: 'Bạn có ưng đôi giày đó không?',
        answer: '네, 디자인이 마음에 드는데 굽이 좀 높은 것 같아요.',
        grammar: 'A/V-는/(으)ㄴ 것 같다',
        answerVi: 'Vâng, tôi ưng kiểu dáng, nhưng hình như gót hơi cao.',
      },
      {
        level: 'Trung bình',
        question: '어떤 옷을 사고 싶어요?',
        questionVi: 'Bạn muốn mua loại quần áo nào?',
        answer: '저는 좀 밝은 색 스웨터가 있었으면 좋겠어요. 요즘 유행하는 디자인으로요.',
        grammar: 'A/V-았으면/었으면 좋겠다',
        answerVi: 'Tôi ước gì có một cái áo len màu sáng một chút. Kiểu đang thịnh hành ấy.',
      },
      {
        level: 'Trung bình',
        question: '넥타이하고 스카프 중에서 뭐가 더 잘 어울려요?',
        questionVi: 'Giữa cà vạt và khăn quàng cổ, cái nào hợp với bạn hơn?',
        answer: '저는 스카프가 넥타이보다 저한테 더 잘 어울리는 것 같아요.',
        grammar: 'N보다',
        answerVi: 'Tôi thấy khăn quàng cổ hợp với tôi hơn cà vạt.',
      },
      {
        level: 'Trung bình',
        question: '옷을 살 때 뭐가 제일 중요해요?',
        questionVi: 'Khi mua quần áo thì điều gì quan trọng nhất với bạn?',
        answer: '저는 가격이 너무 비싸지 않았으면 좋겠어요. 그리고 사이즈가 잘 맞으면 좋겠어요.',
        grammar: 'A/V-았으면/었으면 좋겠다',
        answerVi: 'Tôi mong là giá đừng quá đắt. Và mong là size vừa vặn.',
      },
      {
        level: 'Trung bình',
        question: '이 장갑 좀 크지 않아요?',
        questionVi: 'Đôi găng tay này không phải hơi to à?',
        answer: '네, 좀 큰 것 같아요. 교환할 수 있는지 물어봐야겠어요.',
        grammar: 'A/V-는/(으)ㄴ 것 같다',
        answerVi: 'Vâng, hình như hơi to. Chắc phải hỏi xem có đổi được không.',
      },
      {
        level: 'Nâng cao',
        question: '왜 이 양복을 골랐어요?',
        questionVi: 'Vì sao bạn chọn bộ vest này?',
        answer: '다른 것보다 색깔이 더 어둡지 않고 저한테 잘 어울려서 골랐어요.',
        grammar: 'N보다',
        answerVi: 'Vì so với những cái khác, màu không tối quá và hợp với tôi nên tôi chọn.',
      },
      {
        level: 'Nâng cao',
        question: '환불하는 것하고 교환하는 것 중에서 뭐가 더 나을 것 같아요?',
        questionVi: 'Giữa hoàn tiền và đổi hàng, bạn nghĩ cái nào tốt hơn?',
        answer: '마음에 안 드는 색깔이니까 환불하는 게 더 나을 것 같아요.',
        grammar: 'A/V-는/(으)ㄴ 것 같다',
        answerVi: 'Vì màu không vừa ý nên tôi nghĩ hoàn tiền có vẻ tốt hơn.',
      },
      {
        level: 'Nâng cao',
        question: '다음에 옷을 살 때는 어떻게 하고 싶어요?',
        questionVi: 'Lần sau mua quần áo bạn muốn làm thế nào?',
        answer: '다음에는 사이즈를 안 틀렸으면 좋겠어요. 그리고 환불하지 않아도 되게 미리 잘 입어 봤으면 좋겠어요.',
        grammar: 'A/V-았으면/었으면 좋겠다',
        answerVi: 'Lần sau tôi mong đừng chọn sai size nữa. Và mong là thử đồ kỹ trước để khỏi phải hoàn trả.',
      },
    ],
    grammarSummary: [
      { label: 'A/V-는/(으)ㄴ 것 같다 (hiện tại)', note: 'Suy đoán nhẹ nhàng về hiện tại — hình như, có vẻ (Câu 1, 3, 7, 9).' },
      { label: 'N보다', note: 'So sánh hơn kém — (so với) N thì... (Câu 2, 5, 8).' },
      { label: 'A/V-았으면/었으면 좋겠다', note: 'Ước muốn, mong điều trái với thực tế (Câu 4, 6, 10).' },
    ],
    vocabSummary:
      '청바지 (quần jean), 스웨터 (áo len), 넥타이 (cà vạt), 스카프 (khăn quàng cổ), 디자인 (thiết kế), 유행하다 (hợp thời trang), 사이즈 (kích cỡ), 마음에 들다 (vừa ý), 환불하다 (hoàn tiền), 교환하다 (đổi hàng), 굽이 높다 (gót giày cao), 양복 (bộ vest), 장갑 (găng tay).',
  },
  5: {
    intro:
      'Bám sát chủ đề du lịch và 4 ngữ pháp của Bài 5: V/A-(으)ㄹ까요?, A/V-(으)ㄹ 거예요 (suy đoán), A/V-(으)니까, V-고 나서.',
    items: [
      {
        level: 'Dễ',
        question: '이번 방학에 여행 가고 싶어요?',
        questionVi: 'Kỳ nghỉ này bạn có muốn đi du lịch không?',
        answer: '네, 가고 싶어요. 그런데 어디로 갈까요? 아직 못 정했어요.',
        grammar: 'V/A-(으)ㄹ까요?',
        answerVi: 'Có chứ. Nhưng nên đi đâu nhỉ? Tôi vẫn chưa quyết được.',
      },
      {
        level: 'Dễ',
        question: '경복궁에 가 봤어요?',
        questionVi: 'Bạn đã đến cung Gyeongbok chưa?',
        answer: '아직 안 가 봤는데 정말 아름다울 거예요. 사진에서 많이 봤어요.',
        grammar: 'A/V-(으)ㄹ 거예요',
        answerVi: 'Vẫn chưa, nhưng chắc là sẽ rất đẹp. Tôi xem ảnh nhiều rồi.',
      },
      {
        level: 'Dễ',
        question: '온천에 가 봤어요?',
        questionVi: 'Bạn đã đi suối nước nóng chưa?',
        answer: '네, 가 봤어요. 겨울이니까 온천에 가면 정말 좋아요.',
        grammar: 'A/V-(으)니까',
        answerVi: 'Rồi. Vì là mùa đông nên đi suối nước nóng thực sự rất thích.',
      },
      {
        level: 'Trung bình',
        question: '여행 갔다 온 경험이 있어요? 어땠어요?',
        questionVi: 'Bạn có kinh nghiệm đi du lịch chưa? Thế nào rồi?',
        answer: '네, 작년에 제주도에 갔다 왔어요. 숙소를 예약하고 나서 항공권을 샀는데 좀 힘들었어요.',
        grammar: 'V-고 나서',
        answerVi: 'Vâng, năm ngoái tôi đã đi đảo Jeju. Sau khi đặt chỗ ở xong tôi mới mua vé máy bay, hơi vất vả một chút.',
      },
      {
        level: 'Trung bình',
        question: '왕복 항공권하고 편도 항공권 중에서 뭐가 나아요?',
        questionVi: 'Giữa vé khứ hồi và vé một chiều, cái nào tốt hơn?',
        answer: '여행 일정이 정해져 있으니까 저는 왕복 항공권이 더 편해요.',
        grammar: 'A/V-(으)니까',
        answerVi: 'Vì lịch trình du lịch đã cố định rồi nên tôi thấy vé khứ hồi tiện hơn.',
      },
      {
        level: 'Trung bình',
        question: '숙소를 어디로 정할까요?',
        questionVi: 'Chúng ta nên chọn chỗ ở đâu nhỉ?',
        answer: '한옥에서 자 볼까요? 특별한 경험이 될 것 같아요.',
        grammar: 'V/A-(으)ㄹ까요?',
        answerVi: 'Hay là mình thử ngủ ở nhà Hanok nhỉ? Chắc sẽ là một trải nghiệm đặc biệt.',
      },
      {
        level: 'Trung bình',
        question: '여행 가기 전에 뭐부터 해요?',
        questionVi: 'Trước khi đi du lịch bạn làm gì trước?',
        answer: '저는 항공권을 예약하고 나서 숙소를 찾아봐요.',
        grammar: 'V-고 나서',
        answerVi: 'Tôi đặt vé máy bay xong rồi mới tìm chỗ ở.',
      },
      {
        level: 'Nâng cao',
        question: '왜 가이드 여행 상품을 추천해요?',
        questionVi: 'Vì sao bạn giới thiệu tour có hướng dẫn viên?',
        answer: '한국말을 아직 잘 못하니까 가이드가 있는 여행 상품이 더 편할 거예요.',
        grammar: 'A/V-(으)니까',
        answerVi: 'Vì vẫn chưa giỏi tiếng Hàn nên có hướng dẫn viên sẽ tiện hơn.',
      },
      {
        level: 'Nâng cao',
        question: '봄하고 가을 중에서 언제 한옥마을 여행이 더 좋을 거예요?',
        questionVi: 'Giữa mùa xuân và mùa thu, đi du lịch làng Hanok vào lúc nào sẽ đẹp hơn?',
        answer: '벚꽃이 피니까 아마 봄에 가는 게 더 예쁠 거예요.',
        grammar: 'A/V-(으)ㄹ 거예요',
        answerVi: 'Vì hoa anh đào nở nên chắc đi vào mùa xuân sẽ đẹp hơn.',
      },
      {
        level: 'Nâng cao',
        question: '이번 여행 일정이 어떻게 돼요?',
        questionVi: 'Lịch trình chuyến đi lần này thế nào?',
        answer: '경복궁을 구경하고 나서 한옥마을에 갈까 해요. 그러고 나서 저녁에는 시장에 갈 거예요.',
        grammar: 'V-고 나서',
        answerVi: 'Sau khi tham quan cung Gyeongbok xong tôi định đi làng Hanok. Sau đó buổi tối tôi sẽ đi chợ.',
      },
    ],
    grammarSummary: [
      { label: 'V/A-(으)ㄹ까요?', note: 'Hỏi ý kiến/tự hỏi bản thân trước khi quyết định (Câu 1, 6).' },
      { label: 'A/V-(으)ㄹ 거예요 (suy đoán)', note: 'Phỏng đoán, không hẳn là dự định cá nhân (Câu 2, 9).' },
      { label: 'A/V-(으)니까', note: 'Nêu lý do, bắt buộc dùng trước câu mệnh lệnh/đề nghị/rủ rê (Câu 3, 5, 8).' },
      { label: 'V-고 나서', note: 'Hành động trước hoàn tất xong rồi mới đến hành động sau (Câu 4, 7, 10).' },
    ],
    vocabSummary:
      '여행 (du lịch), 온천 (suối nước nóng), 한옥마을 (làng Hanok), 경복궁 (cung Gyeongbok), 숙소 (nơi lưu trú), 항공권 (vé máy bay), 왕복/편도 (khứ hồi/một chiều), 일정 (lịch trình), 가이드 (hướng dẫn viên), 벚꽃 (hoa anh đào).',
  },
  6: {
    intro:
      'Bám sát chủ đề bưu điện – ngân hàng và 4 ngữ pháp của Bài 6: N(으)로, N(이)라서, V-(으)면 되다, V-(으)ㄴ 것 같다 (quá khứ).',
    items: [
      {
        level: 'Dễ',
        question: '이 소포를 어떻게 보낼 거예요?',
        questionVi: 'Bạn sẽ gửi kiện hàng này bằng cách nào?',
        answer: '비행기로 보낼 거예요. 배로 보내는 것보다 빠르니까요.',
        grammar: 'N(으)로',
        answerVi: 'Tôi sẽ gửi bằng máy bay. Vì nhanh hơn gửi bằng tàu biển.',
      },
      {
        level: 'Dễ',
        question: '은행에서 환전하려면 어떻게 해요?',
        questionVi: 'Muốn đổi ngoại tệ ở ngân hàng thì làm thế nào?',
        answer: '신분증만 가지고 가면 돼요. 어렵지 않아요.',
        grammar: 'V-(으)면 되다',
        answerVi: 'Chỉ cần mang giấy tờ tùy thân đi là được. Không khó đâu.',
      },
      {
        level: 'Dễ',
        question: '택배가 늦게 왔어요?',
        questionVi: 'Kiện hàng giao đến trễ à?',
        answer: '네, 명절이라서 택배가 평소보다 늦게 왔어요.',
        grammar: 'N(이)라서',
        answerVi: 'Vâng, vì là dịp lễ nên hàng giao trễ hơn bình thường.',
      },
      {
        level: 'Trung bình',
        question: '소포를 보낸 적 있어요? 어땠어요?',
        questionVi: 'Bạn đã từng gửi kiện hàng chưa? Thế nào rồi?',
        answer: '네, 지난주에 소포를 보냈는데 무게를 저울에 안 재서 요금을 잘못 낸 것 같아요.',
        grammar: 'V-(으)ㄴ 것 같다 (quá khứ)',
        answerVi: 'Vâng, tuần trước tôi đã gửi kiện hàng, nhưng hình như vì không cân trọng lượng nên tôi đã trả sai phí.',
      },
      {
        level: 'Trung bình',
        question: '돈을 어떻게 보내는 게 편해요?',
        questionVi: 'Gửi tiền bằng cách nào thì tiện hơn với bạn?',
        answer: '저는 현금 대신 계좌로 돈을 보내는 게 더 편해요.',
        grammar: 'N(으)로',
        answerVi: 'Tôi thấy gửi tiền qua tài khoản tiện hơn là dùng tiền mặt.',
      },
      {
        level: 'Trung bình',
        question: '소포를 포장할 때 뭐가 필요해요?',
        questionVi: 'Khi đóng gói kiện hàng thì cần gì?',
        answer: '상자에 물건을 잘 넣고 테이프로 붙이면 돼요. 그다음에 주소만 쓰면 돼요.',
        grammar: 'V-(으)면 되다',
        answerVi: 'Chỉ cần cho đồ vào hộp cẩn thận rồi dán băng dính là được. Sau đó chỉ cần viết địa chỉ thôi.',
      },
      {
        level: 'Trung bình',
        question: '오늘 환율이 왜 이렇게 높아요?',
        questionVi: 'Sao hôm nay tỷ giá cao thế?',
        answer: '주말이라서 환전소가 문을 닫아서 그런지 환율이 더 높은 것 같아요.',
        grammar: 'N(이)라서',
        answerVi: 'Chắc vì là cuối tuần nên tiệm đổi tiền đóng cửa nên tỷ giá cao hơn.',
      },
      {
        level: 'Nâng cao',
        question: '왜 신용카드보다 현금 카드를 더 자주 써요?',
        questionVi: 'Vì sao bạn dùng thẻ ghi nợ nhiều hơn thẻ tín dụng?',
        answer: '저는 학생이라서 신용카드를 만들기 어려워요. 그래서 현금 카드를 더 자주 써요.',
        grammar: 'N(이)라서',
        answerVi: 'Vì tôi là sinh viên nên khó làm thẻ tín dụng. Vì vậy tôi dùng thẻ ghi nợ nhiều hơn.',
      },
      {
        level: 'Nâng cao',
        question: '택배로 보내는 것하고 우편으로 보내는 것 중에서 뭐가 더 간단해요?',
        questionVi: 'Giữa gửi bằng chuyển phát nhanh và gửi bằng bưu điện thông thường, cái nào đơn giản hơn?',
        answer: '택배는 인터넷으로 신청만 하면 되니까 택배가 더 간단한 것 같아요.',
        grammar: 'V-(으)면 되다',
        answerVi: 'Vì chuyển phát nhanh chỉ cần đăng ký qua mạng là được nên tôi thấy nó đơn giản hơn.',
      },
      {
        level: 'Nâng cao',
        question: '이 소포가 왜 아직 안 왔을까요?',
        questionVi: 'Sao kiện hàng này vẫn chưa đến nhỉ?',
        answer: '주소를 잘못 쓴 것 같아요. 아니면 세관에서 오래 걸리는 것 같아요.',
        grammar: 'V-(으)ㄴ 것 같다 (quá khứ)',
        answerVi: 'Hình như đã viết sai địa chỉ. Hoặc có lẽ đang mất nhiều thời gian ở hải quan.',
      },
    ],
    grammarSummary: [
      { label: 'N(으)로', note: 'Phương tiện/phương pháp/chất liệu thực hiện hành động (Câu 1, 5).' },
      { label: 'N(이)라서', note: 'Lý do khách quan xuất phát từ danh từ, không dùng ở câu mệnh lệnh/đề nghị (Câu 3, 7, 8).' },
      { label: 'V-(으)면 되다', note: 'Chỉ cần làm gì đó là đủ để đạt mục đích (Câu 2, 6, 9).' },
      { label: 'V-(으)ㄴ 것 같다 (quá khứ)', note: 'Suy đoán về việc đã xảy ra, dựa trên dấu hiệu hiện tại (Câu 4, 10).' },
    ],
    vocabSummary:
      '택배 (chuyển hàng), 환율 (tỷ giá hối đoái), 환전 (đổi ngoại tệ), 소포를 포장하다 (gói bưu phẩm), 저울 (cân), 신용 카드/현금 카드 (thẻ tín dụng/thẻ ghi nợ), 우편 (bưu chính), 송금 (chuyển tiền), 도장 (con dấu).',
  },
  7: {
    intro:
      'Bám sát chủ đề chỉ đường và 5 ngữ pháp của Bài 7: V/A-(으)ㄹ 것 같다 (tương lai), V-는지 알다[모르다], N인지 알다[모르다], V-(으)려면, V-다가.',
    items: [
      {
        level: 'Dễ',
        question: '지하철역에 가려면 어떻게 가요?',
        questionVi: 'Muốn đến ga tàu điện ngầm thì đi thế nào?',
        answer: '이 길로 쭉 직진하면 돼요. 그런데 지하철역에 가려면 사거리에서 왼쪽으로 돌아가야 해요.',
        grammar: 'V-(으)려면',
        answerVi: 'Cứ đi thẳng theo đường này là được. Nhưng muốn đến ga thì phải rẽ trái ở ngã tư.',
      },
      {
        level: 'Dễ',
        question: '여기서 한옥마을이 얼마나 먼지 아세요?',
        questionVi: 'Bạn có biết từ đây đến làng Hanok bao xa không?',
        answer: '정확히 얼마나 먼지는 몰라요. 그런데 걸어서 15분쯤 걸릴 거예요.',
        grammar: 'N인지 알다[모르다]',
        answerVi: 'Tôi không biết chính xác là bao xa. Nhưng chắc đi bộ mất khoảng 15 phút.',
      },
      {
        level: 'Dễ',
        question: '버스 정류장이 어디에 있는지 아세요?',
        questionVi: 'Bạn có biết trạm xe buýt ở đâu không?',
        answer: '네, 저기 육교 밑에 버스 정류장이 있는지 알아요. 자주 이용해요.',
        grammar: 'V-는지 알다[모르다]',
        answerVi: 'Có, tôi biết có trạm xe buýt ở dưới cầu vượt đằng kia. Tôi hay dùng nó.',
      },
      {
        level: 'Trung bình',
        question: '길을 잃어버린 적 있어요?',
        questionVi: 'Bạn đã từng bị lạc đường chưa?',
        answer: '네, 걸어가다가 길을 잃어버려서 표지판을 보고 겨우 찾아갔어요.',
        grammar: 'V-다가',
        answerVi: 'Có, đang đi bộ thì tôi bị lạc đường, phải nhìn biển chỉ dẫn mãi mới tìm được.',
      },
      {
        level: 'Trung bình',
        question: '지금 사거리 쪽에 가면 길이 막힐까요?',
        questionVi: 'Bây giờ đi về phía ngã tư thì có bị kẹt xe không?',
        answer: '네, 지금 시간에는 길이 많이 막힐 것 같아요. 지하철을 타는 게 나을 거예요.',
        grammar: 'V/A-(으)ㄹ 것 같다 (tương lai)',
        answerVi: 'Vâng, giờ này chắc sẽ kẹt xe nhiều. Đi tàu điện ngầm sẽ tốt hơn.',
      },
      {
        level: 'Trung bình',
        question: '한옥마을에 빨리 가려면 어떻게 해야 돼요?',
        questionVi: 'Muốn đến làng Hanok nhanh thì phải làm sao?',
        answer: '빨리 가려면 택시를 타는 게 좋아요. 버스는 시간이 더 걸려요.',
        grammar: 'V-(으)려면',
        answerVi: 'Muốn đi nhanh thì nên đi taxi. Xe buýt sẽ mất thời gian hơn.',
      },
      {
        level: 'Trung bình',
        question: '지하철역까지 어떻게 갔어요?',
        questionVi: 'Bạn đã đến ga tàu điện ngầm bằng cách nào?',
        answer: '버스를 타고 가다가 사람이 너무 많아서 중간에 내려서 걸어갔어요.',
        grammar: 'V-다가',
        answerVi: 'Tôi đang đi xe buýt thì vì quá đông người nên xuống giữa đường rồi đi bộ.',
      },
      {
        level: 'Nâng cao',
        question: '왜 표지판을 봤는데도 길을 못 찾았어요?',
        questionVi: 'Vì sao xem biển chỉ dẫn rồi mà vẫn không tìm được đường?',
        answer: '표지판에 있는 이름이 무슨 뜻인지 몰라서 계속 헷갈렸어요.',
        grammar: 'N인지 알다[모르다]',
        answerVi: 'Vì tôi không biết tên trên biển chỉ dẫn nghĩa là gì nên cứ bị nhầm mãi.',
      },
      {
        level: 'Nâng cao',
        question: '육교로 건너는 것하고 횡단보도로 건너는 것 중에서 뭐가 더 빠를 것 같아요?',
        questionVi: 'Giữa băng qua bằng cầu vượt và bằng vạch qua đường, cách nào nhanh hơn?',
        answer: '지금 신호가 막 바뀌었으니까 횡단보도로 건너는 게 더 빠를 것 같아요.',
        grammar: 'V/A-(으)ㄹ 것 같다 (tương lai)',
        answerVi: 'Vì đèn vừa mới chuyển nên chắc băng qua bằng vạch qua đường sẽ nhanh hơn.',
      },
      {
        level: 'Nâng cao',
        question: '이 근처에 지하도가 있는지 아세요?',
        questionVi: 'Bạn có biết gần đây có đường hầm không?',
        answer: '저도 이 동네가 처음이라서 지하도가 어디에 있는지 몰라요. 표지판을 같이 찾아볼까요?',
        grammar: 'V-는지 알다[모르다]',
        answerVi: 'Tôi cũng lần đầu đến khu này nên không biết đường hầm ở đâu. Hay là mình cùng tìm biển chỉ dẫn nhé?',
      },
    ],
    grammarSummary: [
      { label: 'V/A-(으)ㄹ 것 같다 (tương lai)', note: 'Phỏng đoán về tương lai (Câu 5, 9).' },
      { label: 'V-는지 알다[모르다]', note: 'Biết/không biết (nghi vấn gián tiếp với động từ) (Câu 3, 8, 10).' },
      { label: 'N 인지 알다[모르다]', note: 'Biết/không biết (nghi vấn gián tiếp với danh từ) (Câu 2).' },
      { label: 'V-(으)려면', note: 'Nếu muốn V thì (vế sau thường là lời khuyên/hướng dẫn) (Câu 1, 6).' },
      { label: 'V-다가', note: 'Đang làm gì thì bị gián đoạn giữa chừng (Câu 4, 7).' },
    ],
    vocabSummary:
      '횡단보도 (vạch qua đường), 사거리 (ngã tư), 직진하다 (đi thẳng), 육교 (cầu vượt), 신호등 (đèn giao thông), 좌회전하다/우회전하다 (rẽ trái/rẽ phải), 지하철역 (ga tàu điện ngầm), 표지판 (biển chỉ dẫn), 길이 막히다 (tắc đường).',
  },
  8: {
    intro:
      'Bám sát chủ đề cảm xúc và 4 ngữ pháp của Bài 8: V/A-겠-, N때문에, V-아/어 버리다, V/A-(으)ㄹ 때.',
    items: [
      {
        level: 'Dễ',
        question: '언제 제일 긴장돼요?',
        questionVi: 'Khi nào bạn căng thẳng nhất?',
        answer: '저는 시험 볼 때 제일 긴장돼요.',
        grammar: 'V/A-(으)ㄹ 때',
        answerVi: 'Tôi căng thẳng nhất khi thi.',
      },
      {
        level: 'Dễ',
        question: '오늘 왜 기분이 안 좋아요?',
        questionVi: 'Sao hôm nay tâm trạng bạn không tốt vậy?',
        answer: '교통사고 때문에 회사에 늦게 도착해서 기분이 안 좋아요.',
        grammar: 'N때문에',
        answerVi: 'Vì tai nạn giao thông nên tôi đến công ty trễ, thấy khó chịu.',
      },
      {
        level: 'Dễ',
        question: '지갑을 잃어버린 적 있어요?',
        questionVi: 'Bạn đã từng làm mất ví chưa?',
        answer: '네, 예전에 지갑을 잃어버렸어요. 그때 정말 속상했어요.',
        grammar: 'V-아/어 버리다',
        answerVi: 'Có, trước đây tôi từng làm mất ví. Lúc đó tôi buồn lắm.',
      },
      {
        level: 'Trung bình',
        question: '친구가 넘어져서 다쳤다고 하는데 어때요?',
        questionVi: 'Nghe nói bạn của bạn bị ngã và bị thương, bạn thấy sao?',
        answer: '많이 아프겠어요. 병원에 가 봤어요?',
        grammar: 'V/A-겠-',
        answerVi: 'Chắc là đau lắm. Bạn ấy đã đi khám chưa?',
      },
      {
        level: 'Trung bình',
        question: '스트레스를 받을 때 어떻게 풀어요?',
        questionVi: 'Khi bị căng thẳng bạn giải tỏa thế nào?',
        answer: '저는 스트레스를 받으면 그냥 다 잊어버리려고 노래를 크게 들어요.',
        grammar: 'V-아/어 버리다',
        answerVi: 'Khi bị căng thẳng tôi cứ nghe nhạc thật to để quên hết đi.',
      },
      {
        level: 'Trung bình',
        question: '노트북이 고장이 나서 걱정돼요?',
        questionVi: 'Laptop hỏng nên bạn lo lắng à?',
        answer: '네, 노트북 고장 때문에 숙제를 못 끝내서 정말 걱정돼요.',
        grammar: 'N때문에',
        answerVi: 'Vâng, vì laptop hỏng nên tôi không làm xong bài tập, thực sự rất lo.',
      },
      {
        level: 'Trung bình',
        question: '창피했던 적 있어요?',
        questionVi: 'Bạn đã từng thấy xấu hổ chưa?',
        answer: '네, 사람들 앞에서 발표할 때 실수해서 정말 창피했어요.',
        grammar: 'V/A-(으)ㄹ 때',
        answerVi: 'Có, khi thuyết trình trước mọi người tôi bị sai nên thực sự xấu hổ.',
      },
      {
        level: 'Nâng cao',
        question: '왜 요즘 그렇게 외로워해요?',
        questionVi: 'Sao dạo này bạn cô đơn vậy?',
        answer: '가족들하고 멀리 떨어져 있기 때문에 가끔 정말 외로워요.',
        grammar: 'N때문에',
        answerVi: 'Vì sống xa gia đình nên thỉnh thoảng tôi thấy thực sự cô đơn.',
      },
      {
        level: 'Nâng cao',
        question: '시험에 떨어졌다고 하면 친구 기분이 어떻겠어요?',
        questionVi: 'Nếu nghe tin thi trượt thì tâm trạng bạn ấy sẽ thế nào?',
        answer: '정말 속상하겠어요. 열심히 준비했을 텐데요.',
        grammar: 'V/A-겠-',
        answerVi: 'Chắc là buồn lắm. Vì bạn ấy đã chuẩn bị chăm chỉ mà.',
      },
      {
        level: 'Nâng cao',
        question: '약속을 잊어버려서 친구를 못 만났는데 어떻게 할까요?',
        questionVi: 'Vì quên mất cuộc hẹn nên không gặp được bạn, giờ nên làm sao?',
        answer: '미안하다고 문자를 보내 버리는 게 좋을 것 같아요. 그리고 다시 약속을 잡아요.',
        grammar: 'V-아/어 버리다',
        answerVi: 'Chắc nên nhắn tin xin lỗi luôn cho xong. Rồi hẹn lại lần khác.',
      },
    ],
    grammarSummary: [
      { label: 'V/A-겠-', note: 'Phỏng đoán dựa trên tình huống trước mắt tại thời điểm nói (Câu 4, 9).' },
      { label: 'N 때문에', note: 'Nguyên nhân/lý do khách quan, hơi tiêu cực (Câu 2, 6, 8).' },
      { label: 'V-아/어 버리다', note: 'Hành động hoàn tất kèm cảm xúc tiếc nuối hoặc nhẹ nhõm (Câu 3, 5, 10).' },
      { label: 'V/A-(으)ㄹ 때', note: 'Chỉ thời điểm mà hành động/trạng thái xảy ra (Câu 1, 7).' },
    ],
    vocabSummary:
      '속상하다 (buồn lòng), 긴장되다 (căng thẳng), 잃어버리다 (làm mất), 걱정되다 (lo lắng), 창피하다 (xấu hổ), 화가 나다 (tức giận), 스트레스를 받다/풀다 (bị căng thẳng/giải tỏa căng thẳng), 고장이 나다 (bị hỏng), 외롭다 (cô đơn).',
  },
  9: {
    intro:
      'Bám sát chủ đề gọi điện – dịch vụ khách hàng và 5 ngữ pháp của Bài 9: A/V-는데요, V-는 중이다, N중이다, A/V-나요?/은가요?/인가요?, N밖에.',
    items: [
      {
        level: 'Dễ',
        question: '무슨 일로 전화하셨어요?',
        questionVi: 'Bạn gọi điện vì việc gì vậy?',
        answer: '문의할 게 있는데요. 서비스 센터 전화번호를 알고 싶어요.',
        grammar: 'A/V-는데요',
        answerVi: 'Tôi có điều muốn hỏi ạ. Tôi muốn biết số điện thoại trung tâm dịch vụ.',
      },
      {
        level: 'Dễ',
        question: '지금 통화 가능해요?',
        questionVi: 'Bây giờ bạn nói chuyện điện thoại được không?',
        answer: '죄송한데 지금 회의 중이라서 나중에 다시 전화해도 될까요?',
        grammar: 'N중이다',
        answerVi: 'Xin lỗi, bây giờ tôi đang trong cuộc họp, tôi gọi lại sau được không?',
      },
      {
        level: 'Dễ',
        question: '상담원이 많아요?',
        questionVi: 'Có nhiều nhân viên tư vấn không?',
        answer: '아니요, 오늘은 상담원이 한 명밖에 없어요. 좀 기다려야 해요.',
        grammar: 'N밖에',
        answerVi: 'Không, hôm nay chỉ có một nhân viên tư vấn thôi. Phải đợi một chút.',
      },
      {
        level: 'Trung bình',
        question: '지금 뭐 하고 있어요?',
        questionVi: 'Bây giờ bạn đang làm gì?',
        answer: '지금 고객 문의에 답장을 쓰는 중이에요. 조금만 기다려 주세요.',
        grammar: 'V-는 중이다',
        answerVi: 'Bây giờ tôi đang viết trả lời cho thắc mắc của khách hàng. Chờ tôi một chút nhé.',
      },
      {
        level: 'Trung bình',
        question: '통역 서비스가 필요하세요?',
        questionVi: 'Bạn cần dịch vụ phiên dịch không?',
        answer: '네, 이거 통역이 가능한가요? 한국어를 잘 못해서요.',
        grammar: 'A/V-나요?/은가요?/인가요?',
        answerVi: 'Vâng, cái này phiên dịch được không ạ? Vì tôi không giỏi tiếng Hàn lắm.',
      },
      {
        level: 'Trung bình',
        question: '접수 기간이 많이 남았어요?',
        questionVi: 'Thời hạn đăng ký còn nhiều không?',
        answer: '아니요, 이제 이틀밖에 안 남았어요. 빨리 접수해야 돼요.',
        grammar: 'N밖에',
        answerVi: 'Không, giờ chỉ còn hai ngày thôi. Phải đăng ký nhanh.',
      },
      {
        level: 'Trung bình',
        question: '창구에서 뭐라고 말했어요?',
        questionVi: 'Ở quầy giao dịch bạn đã nói gì?',
        answer: '전화를 바꿔 달라고 했는데요, 담당자가 지금 없대요.',
        grammar: 'A/V-는데요',
        answerVi: 'Tôi đã nói là muốn chuyển máy, nhưng họ bảo người phụ trách hiện không có ở đó.',
      },
      {
        level: 'Nâng cao',
        question: '왜 전화를 안 받아요?',
        questionVi: 'Sao bạn ấy không nghe điện vậy?',
        answer: '지금 통화 중이라서 그런 것 같아요. 조금 있다가 다시 걸어 볼게요.',
        grammar: 'N중이다',
        answerVi: 'Chắc là đang trong cuộc gọi khác nên vậy. Lát nữa tôi gọi lại thử.',
      },
      {
        level: 'Nâng cao',
        question: '이메일로 문의하는 것하고 전화로 문의하는 것 중에서 어느 게 더 빠른가요?',
        questionVi: 'Giữa hỏi qua email và hỏi qua điện thoại, cách nào nhanh hơn?',
        answer: '급한 문제는 전화로 문의하는 게 더 빠른가요? 저는 그렇게 들었어요.',
        grammar: 'A/V-나요?/은가요?/인가요?',
        answerVi: 'Vấn đề gấp thì hỏi qua điện thoại nhanh hơn phải không? Tôi nghe nói vậy.',
      },
      {
        level: 'Nâng cao',
        question: '상담원하고 통화가 안 되면 어떻게 해요?',
        questionVi: 'Nếu không gọi được cho nhân viên tư vấn thì làm sao?',
        answer: '지금은 문자를 보내는 방법밖에 없는 것 같아요. 나중에 답장이 올 거예요.',
        grammar: 'N밖에',
        answerVi: 'Bây giờ hình như chỉ còn cách nhắn tin thôi. Chắc sau này sẽ có trả lời.',
      },
    ],
    grammarSummary: [
      { label: 'A/V-는데요', note: 'Cung cấp thông tin nhưng để ngỏ, chờ phản ứng của người nghe (Câu 1, 7).' },
      { label: 'V-는 중이다', note: 'Đang tiến hành hành động ngay tại thời điểm nói (Câu 4, 8).' },
      { label: 'N 중이다', note: 'Đang trong tình trạng/quá trình (đi với danh từ) (Câu 2).' },
      { label: 'A/V-나요?/은가요?/인가요?', note: 'Câu hỏi lịch sự, nhẹ nhàng hơn -아요?/어요? (Câu 5, 9).' },
      { label: 'N 밖에', note: 'Chỉ có N (luôn đi với vị ngữ phủ định) (Câu 3, 6, 10).' },
    ],
    vocabSummary:
      '문의 (hỏi/thắc mắc), 상담원 (nhân viên tư vấn), 전화를 걸다/받다/끊다 (gọi/nghe/tắt máy), 통역 (phiên dịch), 창구 (quầy giao dịch), 서비스 (dịch vụ), 문자 (tin nhắn), 무료 (miễn phí).',
  },
  10: {
    intro:
      "Bám sát chủ đề ẩm thực và 4 ngữ pháp của Bài 10: N중에(서), 반말, V-(으)ㄹ게요, A/V-는데 (nghĩa 'nhưng').",
    items: [
      {
        level: 'Dễ',
        question: '한국 음식 중에서 뭐가 제일 좋아요?',
        questionVi: 'Trong các món ăn Hàn Quốc bạn thích món nào nhất?',
        answer: '한국 음식 중에서 삼겹살이 제일 좋아요.',
        grammar: 'N중에(서)',
        answerVi: 'Trong các món ăn Hàn Quốc tôi thích thịt ba chỉ nhất.',
      },
      {
        level: 'Dễ',
        question: '김치찌개 매워요?',
        questionVi: 'Canh kimchi có cay không?',
        answer: '좀 매운데 진짜 맛있어요.',
        grammar: "A/V-는데 (nghĩa 'nhưng')",
        answerVi: 'Hơi cay nhưng thực sự ngon.',
      },
      {
        level: 'Dễ',
        question: '(친구한테) 오늘 점심 같이 먹을래?',
        questionVi: '(Nói với bạn thân) Hôm nay ăn trưa cùng nhé?',
        answer: '응, 좋아! 뭐 먹고 싶어?',
        grammar: '반말',
        answerVi: 'Ừ, được đấy! Cậu muốn ăn gì?',
      },
      {
        level: 'Trung bình',
        question: '매운탕 먹어 봤어요? 어땠어요?',
        questionVi: 'Bạn đã ăn canh cá cay chưa? Thế nào?',
        answer: '네, 먹어 봤는데 저한테는 좀 짰어요. 그래도 국물은 시원했어요.',
        grammar: "A/V-는데 (nghĩa 'nhưng')",
        answerVi: 'Vâng, tôi ăn rồi nhưng với tôi thì hơi mặn. Dù vậy nước canh khá đậm đà.',
      },
      {
        level: 'Trung bình',
        question: '냉면하고 칼국수 중에서 어느 게 더 시원해요?',
        questionVi: 'Giữa mì lạnh và mì cắt tay, cái nào mát hơn?',
        answer: '저는 냉면 중에서도 물냉면이 제일 시원한 것 같아요.',
        grammar: 'N중에(서)',
        answerVi: 'Trong các loại mì lạnh, tôi thấy mì lạnh nước là mát nhất.',
      },
      {
        level: 'Trung bình',
        question: '뭐 먹을 거예요?',
        questionVi: 'Bạn sẽ ăn gì?',
        answer: '저는 비빔국수 먹을게요. 좀 매운 걸로 시켜 주세요.',
        grammar: 'V-(으)ㄹ게요',
        answerVi: 'Tôi sẽ ăn mì trộn nhé. Cho tôi loại hơi cay.',
      },
      {
        level: 'Trung bình',
        question: '(친구한테) 이 집 맛집이야?',
        questionVi: '(Nói với bạn) Quán này ngon nổi tiếng à?',
        answer: '응, 완전 맛집이야! 여기 한정식 진짜 맛있어.',
        grammar: '반말',
        answerVi: 'Ừ, ngon nổi tiếng luôn! Cơm Hàn ở đây thật sự ngon.',
      },
      {
        level: 'Nâng cao',
        question: '왜 이 식당에 자주 안 가요?',
        questionVi: 'Sao bạn không đi quán này thường xuyên?',
        answer: '음식은 맛있는데 가격이 너무 비싸서 자주 못 가요.',
        grammar: "A/V-는데 (nghĩa 'nhưng')",
        answerVi: 'Món ăn thì ngon nhưng giá quá đắt nên tôi không đi thường xuyên được.',
      },
      {
        level: 'Nâng cao',
        question: '한식하고 케밥 중에서 어느 게 더 입에 맞아요?',
        questionVi: 'Giữa món Hàn và kebab, cái nào hợp khẩu vị bạn hơn?',
        answer: '저한테는 한식 중에서 순두부찌개가 제일 입에 맞아요. 케밥은 좀 짜요.',
        grammar: 'N중에(서)',
        answerVi: 'Với tôi thì trong các món Hàn, canh đậu phụ non là hợp khẩu vị nhất. Kebab thì hơi mặn.',
      },
      {
        level: 'Nâng cao',
        question: '장을 봐야 하는데 뭐 사 올까요?',
        questionVi: 'Phải đi chợ mua đồ, mua gì về nhỉ?',
        answer: '제가 야채랑 고기는 사 올게요. 다른 재료는 집에 있어요.',
        grammar: 'V-(으)ㄹ게요',
        answerVi: 'Để tôi mua rau và thịt về nhé. Nguyên liệu khác thì ở nhà có rồi.',
      },
    ],
    grammarSummary: [
      { label: 'N 중에(서)', note: 'Chọn/so sánh một đối tượng trong số nhiều (Câu 1, 5, 9).' },
      { label: '반말', note: 'Lối nói thân mật, bỏ 요, đổi cách xưng hô — chỉ dùng với người thân thiết (Câu 3, 7).' },
      { label: 'V-(으)ㄹ게요', note: 'Ý định/cam kết quyết định ngay lúc nói (Câu 6, 10).' },
      { label: "A/V-는데 (nghĩa 'nhưng')", note: 'Nối hai vế có nội dung đối lập nhau (Câu 2, 4, 8).' },
    ],
    vocabSummary:
      '삼겹살 (thịt ba chỉ), 김치찌개 (canh kimchi), 매운탕 (canh cá cay), 비빔국수 (mì trộn), 냉면/칼국수 (mì lạnh/mì cắt tay), 한정식 (cơm Hàn nhiều món), 맵다/짜다/시다 (cay/mặn/chua), 입에 맞다 (hợp khẩu vị), 장을 보다 (đi chợ).',
  },
  11: {
    intro:
      'Bám sát chủ đề sức khoẻ và 3 ngữ pháp của Bài 11: N마다, V-는 게 어때요?, V-기로 하다.',
    items: [
      {
        level: 'Dễ',
        question: '얼마나 자주 아파요?',
        questionVi: 'Bạn hay bị ốm thế nào?',
        answer: '저는 계절마다 감기에 걸리는 것 같아요.',
        grammar: 'N마다',
        answerVi: 'Tôi hình như cứ mỗi khi giao mùa là bị cảm.',
      },
      {
        level: 'Dễ',
        question: '소화가 안 돼서 힘들어요.',
        questionVi: 'Tôi khó tiêu, mệt quá.',
        answer: '그럼 소화제를 좀 먹어 보는 게 어때요?',
        grammar: 'V-는 게 어때요?',
        answerVi: 'Vậy thử uống thuốc tiêu hóa xem sao?',
      },
      {
        level: 'Dễ',
        question: '병원에 가기로 했어요?',
        questionVi: 'Bạn quyết định đi bệnh viện chưa?',
        answer: '네, 내일 아침에 정형외과에 가기로 했어요.',
        grammar: 'V-기로 하다',
        answerVi: 'Vâng, tôi đã quyết định sáng mai đi khoa chỉnh hình.',
      },
      {
        level: 'Trung bình',
        question: '두통이 자주 있어요?',
        questionVi: 'Bạn có hay bị đau đầu không?',
        answer: '네, 요즘 아침마다 머리가 아파서 두통약을 먹어요.',
        grammar: 'N마다',
        answerVi: 'Vâng, dạo này cứ mỗi sáng tôi lại đau đầu nên phải uống thuốc đau đầu.',
      },
      {
        level: 'Trung bình',
        question: '기운이 없어서 걱정이에요.',
        questionVi: 'Tôi mệt mỏi không có sức, lo quá.',
        answer: '그러면 영양제를 좀 먹어 보는 게 어때요? 저도 요즘 먹고 있어요.',
        grammar: 'V-는 게 어때요?',
        answerVi: 'Vậy thử uống thực phẩm bổ sung dinh dưỡng xem? Dạo này tôi cũng đang uống.',
      },
      {
        level: 'Trung bình',
        question: '다리를 다쳤는데 어떻게 할 거예요?',
        questionVi: 'Bị thương ở chân rồi thì bạn sẽ làm gì?',
        answer: '당분간 운동을 쉬기로 했어요. 다 나을 때까지요.',
        grammar: 'V-기로 하다',
        answerVi: 'Tôi đã quyết định tạm nghỉ tập thể dục một thời gian. Đến khi khỏi hẳn.',
      },
      {
        level: 'Trung bình',
        question: '약을 어떻게 먹어요?',
        questionVi: 'Bạn uống thuốc thế nào?',
        answer: '의사 선생님이 식후마다 한 알씩 먹으라고 했어요.',
        grammar: 'N마다',
        answerVi: 'Bác sĩ bảo tôi uống một viên sau mỗi bữa ăn.',
      },
      {
        level: 'Nâng cao',
        question: '왜 요즘 운동을 하나도 안 해요?',
        questionVi: 'Sao dạo này bạn chẳng tập thể dục gì cả?',
        answer: '요즘 너무 바빠서 못 했는데, 사실 의사 선생님도 운동을 좀 해 보는 게 어때요 하고 말씀하셨어요.',
        grammar: 'V-는 게 어때요?',
        answerVi: 'Dạo này quá bận nên tôi không tập được, thật ra bác sĩ cũng bảo tôi nên thử tập thể dục xem.',
      },
      {
        level: 'Nâng cao',
        question: '매일 운동하는 것하고 이틀마다 운동하는 것 중에서 뭐가 나아요?',
        questionVi: 'Giữa tập mỗi ngày và tập cách ngày, cái nào tốt hơn?',
        answer: '처음에는 이틀마다 운동하는 게 몸에 더 좋을 것 같아요. 매일은 힘들 수 있어요.',
        grammar: 'N마다',
        answerVi: 'Lúc đầu tôi nghĩ tập cách ngày sẽ tốt cho cơ thể hơn. Tập mỗi ngày có thể sẽ mệt.',
      },
      {
        level: 'Nâng cao',
        question: '건강을 위해서 뭘 하기로 했어요?',
        questionVi: 'Vì sức khỏe bạn đã quyết định làm gì?',
        answer: '저는 담배를 끊고 매일 아침에 운동하기로 했어요. 그리고 배탈이 안 나게 밥을 천천히 먹기로 했어요.',
        grammar: 'V-기로 하다',
        answerVi: 'Tôi đã quyết định bỏ thuốc lá và tập thể dục mỗi sáng. Và cũng quyết định ăn chậm hơn để khỏi bị đau bụng.',
      },
    ],
    grammarSummary: [
      { label: 'N 마다', note: 'Mỗi, cứ mỗi... theo chu kỳ (Câu 1, 4, 7, 9).' },
      { label: 'V-는 게 어때요?', note: 'Đề nghị/gợi ý nhẹ nhàng, gián tiếp (Câu 2, 5, 8).' },
      { label: 'V-기로 하다', note: 'Quyết định, lời hứa, hoặc kế hoạch đã được chốt (Câu 3, 6, 10).' },
    ],
    vocabSummary:
      '배탈이 나다 (đau bụng), 기운이 없다 (mệt mỏi), 진료를 받다 (đi khám), 낫다 (khỏi bệnh), 다리를 다치다 (bị thương ở chân), 두통약/감기약/소화제 (thuốc đau đầu/thuốc cảm/thuốc tiêu hóa), 어지럽다 (chóng mặt), 정형외과 (khoa chỉnh hình).',
  },
  12: {
    intro:
      'Bám sát chủ đề ngoại hình – tính cách và 4 ngữ pháp của Bài 12: A-아/어 보이다, N처럼[같이], A/V-는 편이다, A-게.',
    items: [
      {
        level: 'Dễ',
        question: '성격이 어때요?',
        questionVi: 'Tính cách bạn thế nào?',
        answer: '저는 좀 조용한 편이에요. 그런데 친해지면 활발해져요.',
        grammar: 'A/V-는 편이다',
        answerVi: 'Tôi thuộc dạng khá trầm tính. Nhưng khi đã thân rồi thì tôi trở nên hoạt bát hơn.',
      },
      {
        level: 'Dễ',
        question: '저 사람 어때 보여요?',
        questionVi: 'Người kia trông thế nào?',
        answer: '좀 내성적으로 보이는데 눈이 커서 첫인상이 좋아요.',
        grammar: 'A-아/어 보이다',
        answerVi: 'Trông có vẻ hơi hướng nội, nhưng mắt to nên ấn tượng đầu khá tốt.',
      },
      {
        level: 'Dễ',
        question: '오빠하고 닮았어요?',
        questionVi: 'Bạn có giống anh trai không?',
        answer: '네, 저는 오빠처럼 눈썹이 진해요.',
        grammar: 'N처럼[같이]',
        answerVi: 'Vâng, tôi có lông mày đậm giống anh trai.',
      },
      {
        level: 'Trung bình',
        question: '면접 볼 때 어떻게 준비했어요?',
        questionVi: 'Khi phỏng vấn bạn đã chuẩn bị thế nào?',
        answer: '옷을 단정하게 입고 자신 있게 말하려고 노력했어요.',
        grammar: 'A-게',
        answerVi: 'Tôi mặc đồ chỉnh tề và cố gắng nói một cách tự tin.',
      },
      {
        level: 'Trung bình',
        question: '꼼꼼한 성격이에요?',
        questionVi: 'Bạn có tính cách tỉ mỉ không?',
        answer: '네, 저는 뭐든지 꼼꼼하게 확인하는 편이에요. 성격이 급한 편은 아니에요.',
        grammar: 'A/V-는 편이다',
        answerVi: 'Vâng, tôi thuộc dạng luôn kiểm tra kỹ mọi thứ. Tôi không phải kiểu người nóng vội.',
      },
      {
        level: 'Trung bình',
        question: '첫인상이 어땠어요?',
        questionVi: 'Ấn tượng đầu tiên thế nào?',
        answer: '처음에는 배우처럼 멋있어 보였는데 이야기해 보니까 진짜 활발한 사람이었어요.',
        grammar: 'N처럼[같이]',
        answerVi: 'Lúc đầu trông đẹp trai như diễn viên, nhưng nói chuyện thì hóa ra là người rất năng động.',
      },
      {
        level: 'Trung bình',
        question: '오늘 좀 피곤해 보여요.',
        questionVi: 'Hôm nay bạn trông có vẻ mệt.',
        answer: '네, 어제 잠을 잘 못 자서 좀 피곤해 보이나 봐요.',
        grammar: 'A-아/어 보이다',
        answerVi: 'Vâng, tối qua ngủ không ngon nên chắc trông mệt vậy.',
      },
      {
        level: 'Nâng cao',
        question: '왜 사람들이 당신을 활발한 사람이라고 생각해요?',
        questionVi: 'Vì sao mọi người nghĩ bạn là người năng động?',
        answer: '제가 낯선 사람하고도 말을 잘 거는 편이라서 다들 그렇게 생각하는 것 같아요.',
        grammar: 'A/V-는 편이다',
        answerVi: 'Chắc vì tôi thuộc dạng bắt chuyện tốt kể cả với người lạ nên ai cũng nghĩ vậy.',
      },
      {
        level: 'Nâng cao',
        question: '사진하고 실물 중에서 어느 쪽이 더 어려 보여요?',
        questionVi: 'Giữa ảnh và ngoài đời, bạn trông trẻ hơn ở đâu?',
        answer: '사진보다 실물이 더 어려 보인다는 말을 자주 들어요.',
        grammar: 'A-아/어 보이다',
        answerVi: 'Tôi hay nghe người ta nói là ngoài đời tôi trông trẻ hơn trong ảnh.',
      },
      {
        level: 'Nâng cao',
        question: '성격을 바꾸고 싶어요?',
        questionVi: 'Bạn có muốn thay đổi tính cách không?',
        answer: '네, 지금보다 좀 더 편하게 말하고 싶어요. 너무 꼼꼼하게 생각하지 않으려고 노력 중이에요.',
        grammar: 'A-게',
        answerVi: 'Có, tôi muốn nói chuyện thoải mái hơn bây giờ. Tôi đang cố gắng đừng suy nghĩ quá tỉ mỉ.',
      },
    ],
    grammarSummary: [
      { label: 'A-아/어 보이다', note: 'Nhận xét/cảm nhận dựa trên vẻ ngoài (Câu 2, 7, 9).' },
      { label: 'N처럼[같이]', note: 'So sánh tương đồng, giống như N (Câu 3, 6).' },
      { label: 'A-(으)ㄴ/V-는 편이다', note: 'Nhận xét tương đối, không tuyệt đối (Câu 1, 5, 8).' },
      { label: 'A-게', note: 'Biến tính từ thành trạng từ, chỉ mức độ/cách thức (Câu 4, 10).' },
    ],
    vocabSummary:
      '내성적이다/활발하다 (hướng nội/năng động), 첫인상 (ấn tượng đầu), 눈이 크다 (mắt to), 눈썹이 진하다 (lông mày đậm), 성격이 급하다 (nóng vội), 꼼꼼하다 (tỉ mỉ), 키가 크다 (cao).',
  },
  13: {
    intro:
      'Bám sát chủ đề nhà ở và 4 ngữ pháp của Bài 13: V/A-(으)ㄹ지 모르겠다, V/A-기는 하지만, V/A-기 때문에, V-기(가) A.',
    items: [
      {
        level: 'Dễ',
        question: '이 방 어때요?',
        questionVi: 'Phòng này thế nào?',
        answer: '방은 좁은데 정리하기가 편해서 괜찮아요.',
        grammar: 'V-기(가) A',
        answerVi: 'Phòng thì chật nhưng dễ dọn dẹp nên cũng ổn.',
      },
      {
        level: 'Dễ',
        question: '이 집 마음에 들어요?',
        questionVi: 'Bạn có ưng căn nhà này không?',
        answer: '방이 넓기는 하지만 월세가 너무 비싸요.',
        grammar: 'V/A-기는 하지만',
        answerVi: 'Phòng thì rộng thật đấy nhưng tiền thuê hàng tháng quá đắt.',
      },
      {
        level: 'Dễ',
        question: '이 동네가 살기 좋아요?',
        questionVi: 'Khu này sống có tốt không?',
        answer: '네, 주변이 조용하기 때문에 살기 좋아요.',
        grammar: 'V/A-기 때문에',
        answerVi: 'Vâng, vì xung quanh yên tĩnh nên sống tốt.',
      },
      {
        level: 'Trung bình',
        question: '부동산에 가 봤어요? 집을 구했어요?',
        questionVi: 'Bạn đã đến chỗ môi giới bất động sản chưa? Tìm được nhà chưa?',
        answer: '네, 가 봤는데 아직 계약할지 모르겠어요. 좀 더 생각해 보려고요.',
        grammar: 'V/A-(으)ㄹ지 모르겠다',
        answerVi: 'Vâng, tôi đã đi rồi nhưng vẫn chưa biết có nên ký hợp đồng hay không. Tôi định suy nghĩ thêm.',
      },
      {
        level: 'Trung bình',
        question: '오피스텔에서 사는 거 어때요?',
        questionVi: 'Sống ở officetel thế nào?',
        answer: '시설이 잘되어 있어서 살기가 편해요. 그런데 관리비가 좀 비싸요.',
        grammar: 'V-기(가) A',
        answerVi: 'Vì cơ sở vật chất tốt nên sống rất thoải mái. Nhưng phí quản lý hơi đắt.',
      },
      {
        level: 'Trung bình',
        question: '왜 이 아파트로 이사하고 싶어요?',
        questionVi: 'Vì sao bạn muốn chuyển đến chung cư này?',
        answer: '이웃들이 친절하기 때문에 이 아파트로 이사하고 싶어요.',
        grammar: 'V/A-기 때문에',
        answerVi: 'Vì hàng xóm thân thiện nên tôi muốn chuyển đến chung cư này.',
      },
      {
        level: 'Trung bình',
        question: '전세하고 월세 중에서 뭐가 나아요?',
        questionVi: 'Giữa jeonse và thuê theo tháng, cái nào tốt hơn?',
        answer: '전세는 보증금이 크기는 하지만 매달 돈을 안 내도 되니까 더 나은 것 같아요.',
        grammar: 'V/A-기는 하지만',
        answerVi: 'Jeonse thì tiền đặt cọc lớn thật đấy, nhưng không phải trả tiền hàng tháng nên tôi thấy tốt hơn.',
      },
      {
        level: 'Nâng cao',
        question: '왜 아직 이사 날짜를 못 정했어요?',
        questionVi: 'Sao bạn vẫn chưa định được ngày chuyển nhà?',
        answer: '새 집 계약이 잘될지 모르겠어서 이사 날짜를 못 정하고 있어요.',
        grammar: 'V/A-(으)ㄹ지 모르겠다',
        answerVi: 'Vì không biết hợp đồng nhà mới có suôn sẻ hay không nên tôi chưa định được ngày.',
      },
      {
        level: 'Nâng cao',
        question: '원룸하고 기숙사 중에서 어디가 더 지내기가 좋아요?',
        questionVi: 'Giữa phòng trọ và ký túc xá, ở đâu dễ sống hơn?',
        answer: '저한테는 기숙사가 친구를 사귀기가 더 좋은 것 같아요. 원룸은 좀 외로워요.',
        grammar: 'V-기(가) A',
        answerVi: 'Với tôi thì ký túc xá dễ kết bạn hơn. Ở phòng trọ hơi cô đơn.',
      },
      {
        level: 'Nâng cao',
        question: '이 집으로 결정했어요?',
        questionVi: 'Bạn đã quyết định chọn căn nhà này chưa?',
        answer: '네, 방값이 좀 비싸기는 하지만 주변 환경이 정말 좋아서 이 집으로 결정했어요.',
        grammar: 'V/A-기는 하지만',
        answerVi: 'Vâng, tiền phòng hơi đắt thật đấy, nhưng vì môi trường xung quanh rất tốt nên tôi đã quyết định chọn căn này.',
      },
    ],
    grammarSummary: [
      { label: 'V/A-(으)ㄹ지 모르겠다', note: 'Không chắc chắn, băn khoăn về một khả năng (Câu 4, 8).' },
      { label: 'V/A-기는 하지만', note: 'Thừa nhận vế trước đúng nhưng bổ sung ý trái ngược ở vế sau (Câu 2, 7, 10).' },
      { label: 'V/A-기 때문에', note: 'Nguyên nhân rõ ràng, khách quan (Câu 3, 6).' },
      { label: 'V-기(가) A', note: 'Đánh giá mức độ dễ/khó/thích hợp của hành động (Câu 1, 5, 9).' },
    ],
    vocabSummary:
      '월세/전세 (thuê theo tháng/jeonse), 보증금 (tiền đặt cọc), 부동산 (bất động sản), 이웃 (hàng xóm), 관리비 (phí quản lý), 오피스텔/원룸/기숙사 (officetel/phòng trọ/ký túc xá), 시설이 잘되어 있다 (cơ sở vật chất tốt).',
  },
  14: {
    intro:
      'Bám sát chủ đề quy tắc – phép lịch sự và 4 ngữ pháp của Bài 14: V-(으)ㄴ 적(이) 있다[없다], V/A-았을/었을 때, V-아도/어도 되다, V-(으)면 안 되다.',
    items: [
      {
        level: 'Dễ',
        question: '여기서 사진을 찍어도 돼요?',
        questionVi: 'Ở đây chụp ảnh có được không?',
        answer: '아니요, 여기는 사진 촬영 금지예요. 저기서는 찍어도 돼요.',
        grammar: 'V-아도/어도 되다',
        answerVi: 'Không, ở đây cấm chụp ảnh. Ở đằng kia thì chụp được.',
      },
      {
        level: 'Dễ',
        question: '박물관 안에서 물건을 만져도 돼요?',
        questionVi: 'Trong bảo tàng sờ vào đồ vật có được không?',
        answer: '아니요, 안에서는 물건을 만지면 안 돼요.',
        grammar: 'V-(으)면 안 되다',
        answerVi: 'Không, bên trong không được sờ vào đồ vật.',
      },
      {
        level: 'Dễ',
        question: '공공장소에서 실수한 적 있어요?',
        questionVi: 'Bạn đã từng làm gì sai ở nơi công cộng chưa?',
        answer: '네, 예전에 도서관에서 전화를 받은 적이 있어요. 정말 창피했어요.',
        grammar: 'V-(으)ㄴ 적(이) 있다[없다]',
        answerVi: 'Có, trước đây tôi từng nghe điện thoại trong thư viện. Xấu hổ lắm.',
      },
      {
        level: 'Trung bình',
        question: '한국에 처음 왔을 때 뭐가 제일 어려웠어요?',
        questionVi: 'Khi mới đến Hàn Quốc lần đầu, điều gì khó nhất với bạn?',
        answer: '한국에 처음 왔을 때 높임말을 쓰는 게 제일 어려웠어요.',
        grammar: 'V/A-았을/었을 때',
        answerVi: 'Khi mới đến Hàn Quốc lần đầu, dùng kính ngữ là điều khó nhất với tôi.',
      },
      {
        level: 'Trung bình',
        question: '지하철에서 지켜야 하는 공중도덕이 뭐예요?',
        questionVi: 'Trong tàu điện ngầm cần tuân thủ đạo đức công cộng nào?',
        answer: '지하철에서는 큰 소리로 통화하면 안 돼요. 그리고 음식도 먹으면 안 돼요.',
        grammar: 'V-(으)면 안 되다',
        answerVi: 'Trong tàu điện ngầm không được gọi điện to tiếng. Và cũng không được ăn uống.',
      },
      {
        level: 'Trung bình',
        question: '친구한테 반말을 해도 돼요?',
        questionVi: 'Nói năng suồng sã (반말) với bạn có được không?',
        answer: '친한 친구한테는 반말을 해도 되는데 처음 만난 사람한테는 안 돼요.',
        grammar: 'V-아도/어도 되다',
        answerVi: 'Với bạn thân thì được, nhưng với người mới gặp lần đầu thì không được.',
      },
      {
        level: 'Trung bình',
        question: '주차 금지 구역에 차를 세운 적 있어요?',
        questionVi: 'Bạn đã từng đỗ xe ở khu vực cấm đậu xe chưa?',
        answer: '네, 모르고 주차 금지 구역에 세운 적이 있는데 벌금을 냈어요.',
        grammar: 'V-(으)ㄴ 적(이) 있다[없다]',
        answerVi: 'Có, tôi từng đỗ nhầm ở khu vực cấm đậu xe và bị phạt tiền.',
      },
      {
        level: 'Nâng cao',
        question: '왜 높임말이 헷갈렸어요?',
        questionVi: 'Vì sao kính ngữ làm bạn lẫn lộn?',
        answer: '어렸을 때부터 반말만 써 봐서 높임말을 쓰는 게 아직 헷갈려요.',
        grammar: 'V/A-았을/었을 때',
        answerVi: 'Vì từ nhỏ tôi chỉ dùng lối nói suồng sã nên dùng kính ngữ vẫn còn lẫn.',
      },
      {
        level: 'Nâng cao',
        question: '도서관하고 카페 중에서 어디가 규칙이 더 엄격해요?',
        questionVi: 'Giữa thư viện và quán cà phê, ở đâu quy tắc nghiêm hơn?',
        answer: '도서관에서는 통화하면 안 되는데 카페에서는 조용히 하면 괜찮아요. 그래서 도서관이 더 엄격해요.',
        grammar: 'V-(으)면 안 되다',
        answerVi: 'Ở thư viện không được gọi điện, còn ở quán cà phê thì nói nhỏ là ổn. Nên thư viện nghiêm hơn.',
      },
      {
        level: 'Nâng cao',
        question: '예절 때문에 당황한 적 있어요?',
        questionVi: 'Bạn đã từng bối rối vì phép lịch sự chưa?',
        answer: '네, 어른한테 한 손으로 물건을 드린 적이 있는데 그건 예의가 아니라고 들었어요.',
        grammar: 'V-(으)ㄴ 적(이) 있다[없다]',
        answerVi: 'Có, tôi từng đưa đồ cho người lớn tuổi bằng một tay, và nghe nói như vậy là không lịch sự.',
      },
    ],
    grammarSummary: [
      { label: 'V-(으)ㄴ 적(이) 있다[없다]', note: 'Kinh nghiệm đã/chưa từng làm một việc (Câu 3, 7, 10).' },
      { label: 'V/A-았을/었을 때', note: 'Khi đã... (thời điểm đã hoàn toàn xảy ra trong quá khứ) (Câu 4, 8).' },
      { label: 'V-아도/어도 되다', note: 'Xin phép/cho phép thực hiện hành động (Câu 1, 6).' },
      { label: 'V-(으)면 안 되다', note: 'Không được phép, cấm (Câu 2, 5, 9).' },
    ],
    vocabSummary:
      '사진 촬영 금지 (cấm chụp ảnh), 금연 (cấm hút thuốc), 만지다 (sờ, chạm), 반말/높임말 (lối nói suồng sã/kính ngữ), 공중도덕 (đạo đức công cộng), 주차 금지 (cấm đậu xe), 예절 (phép lịch sự).',
  },
  15: {
    intro:
      'Bám sát chủ đề cuộc sống – thói quen và 4 ngữ pháp của Bài 15: A-아지다/어지다, V-게 되다, V-기 전에, V-(으)ㄴ 후에.',
    items: [
      {
        level: 'Dễ',
        question: '한국 생활이 어때요?',
        questionVi: 'Cuộc sống ở Hàn Quốc thế nào?',
        answer: '처음에는 힘들었는데 이제 많이 익숙해졌어요.',
        grammar: 'A-아지다/어지다',
        answerVi: 'Lúc đầu vất vả, nhưng giờ đã quen hơn nhiều rồi.',
      },
      {
        level: 'Dễ',
        question: '밥 먹기 전에 뭐 해요?',
        questionVi: 'Trước khi ăn cơm bạn làm gì?',
        answer: '밥을 먹기 전에 손을 씻어요.',
        grammar: 'V-기 전에',
        answerVi: 'Trước khi ăn cơm tôi rửa tay.',
      },
      {
        level: 'Dễ',
        question: '한국어를 배우게 된 이유가 있어요?',
        questionVi: 'Bạn có lý do nào để học tiếng Hàn không?',
        answer: '네, 한국 노래를 좋아해서 한국어를 배우게 됐어요.',
        grammar: 'V-게 되다',
        answerVi: 'Có, vì thích nhạc Hàn nên tôi đã bắt đầu học tiếng Hàn.',
      },
      {
        level: 'Trung bình',
        question: '한국에 유학 온 후에 뭐가 제일 좋았어요?',
        questionVi: 'Sau khi du học ở Hàn Quốc, điều gì tốt nhất với bạn?',
        answer: '한국에 유학 온 후에 좋은 친구들을 많이 사귄 게 제일 좋았어요.',
        grammar: 'V-(으)ㄴ 후에',
        answerVi: 'Sau khi du học ở Hàn Quốc, việc kết được nhiều bạn tốt là điều tốt nhất.',
      },
      {
        level: 'Trung bình',
        question: '한국어 실력이 늘었어요?',
        questionVi: 'Trình độ tiếng Hàn của bạn tiến bộ chưa?',
        answer: '네, 매일 연습해서 그런지 발음이 훨씬 좋아졌어요.',
        grammar: 'A-아지다/어지다',
        answerVi: 'Vâng, chắc vì luyện tập mỗi ngày nên phát âm đã tốt lên nhiều.',
      },
      {
        level: 'Trung bình',
        question: '버스에서 지켜야 하는 예절이 있어요?',
        questionVi: 'Trên xe buýt có phép lịch sự nào cần tuân thủ không?',
        answer: '네, 자리를 양보하기 전에 먼저 어르신이 계신지 살펴봐야 해요.',
        grammar: 'V-기 전에',
        answerVi: 'Có, trước khi nhường ghế cần để ý xem có người lớn tuổi hay không.',
      },
      {
        level: 'Trung bình',
        question: '왜 이 동네에서 계속 살고 싶어요?',
        questionVi: 'Vì sao bạn muốn tiếp tục sống ở khu này?',
        answer: '오래 살다 보니까 정이 들게 됐어요. 그래서 계속 살고 싶어요.',
        grammar: 'V-게 되다',
        answerVi: 'Vì sống lâu nên dần trở nên gắn bó. Nên tôi muốn tiếp tục sống ở đây.',
      },
      {
        level: 'Nâng cao',
        question: '왜 요즘 한국 생활이 편해졌어요?',
        questionVi: 'Vì sao dạo này cuộc sống ở Hàn Quốc của bạn dễ chịu hơn?',
        answer: '친구들이 많이 생겨서 외롭지 않아졌어요. 그래서 생활이 훨씬 편해졌어요.',
        grammar: 'A-아지다/어지다',
        answerVi: 'Vì có nhiều bạn bè nên tôi không còn cô đơn nữa. Nên cuộc sống dễ chịu hơn nhiều.',
      },
      {
        level: 'Nâng cao',
        question: '졸업한 후에 취직하는 것하고 유학 가는 것 중에서 뭐가 나아요?',
        questionVi: 'Sau khi tốt nghiệp, giữa đi làm và đi du học, cái nào tốt hơn?',
        answer: '저는 졸업한 후에 취직하는 게 더 나을 것 같아요. 경험을 먼저 쌓고 싶어요.',
        grammar: 'V-(으)ㄴ 후에',
        answerVi: 'Tôi nghĩ sau khi tốt nghiệp đi làm sẽ tốt hơn. Tôi muốn tích lũy kinh nghiệm trước.',
      },
      {
        level: 'Nâng cao',
        question: '결혼하기 전에 하고 싶은 게 있어요?',
        questionVi: 'Trước khi kết hôn bạn có điều gì muốn làm không?',
        answer: '결혼하기 전에 취직해서 돈을 좀 모으고 싶어요. 그러고 나서 결혼하려고요.',
        grammar: 'V-기 전에',
        answerVi: 'Trước khi kết hôn tôi muốn đi làm và tiết kiệm một chút tiền. Sau đó mới định kết hôn.',
      },
    ],
    grammarSummary: [
      { label: 'A-아지다/어지다', note: 'Biến đổi dần dần của một trạng thái theo thời gian (Câu 1, 5, 8).' },
      { label: 'V-게 되다', note: 'Thay đổi trạng thái do tác động khách quan, không chủ động (Câu 3, 7).' },
      { label: 'V-기 전에', note: 'Trước khi V (động từ không chia thì) (Câu 2, 6, 10).' },
      { label: 'V-(으)ㄴ 후에', note: 'Sau khi V (Câu 4, 9).' },
    ],
    vocabSummary:
      '유학 (du học), 익숙하다 (quen), 친구를 사귀다 (kết bạn), 자리를 양보하다 (nhường ghế), 정(이) 들다 (trở nên gắn bó), 졸업하다/취직하다/결혼하다 (tốt nghiệp/đi làm/kết hôn), 실력이 늘다 (tiến bộ).',
  },
  16: {
    intro:
      'Bám sát chủ đề Tết – lễ truyền thống và 4 ngữ pháp của Bài 16: V-아/어 놓다, N대신, V-(으)ㄹ까 하다, V/A-(으)ㄹ 테니까.',
    items: [
      {
        level: 'Dễ',
        question: '설날에 뭐 먹어요?',
        questionVi: 'Ngày Tết bạn ăn gì?',
        answer: '설날에는 밥 대신 떡국을 먹어요.',
        grammar: 'N대신',
        answerVi: 'Ngày Tết mọi người ăn canh bánh gạo thay cho cơm.',
      },
      {
        level: 'Dễ',
        question: '명절 준비 다 했어요?',
        questionVi: 'Bạn chuẩn bị xong cho dịp lễ chưa?',
        answer: '네, 음식을 미리 만들어 놓았어요.',
        grammar: 'V-아/어 놓다',
        answerVi: 'Vâng, tôi đã làm sẵn đồ ăn từ trước rồi.',
      },
      {
        level: 'Dễ',
        question: '이번 설날에 고향에 갈 거예요?',
        questionVi: 'Tết này bạn có về quê không?',
        answer: '네, 고향에 갈까 해요. 아직 정확히 정하지는 않았어요.',
        grammar: 'V-(으)ㄹ까 하다',
        answerVi: 'Có, tôi đang định về quê. Nhưng vẫn chưa quyết chắc chắn.',
      },
      {
        level: 'Trung bình',
        question: '세배를 어떻게 해요?',
        questionVi: 'Lạy chào năm mới làm thế nào?',
        answer: '제가 먼저 보여 드릴 테니까 따라 해 보세요.',
        grammar: 'V/A-(으)ㄹ 테니까',
        answerVi: 'Để tôi làm mẫu trước, bạn làm theo nhé.',
      },
      {
        level: 'Trung bình',
        question: '한복을 입어 봤어요?',
        questionVi: 'Bạn đã mặc thử hanbok chưa?',
        answer: '네, 명절에는 평소 옷 대신 한복을 입어요. 편하고 예뻐요.',
        grammar: 'N대신',
        answerVi: 'Vâng, vào dịp lễ mọi người mặc hanbok thay cho quần áo thường ngày. Vừa thoải mái vừa đẹp.',
      },
      {
        level: 'Trung bình',
        question: '차례를 지내기 전에 뭘 준비해요?',
        questionVi: 'Trước khi cúng giỗ tổ tiên thì chuẩn bị gì?',
        answer: '조상님을 위해서 음식을 상에 차려 놓아요. 그리고 향도 준비해요.',
        grammar: 'V-아/어 놓다',
        answerVi: 'Người ta bày sẵn đồ ăn lên bàn để cúng tổ tiên. Và cũng chuẩn bị nhang nữa.',
      },
      {
        level: 'Trung bình',
        question: '이번 명절에 뭘 할까 생각 중이에요?',
        questionVi: 'Bạn đang nghĩ sẽ làm gì dịp lễ này?',
        answer: '가족들하고 윷놀이를 할까 해요. 오랜만에 다 같이 모이니까요.',
        grammar: 'V-(으)ㄹ까 하다',
        answerVi: 'Tôi đang định chơi Yut cùng gia đình. Vì lâu rồi mới tụ họp đông đủ.',
      },
      {
        level: 'Nâng cao',
        question: '왜 설날에 떡국을 먹어요?',
        questionVi: 'Vì sao ngày Tết ăn canh bánh gạo?',
        answer: '나이를 한 살 더 먹는다는 의미로 밥 대신 떡국을 먹는다고 들었어요.',
        grammar: 'N대신',
        answerVi: 'Tôi nghe nói ăn canh bánh gạo thay cho cơm mang ý nghĩa là được thêm một tuổi.',
      },
      {
        level: 'Nâng cao',
        question: '명절에 고향에 가는 것하고 집에서 쉬는 것 중에서 뭐가 나아요?',
        questionVi: 'Giữa về quê dịp lễ và ở nhà nghỉ ngơi, cái nào tốt hơn?',
        answer: '고향에 가면 가족들을 볼 수 있을 테니까 저는 고향에 가는 게 더 좋아요.',
        grammar: 'V/A-(으)ㄹ 테니까',
        answerVi: 'Vì về quê chắc chắn sẽ gặp được gia đình nên tôi thấy về quê tốt hơn.',
      },
      {
        level: 'Nâng cao',
        question: '이번 설날 계획이 뭐예요?',
        questionVi: 'Kế hoạch Tết này của bạn là gì?',
        answer: '성묘도 가고 세배도 할까 해요. 조상님한테 감사한 마음을 전하고 싶어서요.',
        grammar: 'V-(으)ㄹ까 하다',
        answerVi: 'Tôi đang định đi tảo mộ và lạy chào năm mới nữa. Vì tôi muốn bày tỏ lòng biết ơn với tổ tiên.',
      },
    ],
    grammarSummary: [
      { label: 'V-아/어 놓다', note: 'Hành động hoàn tất, kết quả được duy trì và chuẩn bị sẵn (Câu 2, 6).' },
      { label: 'N 대신', note: 'Thay thế, thay cho N (Câu 1, 5, 8).' },
      { label: 'V-(으)ㄹ까 하다', note: 'Ý định còn mơ hồ, chưa chắc chắn (chỉ ngôi thứ nhất) (Câu 3, 7, 10).' },
      { label: 'V/A-(으)ㄹ 테니까', note: 'Ý chí/phỏng đoán mạnh kèm đề nghị cho người nghe (Câu 4, 9).' },
    ],
    vocabSummary:
      '설날/명절 (Tết/ngày lễ), 떡국 (canh bánh gạo), 한복 (hanbok), 세배 (lạy chào năm mới), 차례를 지내다 (cúng giỗ tổ tiên), 성묘 (tảo mộ), 윷놀이 (chơi Yut), 고향에 가다 (về quê).',
  },
  17: {
    intro:
      'Bám sát chủ đề sự cố nhỏ trong cuộc sống và 3 ngữ pháp của Bài 17: V-아다/어다 주다, V-(으)ㄹ 뻔하다, V-아/어 있다.',
    items: [
      {
        level: 'Dễ',
        question: '오늘 무슨 일 있었어요?',
        questionVi: 'Hôm nay có chuyện gì vậy?',
        answer: '네, 늦게 일어나서 비행기를 놓칠 뻔했어요.',
        grammar: 'V-(으)ㄹ 뻔하다',
        answerVi: 'Có, tôi dậy muộn nên suýt nữa lỡ chuyến bay.',
      },
      {
        level: 'Dễ',
        question: '지금 문이 열려 있어요?',
        questionVi: 'Bây giờ cửa đang mở à?',
        answer: '네, 문이 열려 있어요. 좀 추워요.',
        grammar: 'V-아/어 있다',
        answerVi: 'Vâng, cửa đang mở. Hơi lạnh đấy.',
      },
      {
        level: 'Dễ',
        question: '친구가 공항까지 데려다 줬어요?',
        questionVi: 'Bạn của bạn đã đưa bạn đến sân bay à?',
        answer: '네, 친구가 차로 공항까지 데려다 줬어요. 정말 고마웠어요.',
        grammar: 'V-아다/어다 주다',
        answerVi: 'Vâng, bạn tôi đã lái xe đưa tôi đến tận sân bay. Tôi thật sự biết ơn.',
      },
      {
        level: 'Trung bình',
        question: '넘어질 뻔한 적 있어요?',
        questionVi: 'Bạn đã từng suýt ngã chưa?',
        answer: '네, 계단에서 뛰다가 넘어질 뻔했어요. 다행히 안 다쳤어요.',
        grammar: 'V-(으)ㄹ 뻔하다',
        answerVi: 'Có, tôi vừa chạy trên cầu thang thì suýt ngã. May mà không bị thương.',
      },
      {
        level: 'Trung bình',
        question: '지갑이 어디에 있어요?',
        questionVi: 'Ví ở đâu vậy?',
        answer: '가방 안에 놓여 있을 거예요. 다시 한번 찾아볼게요.',
        grammar: 'V-아/어 있다',
        answerVi: 'Chắc đang nằm trong túi xách. Để tôi tìm lại lần nữa.',
      },
      {
        level: 'Trung bình',
        question: '아이를 어떻게 학교에 보냈어요?',
        questionVi: 'Bạn đã đưa con đến trường thế nào?',
        answer: '제가 아이를 학교에 데려다 주고 왔어요.',
        grammar: 'V-아다/어다 주다',
        answerVi: 'Tôi đã đưa con đến tận trường rồi mới về.',
      },
      {
        level: 'Trung bình',
        question: '어제 사고가 날 뻔했다면서요?',
        questionVi: 'Nghe nói hôm qua suýt xảy ra tai nạn à?',
        answer: '네, 길을 건너다가 차에 부딪힐 뻔했어요. 정말 놀랐어요.',
        grammar: 'V-(으)ㄹ 뻔하다',
        answerVi: 'Vâng, đang qua đường thì suýt bị xe đụng. Tôi hoảng thật sự.',
      },
      {
        level: 'Nâng cao',
        question: '왜 가방이 바닥에 떨어져 있어요?',
        questionVi: 'Sao cái túi lại nằm dưới sàn vậy?',
        answer: '아까 떨어뜨렸는데 못 봐서 그대로 놓여 있는 것 같아요.',
        grammar: 'V-아/어 있다',
        answerVi: 'Chắc lúc nãy tôi làm rơi mà không để ý nên nó vẫn nằm nguyên đó.',
      },
      {
        level: 'Nâng cao',
        question: '부모님이 데려다 주는 것하고 혼자 가는 것 중에서 뭐가 편해요?',
        questionVi: 'Giữa được bố mẹ đưa đi và tự đi một mình, cái nào tiện hơn?',
        answer: '저는 부모님이 데려다 주는 게 더 편한데, 이제 혼자 가는 연습도 해야 할 것 같아요.',
        grammar: 'V-아다/어다 주다',
        answerVi: 'Tôi thấy được bố mẹ đưa đi tiện hơn, nhưng chắc giờ cũng nên tập tự đi một mình.',
      },
      {
        level: 'Nâng cao',
        question: '오늘 왜 이렇게 정신이 없어요?',
        questionVi: 'Sao hôm nay bạn rối trí thế?',
        answer: '지갑을 잃어버릴 뻔하고 버스도 놓칠 뻔해서 정말 정신이 없었어요. 그래도 다행히 다 잘 해결됐어요.',
        grammar: 'V-(으)ㄹ 뻔하다',
        answerVi: 'Tôi suýt làm mất ví, lại suýt lỡ xe buýt nên thực sự rất rối trí. Nhưng may là mọi thứ đều ổn cả.',
      },
    ],
    grammarSummary: [
      { label: 'V-아다/어다 주다', note: 'Hai hành động nối tiếp diễn ra ở hai địa điểm khác nhau (Câu 3, 6, 9).' },
      { label: 'V-(으)ㄹ 뻔하다', note: 'Suýt nữa thì... (nguy cơ cao nhưng thực tế không xảy ra), luôn chia quá khứ (Câu 1, 4, 7, 10).' },
      { label: 'V-아/어 있다', note: 'Trạng thái kết quả của hành động còn duy trì đến hiện tại (Câu 2, 5, 8).' },
    ],
    vocabSummary:
      '놓치다 (bỏ lỡ), 넘어지다 (ngã), 잃어버리다 (làm mất), 사고가 나다 (xảy ra tai nạn), 부딪히다 (va vào), 떨어뜨리다 (làm rơi), 다행이다 (may mắn), 정신(이) 없다 (rối trí).',
  },
  18: {
    intro:
      'Bám sát chủ đề nhìn lại quá trình học tập và 4 ngữ pháp của Bài 18: V-(으)ㄴ 지, N(이)나, A-다/V-ㄴ다/는다, N(이)다.',
    items: [
      {
        level: 'Dễ',
        question: '한국에 온 지 얼마나 됐어요?',
        questionVi: 'Bạn đến Hàn Quốc được bao lâu rồi?',
        answer: '한국에 온 지 벌써 6개월이 됐어요.',
        grammar: 'V-(으)ㄴ 지',
        answerVi: 'Tôi đến Hàn Quốc đã được 6 tháng rồi.',
      },
      {
        level: 'Dễ',
        question: '한국어를 몇 년이나 공부했어요?',
        questionVi: 'Bạn học tiếng Hàn bao nhiêu năm rồi?',
        answer: '한국어를 3년이나 공부했어요. 시간이 정말 빨리 지나갔어요.',
        grammar: 'N(이)나',
        answerVi: 'Tôi học tiếng Hàn tận 3 năm rồi. Thời gian trôi qua thật nhanh.',
      },
      {
        level: 'Dễ',
        question: '이 동네에 산 지 오래됐어요?',
        questionVi: 'Bạn sống ở khu này lâu chưa?',
        answer: '네, 이 동네에서 산 지 벌써 2년이나 됐어요.',
        grammar: 'V-(으)ㄴ 지',
        answerVi: 'Vâng, tôi sống ở khu này đã 2 năm rồi.',
      },
      {
        level: 'Trung bình',
        question: '처음 왔을 때하고 지금하고 뭐가 달라졌어요?',
        questionVi: 'So với lúc mới đến thì bây giờ có gì khác?',
        answer: '처음보다 친구가 열 명이나 더 생겼어요. 실력도 많이 늘었어요.',
        grammar: 'N(이)나',
        answerVi: 'So với lúc trước tôi có thêm tận mười người bạn. Trình độ cũng tiến bộ nhiều.',
      },
      {
        level: 'Trung bình',
        question: '일기에 오늘 하루를 어떻게 써요?',
        questionVi: 'Bạn viết nhật ký về hôm nay thế nào?',
        answer: '"오늘은 오랜만에 친구를 만난다"처럼 써요. 일기는 반말로 써야 하니까요.',
        grammar: 'A-다, V-ㄴ다/는다',
        answerVi: 'Tôi viết kiểu như "Hôm nay tôi gặp bạn sau một thời gian dài". Vì nhật ký phải viết theo lối văn viết.',
      },
      {
        level: 'Trung bình',
        question: '취직한 지 얼마나 됐어요?',
        questionVi: 'Bạn đi làm được bao lâu rồi?',
        answer: '취직한 지 이제 3개월 됐는데 아직도 배울 게 많아요.',
        grammar: 'V-(으)ㄴ 지',
        answerVi: 'Tôi đi làm được 3 tháng rồi nhưng vẫn còn nhiều thứ phải học.',
      },
      {
        level: 'Trung bình',
        question: '이 사진 속 사람이 누구예요?',
        questionVi: 'Người trong bức ảnh này là ai?',
        answer: '이건 제 대학교 때 사진이에요. 일기에는 "이 사람은 내 첫 한국 친구다"라고 썼어요.',
        grammar: 'N(이)다',
        answerVi: 'Đây là ảnh hồi tôi học đại học. Trong nhật ký tôi đã viết "Người này là người bạn Hàn đầu tiên của tôi".',
      },
      {
        level: 'Nâng cao',
        question: '왜 이렇게 한국어 실력이 많이 늘었어요?',
        questionVi: 'Sao trình độ tiếng Hàn của bạn tiến bộ nhiều vậy?',
        answer: '매일 두 시간이나 한국어를 공부했기 때문에 실력이 많이 는 것 같아요.',
        grammar: 'N(이)나',
        answerVi: 'Chắc vì mỗi ngày tôi học tận hai tiếng tiếng Hàn nên trình độ tiến bộ nhiều.',
      },
      {
        level: 'Nâng cao',
        question: '한국에 산 지 오래된 사람하고 얼마 안 된 사람 중에서 누가 더 잘 적응해요?',
        questionVi: 'Giữa người sống ở Hàn Quốc lâu và người mới sống chưa lâu, ai thích nghi tốt hơn?',
        answer: '보통 한국에 산 지 오래된 사람이 문화에 더 익숙해서 잘 적응하는 것 같아요.',
        grammar: 'V-(으)ㄴ 지',
        answerVi: 'Thường thì người sống ở Hàn Quốc lâu quen văn hóa hơn nên thích nghi tốt hơn.',
      },
      {
        level: 'Nâng cao',
        question: '6개월 동안 뭐가 제일 기억에 남아요?',
        questionVi: 'Trong suốt 6 tháng qua điều gì đọng lại nhất với bạn?',
        answer: '"시간이 정말 빨리 지나간다"는 생각이 제일 많이 들어요. 처음보다 모든 게 많이 바뀌었어요.',
        grammar: 'A-다, V-ㄴ다/는다',
        answerVi: 'Suy nghĩ "thời gian trôi qua thật nhanh" là điều tôi nghĩ nhiều nhất. Mọi thứ đã thay đổi rất nhiều so với lúc đầu.',
      },
    ],
    grammarSummary: [
      { label: 'V-(으)ㄴ 지', note: 'Khoảng thời gian đã trôi qua kể từ khi V (Câu 1, 3, 6, 9).' },
      { label: 'N(이)나', note: 'Số lượng nhiều hơn, vượt xa so với mong đợi (Câu 2, 4, 8).' },
      { label: 'A-다, V-ㄴ다/는다', note: 'Đuôi trần thuật văn viết — dùng trong nhật ký, báo chí (Câu 5, 10).' },
      { label: 'N(이)다', note: 'Dạng danh từ của lối văn viết trần thuật (Câu 7).' },
    ],
    vocabSummary:
      '시간이 지나가다 (thời gian trôi qua), 변화 (sự thay đổi), 오랜만에 (sau thời gian dài), 바뀌다 (thay đổi), 추억 (kỷ niệm), 실력이 늘다 (tiến bộ), 발전하다 (phát triển), 아직도 (vẫn còn).',
  },
}
